### ISSUE TITLE
[client-shell] Add -v / --verbose

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1061]
This option should interface with the standard `log` library.  If the option is not given, the logs should be directed to a null output.  If the option is given, direct that output to stderr.

**Comment by Jo-IE** [comment]
Hi @djmitche is this issue open to outreachy applicants? Thanks!

**Comment by djmitche** [comment]
It is, but note that it's in Go, not JS!

**Comment by Jo-IE** [comment]
I just started learning Go and I would like to learn more, could I still work on it?

**Comment by Jo-IE** [comment]
bump

**Comment by Jo-IE** [comment]
Are these the steps to follow when getting this set up? https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md#hacking-on-clients

**Comment by djmitche** [comment]
No, that's a little outdated in fact, since it doesn't mention client-shell.

Like most go projects, you should be able to just run `go test ./...` in the `clients/client-shell` directory to get the tests to run.  Unlike most go projects this one uses `go mod` so it doesn't need to be checked out in a particular directory -- it should just work.  Note that you'll need go1.12.9.

**Comment by Jo-IE** [comment]
ok thank you!

**Comment by Jo-IE** [comment]
Hi @djmitche sorry for not getting back to you sooner but here is my progress so far:

I understand that I am to make a `verbose -v` flag for the `version` command that directs output to stderr when present or null otherwise and this should be implemented using the `log` library.

I am guessing we will be using the `output` function from the `log` library `log.Output(calldepth, string)` to implement the output. However, I do not understand what the function is supposed to be doing. For example, if I had something like `log.Output(1, "verbose")`, I do not know what that is supposed to print in this context. 

Any tips would be helpful!

Thank you.

**Comment by djmitche** [comment]
I think we want this option for *all* commands, not just `version`.  Logging for the `version` command isn't that interesting!  Maybe a better example is the `taskcluster group cancel` command?

I think this will involve a few things:

1. setting up a [Logger](https://golang.org/pkg/log/#Logger) that is available for every command
1. configuring that logger (via `l.SetOutput`) based on whether `--verbose` was passed
1. updating commands that output some status while they work (such as "cancelling task <taskId>") to use the Logger instead of just calling `fmt.Fprintf`.

I don't think there are many examples of the latter.  The first two steps will be the more time-consuming steps.

**Comment by vnzongzna** [comment]
Hi @djmitche 
I would like to work on this issue 🙂

**Comment by djmitche** [comment]
It's all yours!

**Comment by vnzongzna** [comment]
@djmitche since all the subcommands are separated by packages, do we have to define a `verbose` flag in each command seperately? or can we have a single `PersistentPreRun` that can be defined for `root` command and pass use that instead?
A sample snippet that I could find from [Scaffold](https://github.com/GoogleContainerTools/skaffold/blob/69776b15674898a87ac61b9431f93ee68cffa6fd/cmd/skaffold/app/cmd/cmd.go#L49)
```go
func Command() *cobra.Command {
	rootCmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		if err := setUpLogs(os.Stdout, v); err != nil {
			return err
		}
		return nil
	}
	rootCmd.PersistentFlags().StringVarP(&v, "verbose", "v", logrus.WarnLevel.String(), "Log level (debug, info, warn, error, fatal, panic")

	return rootCmd
}
```

**Comment by djmitche** [comment]
I don't know much about Cobra, but if that approach works, it seems like the best solution.
