### ISSUE TITLE
Task group without a decision task repeatedly shows an error

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1156]
When viewing [this](https://taskcluster-ui.herokuapp.com/tasks/groups/B-8evnFQRbuX6yeLO49IRg) task group, I get an error bar:

![image](https://user-images.githubusercontent.com/28673/62472850-9c1d6080-b76d-11e9-977b-0c10fcaf2bdb.png)

After dismissing this, it reappears almost instantly.  It looks like it's looking for the decision task (since it's referring to a taskId matching the taskGroupId).

**Comment by helfi92** [comment]
> After dismissing this, it reappears almost instantly.

This issue probably only happens when the task group is running, re-showing the error whenever an update happens and the listener triggers.

Culprit: When the task event listener triggers, the error object reference changes which makes the ErrorPanel component re-display the error since the `error` prop reference changes.

**Comment by helfi92** [comment]
@djmitche How often is there a task group without a decision task?

**Comment by djmitche** [comment]
In Firefox CI, rarely, but in general, quite often.
