### ISSUE TITLE
Task "Edit" button does not correctly fill in the editor

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1159]
**Describe the bug**
When selecting the "Edit" option, I'm taken to a blank "Create Task" page

**To Reproduce**
1. Go to https://dustin.taskcluster-dev.net/tasks/CM18iwb-T6CU4G49mqxREw (or any active task)
2. Click on "Edit"
4. See empty editor

**Expected behavior**
An editor prepared with the contents of the task.

**Comment by helfi92** [comment]
To fix this issue, you would need to delete the indexed DB `taskDefinitons` table.

![Screen Shot 2019-08-06 at 10 30 00 AM](https://user-images.githubusercontent.com/3766511/62548685-31cff300-b835-11e9-9951-539afc95ff53.png)

We could technically do a https://dexie.org/docs/Dexie/Dexie.version() version upgrade but since that change was done a while ago when nobody outside Taskcluster was using this site at the time, I think we could keep the same version and just have a couple of people delete that table.

**Comment by djmitche** [comment]
Indeed, that fixed it - thanks!
