### ISSUE TITLE
[UI] link not appearing

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1384]
STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/worker-manager/gecko-1%2Fwin2012-gamma
2. Switch to the light theme by clicking the light bulb icon

<img width="423" alt="Screen Shot 2019-09-24 at 11 54 15 AM" src="https://user-images.githubusercontent.com/3766511/65528277-10e55f00-dec2-11e9-83be-640388e7c9a1.png">

Acutal (the text ci-admin is missing):

<img width="578" alt="Screen Shot 2019-09-24 at 11 55 25 AM" src="https://user-images.githubusercontent.com/3766511/65528360-370aff00-dec2-11e9-97cf-2779cddaa042.png">

Expected: Links are shown (the text ci-admin is shown)

<img width="1517" alt="Screen Shot 2019-09-24 at 11 54 49 AM" src="https://user-images.githubusercontent.com/3766511/65528339-2ce90080-dec2-11e9-91de-3036562ca462.png">

**Comment by Shubhamchinda** [comment]
I'd like to take this!

**Comment by Shubhamchinda** [comment]
Hey @helfi92 , I hope you're doing great!

I think the problem is in [mozilla-frontend-infra/components/Markdown](https://github.com/mozilla-frontend-infra/components/blob/master/src/components/Markdown/index.jsx) as the link may has styling issues when the theme is light( As we can click on it but it's not visible ).

Am I going in right direction?

Thanks!

**Comment by djmitche** [comment]
(commented on the issue linked ^^ just above)

**Comment by helfi92** [comment]
`@mozilla-frontend-infra/components@2.4.5` contains the fix. Thanks @Shubhamchinda!

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/pull/1638.
