### ISSUE TITLE
[UI] Copy/paste broken in live log pages

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#1405]
**Describe the bug**

It isn't possible to select/copy test from the live log of a task from the "Run Logs" tab.

**To Reproduce**

1. Go to a running task in the "Task & Group Inspector"
2. Click on "Run Logs"
3. Scroll down to the logs
4. Try to select/copy text

**Expected behavior**

It should be possible to select text, it to be highlighted when selected, and then copy it to the desktop session clipboard.

**Platform (please complete the following information):**

 - Firefox 69.0.1/macOS

**Comment by djmitche** [comment]
@petemoore can you confirm this is in the new UI?

**Comment by katherine95** [comment]
@djmitche Has anyone taken up this task?

**Comment by djmitche** [comment]
Not yet.  I think the first thing to do would be to confirm that this bug is, in fact, the case -- I believe since @petemoore mentioned "Task & Group Inspector" that this is the old UI (for example, https://tools.taskcluster.net/groups/Gw48tjKCSxah55TSN8JGxQ/tasks/J79ITApVTW6zwcmb1vHXuQ/runs/0/logs/public%2Flogs%2Flive.log).

You can try the taskId from that link in the new UI, and try copy/pasting out of the live logs.  Try it in Firefox and Chrome, and try it after scrolling up and down the live log, just to be sure.

Thanks!

**Comment by katherine95** [comment]
Okay, trying it out. Will let you know

**Comment by katherine95** [comment]
@djmitche just to seek clarification, am I reproducing it correctly in the new UI? Below is a [gif ](http://g.recordit.co/WUWRb9tqVs.gif)with how I am trying to reproduce it. It seems to allow copy/paste.

http://g.recordit.co/WUWRb9tqVs.gif

**Comment by djmitche** [comment]
I think the gif cuts off before the interesting part (i see you clicking on the live log link..) but yes, the part I see looks correct.  So yes, I think this works fine!  Thanks for verifying!

**Comment by katherine95** [comment]
Oh I see the gif record didn't complete, any way you are welcome.
