### ISSUE TITLE
[UI] Remove horizontal line from Task view

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1421]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/tasks/JH1bEpjqRTi_AhcpulPnxQ

**Expected behavior**
No horizontal line displayed.

<img width="1656" alt="Screen Shot 2019-09-30 at 5 35 58 PM" src="https://user-images.githubusercontent.com/3766511/65918966-071f9800-e3a9-11e9-8392-1cd95c0756e4.png">

**Current behavior**
<img width="1639" alt="Screen Shot 2019-09-30 at 5 36 10 PM" src="https://user-images.githubusercontent.com/3766511/65918967-07b82e80-e3a9-11e9-850f-76dd7534c03d.png">

**Comment by pachicodes** [comment]
Hello, I am an outreachy applicant and would like to work on this issue!
TY

**Comment by djmitche** [comment]
Hi! In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

**Comment by olympiawoj** [comment]
Hey @djmitche! I've completed the first step of the app & would like to work on this issue as my first contribution.

**Comment by olympiawoj** [comment]
I am trying to re-create the issue in my local environment and am getting a connection error while the UI stays in a loading state. I have my web server running on port 3050 and my project running on http://localhost:5080/ with no other connections running - please advise.

_[HPM] Error occurred while trying to proxy request /graphql from localhost:5080 to http://localhost:3050 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)_

ECONNRESET (Connection reset by peer): A connection was forcibly closed by a peer. This normally results from a loss of the connection on the remote socket due to a timeout or reboot. Commonly encountered via the http and net modules.

<img width="1124" alt="Screen Shot 2019-10-01 at 6 10 40 PM" src="https://user-images.githubusercontent.com/41010759/66004450-da39b680-e476-11e9-818b-d4edc0d289b2.png">

**Comment by vishakhanihore** [comment]
> Hi! In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

@djmitche Please assign me the issue, I have completed the first step and mailed the result to you as well

**Comment by mkneumann777** [comment]
I believe I can tackle this issue.

**Comment by ajinkabeer** [comment]
Hello @djmitche,
I have sent you my GitHub username via email. Can I work on this issue?

**Comment by devnoorfatima** [comment]
I have accepted the invitation for collaboration. Can you please assign this issue to me.

**Comment by djmitche** [comment]
Hi everyone!

pachicodes, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

@olympiawoj has completed that step and is the first to comment here, so I will assign to them.  I apologize to @vishakhanihore @mkneumann777 @ajinkabeer and @devnoorfatima!

**Comment by devnoorfatima** [comment]
@olympiawoj  do you need any help in this issue.

**Comment by vishakhanihore** [comment]
Hello @olympiawoj , Feel free to ask for any help regarding the issue 🙃

**Comment by helfi92** [comment]
I haven't heard from @olympiawoj for a while. This task is free to grab now. I think what's left is to to simply rebase the pull-request.

**Comment by devnoorfatima** [comment]
can i take it

**Comment by devnoorfatima** [comment]
@helfi92  I have made the PR for this issue https://github.com/taskcluster/taskcluster/pull/1847
