### ISSUE TITLE
SyntaxError in ui/docs/manual/using/namespaces.mdx

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1472]
```
WARNING in ./docs/manual/using/namespaces.mdx
Module build failed (from ./node_modules/mdx-loader/index.js):
SyntaxError: unknown: Unexpected token (245:60)

  243 | <Warning>
  244 | In some cases, projects need additional scopes.
> 245 | To do so, create a role `project:<project>:grants/<grantName` containing the desired scopes.
      |                                                             ^
  246 | This role can then be assumed where necessary, or project admins can use it to grant specific scopes as desired.
  247 | </Warning>
  248 |     </MDXLayout>
```

I'm not sure why mdx-loader considers this a "warning" instead of an error.

@vishakhanihore did you see this issue when you made these changes?

**Comment by djmitche** [comment]
Hm, I actually don't know how to fix this..

**Comment by djmitche** [comment]
The bits I don't know:
 * how to make this error show up in CI
 * how to allow writing "regular" Markdown within `<Warning>..</Warning>`.

**Comment by vishakhanihore** [comment]
I will take a look as soon as I get free from my classesm

**Comment by vishakhanihore** [comment]
> ```
> WARNING in ./docs/manual/using/namespaces.mdx
> Module build failed (from ./node_modules/mdx-loader/index.js):
> SyntaxError: unknown: Unexpected token (245:60)
> 
>   243 | <Warning>
>   244 | In some cases, projects need additional scopes.
> > 245 | To do so, create a role `project:<project>:grants/<grantName` containing the desired scopes.
>       |                                                             ^
>   246 | This role can then be assumed where necessary, or project admins can use it to grant specific scopes as desired.
>   247 | </Warning>
>   248 |     </MDXLayout>
> ```
> 
> I'm not sure why mdx-loader considers this a "warning" instead of an error.
> 
> @vishakhanihore did you see this issue when you made these changes?

@djmitche AFAIK, Such issues didn't come up in my PR #1451 as the CI passed at that time.
BTW is this error coming up in `console` or `CI Build` ?

**Comment by djmitche** [comment]
It's coming up in the terminal where I ran `yarn start`.  It doesn't seem to show up in CI -- I'm not sure why!  Thanks for your notes..

**Comment by vishakhanihore** [comment]
@djmitche My fork is insync with the upstream/master and I still cant see this error in web-server nor ui.

**Comment by djmitche** [comment]
I merged the PR, so it's fixed in master now :)

**Comment by vishakhanihore** [comment]
@djmitche I found the error, see here : https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md . That was the whole reason the error was shown on console rather than getting shown on CI Clients.

**Comment by vishakhanihore** [comment]
Can I look into this issue ?

**Comment by vishakhanihore** [comment]
> @djmitche I found the error, see here : https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md . That was the whole reason the error was shown on console rather than getting shown on CI Clients.

or what we can do is to ignore the `MarkDown` docs for checking of following rule ? @helfi92

**Comment by helfi92** [comment]
Sure, that works.

**Comment by vishakhanihore** [comment]
@djmitche @helfi92 The following issue is not related to any checks , Sorry for my naive observation.
After deeper digging such syntax is not recognised as valid one in `mdx-js`, But this issue is already solved in `mdx-js` library, But since we are not using `mdx-js` directly and using `mdx-loader` which is depreciated a long ago. 
Please tell me what would be right approach for this, Create our own fork for `mdx-utils` or start using `mdx-js`.

References :
https://github.com/mdx-js/mdx/issues/486
https://github.com/mdx-js/mdx/issues/628
https://github.com/jamesknelson/mdx-loader (**Depreciated long ago and also archived**)
https://github.com/frontarm/mdx-util ( Updated mdx-loader home)
https://github.com/frontarm/mdx-util/issues/55#issuecomment-526028233 (Issue telling `mdx-js` is depreciated in the following)

**Comment by djmitche** [comment]
I'm impressed with your skills in investigating JS dependencies -- it's a rare talent :)

It seems like the right course would be to use the mdx-loader functionality in mdx-util.  But you mention a fork -- why would that be needed?  Could we instead make a PR to mdx-util?

**Comment by vishakhanihore** [comment]
> I'm impressed with your skills in investigating JS dependencies -- it's a rare talent :)

Thanks, but its just some googling and stack overflow stuff 😅 .


> It seems like the right course would be to use the mdx-loader functionality in mdx-util. But you mention a fork -- why would that be needed? Could we instead make a PR to mdx-util?

Firstly, We have to determine which dependency is using `mdx-loader` as a peer. Since `mdx-loader` is not directly used in our `package.json` after that, we have to upgrade that dependency to use `mdx-util` instead of `mdx-loader` and if we are successful in that, I think we can send a PR to mdx-util, as it is maintained regularly.
@helfi92 @djmitche Your views and suggestions?

**Comment by helfi92** [comment]
> Firstly, We have to determine which dependency is using mdx-loader

It's being used by the ui:

https://github.com/taskcluster/taskcluster/blob/6daa7663b9e1091521961093f363ea52886b89ae/ui/package.json#L65

**Comment by vishakhanihore** [comment]
@helfi92
Firstly, my plan is to upgrade the mdx-loader to mdx-util.
Afterwards if the following is still present I will send a PR to mdx-util
upgrading the mdx-js.
How does in sound?

**Comment by djmitche** [comment]
Sounds good!

**Comment by djmitche** [comment]
I think this got fixed up :)
