### ISSUE TITLE
Visually divide API references into categories

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1577]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

In [bug 1551848](https://bugzilla.mozilla.org/show_bug.cgi?id=1551848) and #1049 , @subhamskm  added a `category` to each API method. That category doesn't show up in the [documentation](https://community-tc.services.mozilla.com/docs/reference/platform/auth/api) though.

It would be great to use these categories as small "headings" in the list of API methods, in cases where there is more than one category (such as the Auth service).  In cases where there is only one category, there should be no change.

Mocked up with GIMP:
![sketch](https://user-images.githubusercontent.com/28673/66653862-f374fc80-ec06-11e9-8d6d-72ab53b04a11.png)

**Comment by helfi92** [comment]
The task would involve modifying web-server to expose this new property and then modifying the UI to display a subheader.

**Comment by JiwoonKim** [comment]
May I take this issue please, if all other outreachy applicants have already taken one?

**Comment by djmitche** [comment]
This is static API data that's baked into the UI image -- no need for web-server changes.

**Comment by JiwoonKim** [comment]
Hi @djmitche .  My idea of implementing this issue is the following:

1. categorize the entries by `category`: create a map which stores (category, list of entries) 
2. display the entries by category using conditional rendering
    - if there is only one entry in the category: don't display headings
    - if there is more than one entry in the category: display small headings above

I've already implemented the first part and am coding the second part at the moment, but came to realize that coding the second part directly into the `ApiReference` component's render() section seems a bit cluttery and not conforming to the principle of separation of concerns.

I was wondering if you could help guide me concerning this issue. Would it be okay to implement the conditional rendering part as a separate component such as `EntryCategory` ? Or is there maybe a different approach into conditional rendering without cluttering the render() section?

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/ab269e18717d3145047dc92803f78ced09452be4.
