### ISSUE TITLE
[taskcluster-web]: Show "recently-created" task definitions

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#164]
As I rotate between tickets I'm working on, I need to re-create some very similar builds. For example, last week, I created some tasks that would trigger a build on my custom `worker_type`. However, it's been a couple work days, and I've changed contexts. I can't quite remember exactly how my task definition looked, so I need to re-create it. It would potentially be neat if I could use recently-created task definitions.

Note: I'm not sure how you could handle de-duping: I wouldn't want to see _every_ task definition I've created, because they'll all be vaguely different with different timestamps. For me, I've probably spun up over 50 tasks in the last week, but I've only done maybe 3 "types" of tasks.

**Comment by djmitche** [comment]
They could possibly be grouped by `metadata.label`, so it only shows the latest with a particular label.  If @helfi92 thinks this is a good idea, then it will probably make a great contributor project!

**Comment by helfi92** [comment]
I like this idea a lot! Let's make it happen.

@djmitche, `metadata.label` doesn't seem to be defined in the task definition schema. Did you mean `metadata.name`?

**Comment by djmitche** [comment]
Yes, sorry!  (we call it "label" in the Gecko taskgraph code..)

**Comment by helfi92** [comment]
STR:

1. Navigate to http://localhost:5080/tasks/create
2. Login. The instructions for logging in can be found in https://github.com/taskcluster/taskcluster/tree/master/ui#web-server. You'll need to clone the server and make sure you follow the instructions that shows you how to set up the `rootUrl`. More information on the server can be found [here](https://github.com/taskcluster/taskcluster/tree/master/services/web-server#readme)
3. Click the plus icon (Create Task) button to create the task. You'll know that it worked when you get navigated away to the task view.
4. Navigate back to http://localhost:5080/tasks/create

**Actual**: There is no list showing recently created tasks

**Expected**: A list is shown displaying recently created tasks (1 task in our case)

---

Possible questions you may have:

1. How do I create the list?

Refer to https://github.com/taskcluster/taskcluster/blob/32673bfefcb072fecce052d814a2d1738f5be5df/ui/src/views/Tasks/NoTask/index.jsx#L52-L71 for inspiration.

2. Where and how do I store the task definitions?

We use [`Dexie.js`](https://dexie.org/) to store collections in the browser. Let's store the 5 most recent task definitions created. If a user creates a 6th one, we should override the old saved task. 

We use Dexie.js to store the 5 most recent tasks. For example if you navigate to https://taskcluster-web.netlify.com/tasks/fBCfJ3vFRK-3zYVPs8SsLw and then https://taskcluster-web.netlify.com/tasks/e-vSE19-RQWZiaxeh2BrLQ then in https://taskcluster-web.netlify.com/tasks you will see a list of the recent viewed tasks. You can look at how they were implemented since it will probably be something really similar to saving task definitions. Here's some code for you to look at for inspiration:

https://github.com/taskcluster/taskcluster/blob/a60f57c3215c46022a3f0d6f59834bb9134359c1/ui/src/utils/db.js

https://github.com/taskcluster/taskcluster/blob/32673bfefcb072fecce052d814a2d1738f5be5df/ui/src/views/Tasks/NoTask/index.jsx#L28-L31

In order to store task definitions, you can use the `metadata.name` as the unique key. For example in

![screen shot 2019-02-07 at 10 22 34 am](https://user-images.githubusercontent.com/3766511/52421603-5df6fb00-2ac2-11e9-8cec-30bc0eb788fb.png)

the default name is "Example Task" as shown on line 14 when the user first navigates to the Create Task view.

**Comment by iFlameing** [comment]
I would like to work on this issue

**Comment by helfi92** [comment]
Awesome! Go for it.

**Comment by iFlameing** [comment]
@helfi92 How I can sign in taskcluster ui. I already configured my user-config.yml in web-server. you can see my user-config at this [link](https://pastebin.com/MsiVwp5L).

**Comment by helfi92** [comment]
Remove the github stuff. Replace the file with:

```
defaults:
  taskcluster:
    rootUrl: https://taskcluster.net
```

**Comment by helfi92** [comment]
After that, you will need get taskcluster credentials via https://github.com/taskcluster/taskcluster/tree/master/services/web-server#taskcluster-credentials.

**Comment by iFlameing** [comment]
@helfi92 I download the binary file for linux-amd64 and execute command `chmod +x taskcluster` and after that I run the executable file `./taskcluster` but nothing happened and my terminal shows taskcluster command not found. How I can resolve this?

**Comment by helfi92** [comment]
Make sure you are running `chmod +x taskcluster` in the same directory where that binary is downloaded.

**Comment by iFlameing** [comment]
Screenshot of the error .![screenshot from 2019-02-14 00-18-18](https://user-images.githubusercontent.com/33936987/52735647-1f939b80-2fee-11e9-95de-ec04f65a233c.png)

**Comment by helfi92** [comment]
It seems to be working. Now run `./taskcluster signin --name taskcluster-web-server`.

**Comment by iFlameing** [comment]
@helfi92 when I execute this I successfully signed in and my terminal showed up with this Credentials output as environment variables where I can find my access-token I found my client id.

**Comment by helfi92** [comment]
You don't need the json certificate. You can leave that input field empty. The access token should be there somewhere beside the client ID :)

**Comment by iFlameing** [comment]
@helfi92 thanks for helping me I successfully signed in :)

**Comment by helfi92** [comment]
Awesome!

**Comment by iFlameing** [comment]
@helfi92 I saw the code of ceateTask and I am thinking that I should create a functional component in createTask folder which handles list rendering logic and use the same database(db.taskIdsHistory
) which is already available and passed the recently added task to functional component.what do you think? another doubt, should I place this Tasklist above the codeEditor or below?

**Comment by helfi92** [comment]
> I should create a functional component in createTask folder which handles list rendering logic

Sure. Feel free to do whatever you think will fix the issue. We can always make some changes later after the initial pull-request.

> use the same database(db.taskIdsHistory)

You'll want to use the same database but with different key to index the data. I think the value of `metadata.name` would make a good key to index on.

> should I place this Tasklist above the codeEditor or below?

You can do what you think feels right. It shouldn't be too hard to change later during the review process :)
