### ISSUE TITLE
[UI] Fix view title

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1682]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/worker-manager
2. Click on `taskcluster-imaging/taskcluster-imaging-ci`
3. Look a the view title

![Screen Shot 2019-10-18 at 8 52 29 AM](https://user-images.githubusercontent.com/3766511/67095717-a2c04f00-f184-11e9-928f-32c6319a646b.png)

**Expected behavior**
It should say "Errors for "taskcluster-imaging/taskcluster-imaging-ci"

**Comment by JiwoonKim** [comment]
May I take this issue?

**Comment by JiwoonKim** [comment]
@helfi92 

**Reason Behind Bug**
I played a little bit with the components in `WMViewErrors` and found that this error stems from the problem that the `Dashboard` component uses a `makeTitle()` method, which changes the parameter value uppercase but also as a side-effect eliminates characters such as: -, / ", etc. 
(method is from the change-case library. specifics at https://github.com/blakeembrey/title-case )

To explain more specifically, the changes apply as the following:
- parameter within `WMViewErrors`: 
   - **taskcluster-imaging/taskcluster-imaging-ci**

- `Dashboard` component takes the parameter as title props with prefix "Errors for":
   - renders it through `makeTitle()` to result in the following
   - **Errors For Taskcluster Imaging Taskcluster Imaging Ci**

**Possible Solutions**
Since the issue is in the `Dashboard` component, I was thinking of mainly two solutions:

1. expose a `withoutTitleChange` prop to the Dashboard component which prevents the `makeTitle()` method to run on the title props given
   - this will preserve the parameter format given as title prop
   - however, the problem is that if using a prefix ("Errors for" in this case) along with the parameter, you will need to make sure it is written in uppercase (ex. "Errors For")

2. expose a `withParameter` prop to the Dashboard component to attach an added value to the title
    - title prop "Errors for" is changed to uppercase by `makeTitle()` method
    - simply attach the `withParameter` prop to that uppercased title and use that as final title for Dashboard

I'm thinking the second solution may be better, but would like to know your thoughts on this idea before I implement anything! And thanks in advance for reading a long proposal :)

**Comment by helfi92** [comment]
Nice write-up! I'm leaning more towards the first option. I think this will be similar to the `disableTypography` prop in [`ListItemText`](https://material-ui.com/api/list-item-text/#listitemtext-api). We can even call the prop `disableTitleFormatting` :)

**Comment by JiwoonKim** [comment]
> Nice write-up! I'm leaning more towards the first option. I think this will be similar to the `disableTypography` prop in [`ListItemText`](https://material-ui.com/api/list-item-text/#listitemtext-api). We can even call the prop `disableTitleFormatting` :)

Thanks for the direction! I'll soon implement changes and submit a pull request.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/08a316b1111cab297910034ca7f42c75a05d087a.
