### ISSUE TITLE
Task group list doesn't refresh

### ISSUE THREAD

**Issue by glandium** [taskcluster/taskcluster#1838]
Opening a task group view (e.g. https://community-tc.services.mozilla.com/tasks/groups/FLgCbQUZRVihnZSTLKVpjw) while tasks are proceeding doesn't show any progress. That is, the status of tasks never changes dynamically, and reloading the page is required. (Using Firefox 70)

**Comment by naima-shaikh** [comment]
@glandium  May i take this one ? It looks interesting :) Thanks

**Comment by helfi92** [comment]
`GRAPHQL_SUBSCRIPTION_ENDPOINT` in the community deployment is currently set as `/subscription` but should instead be set to `https://community-tc.services.mozilla.com/subscription`.

**Comment by helfi92** [comment]
@djmitche This should probably be changed in gcloud. Hm, I'm not sure if I have permissions. I can't seem to locate the env vars for the cluster in the gcloud UI.

**Comment by djmitche** [comment]
I'd like to have this default to `/subscription`, so that people deploying the service don't need to customize it.  The only reason that it is a configuration value is to support netlify deployments.

https://github.com/taskcluster/taskcluster/blob/911be3c69fd6a50c7feefd733a092c6472886b74/ui/src/App/index.jsx#L80

This *almost* does the right thing.  The problem is, it sees `/subscription` and not the expanded URL.  I'll see if I can fix that up.

**Comment by glandium** [comment]
Is this deployed? Because the task group list still doesn't refresh for me.

**Comment by glandium** [comment]
Oh, there is a difference from before... now I can see error messages in the web console:
```
Firefox can’t establish a connection to the server at wss://community-tc.services.mozilla.com/subscription.
```
and sometimes:
```
The connection to wss://community-tc.services.mozilla.com/subscription was interrupted while the page was loading.
```

I also see 404 errors for requests to https://community-tc.services.mozilla.com/subscription

**Comment by djmitche** [comment]
Yep, cloudops is looking in https://bugzilla.mozilla.org/show_bug.cgi?id=1593564
