### ISSUE TITLE
Can't trigger actions

### ISSUE THREAD

**Issue by glandium** [taskcluster/taskcluster#1840]
- Go to e.g. https://community-tc.services.mozilla.com/tasks/groups/K4JZdi5VQJ2S5pXsBUOApA
- Click the menu thing in the lower right corner
- Pick one of the action items
- Click on the action button in the dialog that opens

This results in the following error:
Schema Validation Failed! Rejecting Schema: https://community-tc.services.mozilla.com/schemas/queue/v1/create-task-request.json# Errors: data should NOT have additional properties: "options"

The corresponding actions.json is https://community-tc.services.mozilla.com/api/queue/v1/task/K4JZdi5VQJ2S5pXsBUOApA/runs/0/artifacts/public/actions.json, and doesn't contain `options`.

An `options` field *is* sent over in the HTTP request, and is apparently added on the client side, containing `authorizedScopes` and it seems it might come from https://github.com/taskcluster/taskcluster/blob/c85e4e4fbc395e4212452a1dfce70afb4451d331/ui/src/views/Tasks/submitTaskAction.js#L57

**Comment by djmitche** [comment]
Looking deeper, it seems that this `task.options` was added in 61b12b184292ec9e62b6c7401ca9a7ea0b066b68 as a way to pass client options to taskcluster-client.  That's a bit odd, but GraphQL is a private API between web-server and the UI, so it doesn't really matter.  It's especially odd because the comment is wrong!  It's OK from a security perspective: the `client` being used here is initialized for each request based on the TC credentials included with that request, so anything the HTTP client could do by passing malicious `options`, they could just as well do by importing taskcluster-client and calling `new Client({...options})`.

A more natural design might be to include an `authorizedScopes` argument to the `createTask` mutation.  But I think the immediate fix is to remove the `options` property from the task before calling `createTask` with it.
