### ISSUE TITLE
[UI] Expiry times only include date.

### ISSUE THREAD

**Issue by tomprince** [taskcluster/taskcluster#2031]
Various place in the UI only display dates, where the underlying value also includes times.

The place I've most noticed this is the client page; I usually use CLI clients with expiry <1h, so the lack of being able to see the current expiry time, and adjust it is impactful. I've also noticed that secrets only show the dates There may be other place in the UI that display dates as well.

**Comment by helfi92** [comment]
SGTM. We could include a time picker.

**Comment by Manish-Giri** [comment]
Hello, I'd like to give this a shot. If anyone could give a brief overview on what needs to be done, that'll be very helpful.

**Comment by helfi92** [comment]
Awesome, thanks @Manish-Giri. Here's what I think should be done:

The change will need to be done in our custom [DatePicker](https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/DatePicker/index.jsx) component. We would need to stop using `KeyboardDatePicker` and instead use [DateTimePicker](https://material-ui-pickers.dev/demo/datetime-picker).

https://github.com/taskcluster/taskcluster/blob/5e6c2b635b916f495873e9b64fd07a69fb090946/ui/src/components/DatePicker/index.jsx#L5

The next thing we'll have to do is make sure the picker fits properly with the light and dark theme of our site. You can test this by navigating to http://localhost:5080/secrets/create and then clicking on the widget to view it. You might need to adjust some colors. I'm hoping there won't be anything to change, but just in case, you'll be able to do that in `theme.js`. We already override a couple of stuff for the current date picker:

https://github.com/taskcluster/taskcluster/blob/5e6c2b635b916f495873e9b64fd07a69fb090946/ui/src/theme.js#L301-L344

**Comment by Manish-Giri** [comment]
@helfi92 Thank You for the detailed explanation! I'm on it.

**Comment by Manish-Giri** [comment]
Hi @helfi92, I'm having some trouble getting the environment up and running, and was hoping you might be able to shed some light.

1. [web-server](https://github.com/taskcluster/taskcluster/tree/master/services/web-server) - Since Taskcluster ui requires the `web-server` service to be running on port 3050 prior to launching the UI, I  followed the instructions [here ](https://github.com/taskcluster/taskcluster/tree/master/services/web-server#running-taskcluster-web-server-locally), and created a `user-config.yml` from the provided template, with ` rootUrl: https://taskcluster.net`. If I execute `yarn start` now, I get this error -

```
ubuntu@ip-172-31-28-75:~/workspace/taskcluster/services/web-server$ yarn start
yarn run v1.19.1
$ cross-env NODE_ENV=development node src/main.js devServer
AssertionError [ERR_ASSERTION]: namespace is required
    at new Client (/home/ubuntu/workspace/taskcluster/libraries/pulse/src/client.js:78:5)
    at setup (/home/ubuntu/workspace/taskcluster/services/web-server/src/main.js:58:16)
    at /home/ubuntu/workspace/taskcluster/libraries/loader/src/index.js:109:33
    at new Promise (<anonymous>)
    at /home/ubuntu/workspace/taskcluster/libraries/loader/src/index.js:107:18
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Promise.all (index 2)
    at async Promise.all (index 1)
error Command failed with exit code 1.
```

I'm assuming this is because the `namespace` field is not optional in the yml file -
```
 pulse:
    namespace:
```
which is confusing because the [docs ](https://github.com/taskcluster/taskcluster/tree/master/services/web-server#pulse)say it's optional - 
> Pulse messages are entirely optional, and most server components do not require them. If you do not configure pulse, the server will act as if no pulse messages are received, which is sufficient for most development work.

If I change the `namespace` field to `namespace: ..` in `user-config.yml`, the next error I get is related to `github login strategy` - 

```
ubuntu@ip-172-31-28-75:~/workspace/taskcluster/services/web-server$ yarn start
yarn run v1.19.1
$ cross-env NODE_ENV=development node src/main.js devServer
Error: Unable to use "github" login strategy without taskcluster clientId and accessToken
    at Github.useStrategy (/home/ubuntu/workspace/taskcluster/services/web-server/src/login/strategies/github.js:114:13)
    at /home/ubuntu/workspace/taskcluster/services/web-server/src/servers/createApp.js:117:14
    at Array.forEach (<anonymous>)
    at module.exports (/home/ubuntu/workspace/taskcluster/services/web-server/src/servers/createApp.js:116:29)
    at setup (/home/ubuntu/workspace/taskcluster/services/web-server/src/main.js:110:9)
    at /home/ubuntu/workspace/taskcluster/libraries/loader/src/index.js:109:33
    at new Promise (<anonymous>)
    at /home/ubuntu/workspace/taskcluster/libraries/loader/src/index.js:107:18
    at async Promise.all (index 0)
    at async Promise.all (index 1)
```

Which is again confusing, because the [docs ](https://github.com/taskcluster/taskcluster/tree/master/services/web-server#taskcluster-credentials) say taskcluster-credentials is not required for most dev work. 

2. [ui](https://github.com/taskcluster/taskcluster/tree/master/ui#taskcluster-ui) - I'm able to start up the ui successfully, but after a few seconds, I get a ` JavaScript heap out of memory` error. Not sure if this is related to `web-server` not being up and running already. 

```
ubuntu@ip-172-31-28-75:~/workspace/taskcluster/ui$ yarn start
yarn run v1.19.1
$ cross-env GENERATE_ENV_JS=1 webpack-dev-server --mode development
ℹ ｢wds｣: Project is running at http://localhost:5080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/ubuntu/workspace/taskcluster/ui
ℹ ｢wds｣: 404s will fallback to /index.html

<--- Last few GCs --->

[3797:0x425b830]    60028 ms: Mark-sweep 503.8 (528.2) -> 503.6 (528.2) MB, 828.9 / 0.0 ms  (average mu = 0.220, current mu = 0.000) last resort GC in old space requested
[3797:0x425b830]    60870 ms: Mark-sweep 503.6 (528.2) -> 503.6 (527.7) MB, 841.7 / 0.1 ms  (average mu = 0.118, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x12f382d]
Security context: 0x314e7e9408a1 <JSObject>
    1: fromStringFast(aka fromStringFast) [0x2d34db6d8a9] [buffer.js:~385] [pc=0x4e3aba2ba1d](this=0x1f1dbc2804a9 <undefined>,0x13bfaed05061 <Very long string[149282]>,0x02d34db75a69 <Object map = 0x20d970665cd1>)
    2: fromString(aka fromString) [0x2d34db6d8e9] [buffer.js:418] [bytecode=0x362350cf1191 offset=117](this=0x1f1dbc2804a9 <undefined>,0x13bfaed05061 <...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x9d8da0 node::Abort() [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
 2: 0x9d9f56 node::OnFatalError(char const*, char const*) [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
 3: 0xb37dbe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
 4: 0xb38139 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
 5: 0xce34f5  [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
 6: 0xcf33bd v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
 7: 0xcc0f86 v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
 8: 0xef9be2 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
 9: 0xb3700b v8::internal::String::Flatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::AllocationType) [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
10: 0xb4b489 v8::String::Utf8Length(v8::Isolate*) const [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
11: 0x9b1d79  [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
12: 0x12f382d  [/home/ubuntu/.nvm/versions/node/v12.13.0/bin/node]
error Command failed with exit code 1.
```

Also, something worth mentioning - I have a windows machine, so I wanted to run this on AWS EC2, as the [docs ](https://github.com/taskcluster/taskcluster/blob/d6a4adddb44f22c6b202773ce334bfdff56de8c5/dev-docs/development-process.md#hacking-on-the-ui) mention that a Linux environment is essential for hacking on the UI. I'm using a t2.micro instance, which has 1GB memory, could the out-of-memory error be due to this?

Thanks!

**Comment by Manish-Giri** [comment]
@helfi92 So, I just switched in `DateTimePicker`, and I fiddled with different date-time combinations in both dark and light themes. Here are the screenshots - https://imgur.com/a/wOaJjEk

If you could take a look to verify that the colors look right, I'll submit a PR. Else I can go in to `theme.js` and override the styles accordingly.

**Comment by Rolikasi** [comment]
Hello @Manish-Giri 
You may follow [this](https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md) development docs to setup your environment
Note that the `https://taskcluster.net` instance is shut down, you need to use either `https://firefox-ci-tc.services.mozilla.com/` or `https://community-tc.services.mozilla.com/`

**Comment by Rolikasi** [comment]
Is it possible to fix that regression?

Before

![before](https://user-images.githubusercontent.com/44370635/69493371-6943d780-0ed8-11ea-86af-ae9fa591ae8f.PNG)


After

![after](https://user-images.githubusercontent.com/44370635/69493376-6c3ec800-0ed8-11ea-8993-3764361a213d.PNG)

**Comment by Rolikasi** [comment]
I think `KeyboardDateTimePicker` is better option here, because it can show the time in a tab and users can use keyboard. @helfi92 what do you think?

**Comment by helfi92** [comment]
> Hello @Manish-Giri
You may follow this development docs to setup your environment
Note that the https://taskcluster.net instance is shut down, you need to use either https://firefox-ci-tc.services.mozilla.com/ or https://community-tc.services.mozilla.com/

Thanks for helping @Rolikasi! We should definitely update that file to say https://community-tc.services.mozilla.com rather than https://taskcluster.net :)

> I think KeyboardDateTimePicker is better option here

Agreed. Also, for the format prop we can probably use `format="yyyy/MM/dd hh:mm a"`

**Comment by Manish-Giri** [comment]
@Rolikasi @tomprince Thank You for your inputs. I'll use `KeyoardDateTimePicker` and test if things are working correctly.

While I'm at it, should I also update the [`web-server` doc](https://github.com/taskcluster/taskcluster/blob/fcb83f7cf149b61ac52367d25eba17f2eaf0b5cd/services/web-server/README.md#running-taskcluster-web-server-locally) to use  https://community-tc.services.mozilla.com instead?

**Comment by Manish-Giri** [comment]
Meanwhile, here's the new set of screenshots with `KeyboardDateTimePicker` - https://imgur.com/a/Ks0H2xO

I tested that keyboard input is working, in the last screenshot.

**Comment by Manish-Giri** [comment]
@Rolikasi @helfi92 Thank You for your inputs! I replaced `DateTimePicker` with `KeyboardDateTimePicker`. Here are the new set of screenshots - https://imgur.com/a/Ks0H2xO

I noticed one potential issue though - the picker won't let me add in a **time** manually, just the **date**. This is weird because I did add the `format` prop to `KeyboardDateTimePicker` like so -

```
        <KeyboardDateTimePicker
            className={classNames(classes.datePicker, className)}
            showTodayButton
            keyboardIcon={<CalendarIcon />}
            rightArrowIcon={<ChevronRightIcon />}
            leftArrowIcon={<ChevronLeftIcon />}
            value={value}
            onChange={onChange}
            format="yyyy/MM/dd hh:mm a"
            {...props}
```
When I inspected the component in the component tree (React browser extension), this is what I see -

![8](https://user-images.githubusercontent.com/11348778/69524998-2fed8500-0f35-11ea-90fe-0d15733edb5b.png)

Since `DatePicker` gets rendered by the `SecretForm` component here - 

https://github.com/taskcluster/taskcluster/blob/5e6c2b635b916f495873e9b64fd07a69fb090946/ui/src/components/SecretForm/index.jsx#L199-L205

And `SecretForm` passes the `format` prop as `format="yyyy/MM/dd`, this overrides the `format` prop I added manually in `DatePicker.jsx`, which is why I can't add in the time manually via keyboard. It works only if I set it using the "calendar" icon beside the picker. 

On the other hand, if I edit the `format` prop  to add in `hh:mm a` in `SecretForm.jsx`, like so - 
```
  <ListItem>
             <DatePicker
               label="Expires"
               value={expires}
               onChange={this.handleExpirationChange}
               format="yyyy/MM/dd hh:mm a"
               maxDate={addYears(new Date(), 1001)}
             /> 

```
it works -

![9](https://user-images.githubusercontent.com/11348778/69527019-6d541180-0f39-11ea-9b24-9a561ec3da9e.png)

![10](https://user-images.githubusercontent.com/11348778/69527029-7349f280-0f39-11ea-9b88-c11b6c3c615a.png)

If it is not desired to change the `SecretForm` component, I tried another way - manually overriding `format` in `DatePicker.jsx` by passing it in **after** `props` has been destructured- 
```

{...props}
format="yyyy/MM/dd hh:mm a"
```

and this way works too.

Please let me know which approach is preferred, and I'll make the changes accordingly.

**Comment by Rolikasi** [comment]
There are 3 components that use DatePicker: `SecretForm`, `ClientForm` and `AuthConsent`.
IMO you can remove `format` prop from these components and add `format="yyyy/MM/dd hh:mm a"` in `KeyboardDateTimePicker` before `{...props}`

**Comment by helfi92** [comment]
Agreed with @Rolikasi. Also, from the screenshots, the minute and hour hands of the clock are not showing:

#### From the screenshot

![Screen Shot 2019-11-25 at 7 58 29 AM](https://user-images.githubusercontent.com/3766511/69542463-82d93380-0f59-11ea-8489-135decc7a070.png)

#### From https://material-ui-pickers.dev/demo/datetime-picker

![Screen Shot 2019-11-25 at 7 58 56 AM](https://user-images.githubusercontent.com/3766511/69542462-82d93380-0f59-11ea-8f0a-eac723c99e88.png)

You'll probably need to override some styles in theme.js.

Aside, I think it would be good if you can open up a pull-request where we could look at the code. We would be in a better measure to help this way :)

**Comment by Manish-Giri** [comment]
@helfi92 Regarding this - 

> Also, from the screenshots, the minute and hour hands of the clock are not showing:

The hour and minute hands are actually there, but it's very faint, so hard to see.

Here, the hour hand is there pointing at 2 -

![Untitled](https://user-images.githubusercontent.com/11348778/69579675-fe120800-0fa0-11ea-9e7a-6cc45996c023.png)

and here at 54, but again very faint -

![Untitled](https://user-images.githubusercontent.com/11348778/69579818-429da380-0fa1-11ea-93aa-76602c4de827.png)

You're correct in that I will have to override styles in theme.js.

I'll open up a PR, probably mark it as Draft at first.

**Comment by helfi92** [comment]
> I'll open up a PR, probably mark it as Draft at first.

Awesome :)

**Comment by Manish-Giri** [comment]
@helfi92 I sent in a PR, including some screenshots of the changes in `theme.js`.
