### ISSUE TITLE
[UI] Task view marks many artifact text files as "LOG"

### ISSUE THREAD

**Issue by glandium** [taskcluster/taskcluster#2132]
1. Go to https://firefox-ci-tc.services.mozilla.com/tasks/LvQcKn0sRbOEOf7NG4AsNA
2. Click on 'Artifacts'
3. Check the list of artifacts. Many have a "LOG" marker, but most of those marked as such are not, in fact, logs.

What's weird, though, is that while they all have in common that they are plain text files, there are also plain text files that _aren't_ marked as "LOG".

**Comment by helfi92** [comment]
This was fixed in https://github.com/taskcluster/taskcluster/pull/2091. It will be deployed on Taskcluster 24.0.0. FirefoxCI is running on 23.0.0 atm. I believe a new deployment will be made either this week or the next one.

![Screen Shot 2019-12-04 at 7 46 25 AM](https://user-images.githubusercontent.com/3766511/70143786-7dbb6900-166a-11ea-9c4d-528d89490408.png)
