### ISSUE TITLE
[UI] information drawer shows null for a split second

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2152]
**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/provisioners/
2. Click on any information icon beside the provisioner name
3. Press the ESC key while looking at the drawer title

**Expected behavior**
The content in the drawer does not change while the drawer is being closed.

**Actual behavior**
The title becomes empty while the drawer is being closed.

**Taskcluster version**
24.0.1

**Comment by MooseJ** [comment]
@helfi92 Took a look at the code for the provisioner component. It looks like this is happening since the onClose function for the Drawer empties out the drawer as soon as it's called and changes a variable tied to a Drawer prop that causes the close animation to play after. So the animation is playing while `drawerProvisioner` is null.

I think this should be fixable by never setting `drawerProvisioner` to `null` when closing a Drawer, and only having it change when a Drawer is opened.

I can pick this up too!

**Comment by helfi92** [comment]
That's a good idea!
