### ISSUE TITLE
[UI] always allow collapsing the drawer

### ISSUE THREAD

**Issue by davehouse** [taskcluster/taskcluster#225]
Could you add an action to collapse the drawer or leave the accordion button when the screen is wide (then I can choose to collapse it)?

As a user, I would like to hide the navigation when I am looking at content. This would provide more space to view content and prevent horizontal scrolling.

Here is a screenshot showing the limited content space (half of the table is displayed, and I must scroll horizontally to see the other half):
![image](https://user-images.githubusercontent.com/5540936/47586104-6e70d480-d91c-11e8-95a4-45ba674568f5.png)

**Comment by iFlameing** [comment]
@helfi92 I would like to work on this issue :)

**Comment by helfi92** [comment]
Great to hear! Go for it.

**Comment by helfi92** [comment]
Here's how I would tackle the issue:

1. Add a "<" icon button on the right hand side of the "Taskcluster" text

![screen shot 2019-02-16 at 7 53 18 am](https://user-images.githubusercontent.com/3766511/52900108-0e01ed80-31c0-11e9-9bc4-08278cf34052.png)

You can import it in the code via:

```
import ChevronLeftIcon from 'mdi-react/ChevronLeftIcon;
```

2. Use an `IconButton` to wrap the icon so that it's clickable

3. Add a tooltip to the button that says "Collapse side panel"

4. When the user closes the menu, there should be a hamburger menu that allows a user to open the panel.

![screen shot 2019-02-16 at 7 57 19 am](https://user-images.githubusercontent.com/3766511/52900151-8a94cc00-31c0-11e9-8015-a64dc4d0fe4e.png)

_Note: We already have that hamburger menu show up by default when the window size is small._

5. On small screens, when the panel is open, there is a hamburger menu that we can remove and replace with the "<" icon however it should be located to the right of "Taskcluster".

<img width="126" alt="screen shot 2019-02-16 at 8 01 15 am" src="https://user-images.githubusercontent.com/3766511/52900205-1149a900-31c1-11e9-9fb6-6b8eb9a3ddbc.png">

**Comment by helfi92** [comment]
Actually, I think there might be an easier approach which is by simply adding a hamburger menu at the left hand side of "Taskcluster" :) No need for the "<" icon.

**Comment by Aditya-Kolla** [comment]
Can I give this a go?

**Comment by iFlameing** [comment]
@Aditya-Kolla I already working on this. You can work on another issue.

**Comment by iFlameing** [comment]
@helfi92 I added hamburger menu but I have doubt in implementing the onClick handler because right now we are hiding the drawer using CSS. Can you give me some starter suggestion on, how I should tackle it?

**Comment by helfi92** [comment]
> I added hamburger menu but I have doubt in implementing the onClick handler because right now we are hiding the drawer using CSS. Can you give me some starter suggestion on, how I should tackle it?

The code uses breakpoints. To have a better understanding of how they work, refer to [Breakpoints](https://material-ui.com/layout/breakpoints/).

Regarding the onClick, you will be calling the [`handleDrawerToggle`](https://github.com/taskcluster/taskcluster/blob/a60f57c3215c46022a3f0d6f59834bb9134359c1/ui/src/components/Dashboard/index.jsx#L199-L201) method to open/close the drawer. It would also make sense to rename `mobileOpen` to `drawerOpen` since we want to be able to close the drawer for both mobile and desktop users.

You just have to port the current mobile functionality to desktop (i.e., larger screens). This is how it currently looks on smaller screens (you can see that by reducing the width of the browser):

<img width="401" alt="screen shot 2019-02-18 at 8 01 01 am" src="https://user-images.githubusercontent.com/3766511/52952751-8e0c8c80-3353-11e9-829c-1e585065c85f.png">

<img width="410" alt="screen shot 2019-02-18 at 8 01 13 am" src="https://user-images.githubusercontent.com/3766511/52952755-91a01380-3353-11e9-9d7a-f67ed5ce5438.png">

The only difference there should be from a user loading the dashboard on a mobile vs desktop view is that the one on mobile will have the drawer closed by default whereas the desktop user will have it open by default.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/2b77a7b9d497767e0561f6f9f57b9ed961cd4190.
