### ISSUE TITLE
96% overhead in community?

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#2878]
We should figure out either how the reporting is missing useful work being done or find where the wasted usage is coming from. Followup work can be either fixing the wastage or helping make it so that reporting is more reliable.

**Comment by ccooper** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1639872

**Comment by ccooper** [comment]
I posit that this is mostly due to some projects having minCapacity > 0: https://github.com/mozilla/community-tc-config/search?q=minCapacity&unscoped_q=minCapacity

Setting minCapacity to zero should be our first step.

Deepspeech is also the worst offender by a country mile, accounting for >$21,000 in overhead against only $60 in real CI costs. I will set their maxCapacity to 2 instead of 96 while I'm in there.

**Comment by ccooper** [comment]
https://github.com/mozilla/community-tc-config/pull/278

**Comment by ccooper** [comment]
We had a lot of instances getting wedged in the Firefox CI cluster, and I'm beginning to suspect that a similar thing is happening in the community cluster.

I'm currently trying to get access to the community workers account in AWS to test my theory. I'll document what I find, and clean it out as necessary.

**Comment by ccooper** [comment]
Well, I did find some, but not as many as I was expecting:
```
(aws-cleanup) Xeppo:aws-cleanup ccooper$ time ./terminate_long_running_instances.py --account community 2>&1 | tee logs/terminate_long_running_instances-community-output-`date +%Y%m%d%H%M%S`.log
eu-central-1: 0 instances found
us-east-1: 2020-05-18 19:05:34+00:00 i-0357aa5d15b156eee proj-bergamot/ci-windows
us-east-1: 1 instance found
us-east-1: Attempting to delete instance i-0357aa5d15b156eee...DONE
us-west-1: 2020-05-04 20:45:30+00:00 i-007325365de19c6be proj-bergamot/ci-windows
us-west-1: 1 instance found
us-west-1: Attempting to delete instance i-007325365de19c6be...DONE
us-west-2: 2020-04-12 00:03:06+00:00 i-0206863ee4934202c proj-bergamot/ci-windows
us-west-2: 2020-02-21 18:54:31+00:00 i-0b47886481552a616 proj-taskcluster/gw-ci-ubuntu-18-04
us-west-2: 2 instances found
us-west-2: Attempting to delete instance i-0206863ee4934202c...DONE
us-west-2: Attempting to delete instance i-0b47886481552a616...DONE

real	0m5.626s
user	0m0.528s
sys	0m0.102s
```

**Comment by ccooper** [comment]
I tracked down a similar, small number (10) of long-running GCP instances, but haven't scripted that process up yet. I'm going to hold off on terminating them in case we want to poke at one for diagnostics.

**Comment by ccooper** [comment]
Tomorrow I want to dig into why we seem to spin up many instances that never claim work, e.g.: https://community-tc.services.mozilla.com/provisioners/proj-relman/worker-types/compute-smaller/workers/?sortBy=First%20Claim&sortDirection=desc

**Comment by ccooper** [comment]
> Tomorrow I want to dig into why we seem to spin up many instances that never claim work, e.g.: https://community-tc.services.mozilla.com/provisioners/proj-relman/worker-types/compute-smaller/workers/?sortBy=First%20Claim&sortDirection=desc

TIL setting minCapacity doesn't prevent a worker from shutting down after idleTimeoutSecs. Worker-manager will see the empty pool and start new workers up to minCapacity. The net effect is that for idle worker pools with a minCapacity set, there will be near-constant number of workers, modulo the cycle time for worker shutdown, restart, and worker-manager noticing the empty pool. That explains all the workers with no claims spawning every 900s (idleTimeoutSecs) in community.

**Comment by ccooper** [comment]
My next step is to do some quick math based on the April reporting numbers to determine how much of the time overhead was attributable to worker pools with a minCapacity > 0. This should give me a new overhead percentage that is hopefully less than 96%, and may give me a new target for investigation as well.

**Comment by ccooper** [comment]
I did some math last night using a project I have full access to, proj-taskcluster/gw-ci-windows2012r2-amd64. 

For April 2020:
* \# tasks: 1,132
* \# hours total: 1,583
* \# hours overhead[1]: 1,498
* \# hours running tasks[1]: 85
* avg time/task for April: 0.07 hours (or 4.2 minutes)
* avg time/task validated from recent tasks: 4.47 minutes
* idleTimeoutSecs: 1 hour (3600 secs)

From the above numbers, the # hours spent actually running tasks looks legit based on comparisons with more recent task timings. The important number to call out is the idleTimeoutSecs. If we assume a pathological spacing of tasks so that we hit the full idleTimeout on every task, that would account for 1,132 hours out of the 1,498 hours of overhead, leaving us with 366 hours to account for. While still not great, that would put us in line with the Firefox CI cluster with about 25% overhead to worry about.

1. From @trink's [workerType Costs Community report](https://datastudio.google.com/u/0/reporting/1NUkJMd4wU9kV8ZxlTmo7lzSwLr8BAz3R/page/0Aq1)

**Comment by ccooper** [comment]
https://github.com/mozilla/community-tc-config/issues/282

**Comment by ccooper** [comment]
Looking at the workerType cost breakdown over the past week, proj-bergamot had the most hours (688) and it was *all* overhead. Over the last three days, it had zero tasks which translated to zero overhead. The minCapacity change is having the desired effect. 

So this is getting better in AWS, although the idleTimeoutSecs change needs to be apply to reduce it further. It will take a few weeks to bear out completely.

On to GCP.

**Comment by trink** [comment]
@ccooper GCP overhead is being corrected https://bugzilla.mozilla.org/show_bug.cgi?id=1642342

**Comment by ccooper** [comment]
> On to GCP.

I've added a [script to cleanup errant GCP instances](https://github.com/ccooper/cloud-cleanup/blob/master/gcp/delete_old_resources_gcp.bash). It gets the job done, but it's synchronous and slow and not particularly bulletproof. I'm trying to get a version working in python using the SDK similar to [what I have for AWS](https://github.com/ccooper/cloud-cleanup/blob/master/aws/terminate_long_running_instances.py), but it doesn't seem to support the same functionality as the CLI.

**Comment by ccooper** [comment]
I think we understand overhead to a level where I can call this done. It's not 96% any more at least.
