### ISSUE TITLE
figure out next steps for provisioning improvements

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#2879]
Some starter ideas:
* bring back scaling ratio (aka only provisioning N% of pending)
* intentional under-provisioning in some other fashion
* track historical task runtimes per pool and/or per label and use it to estimate total time of pending tasks in a queue
* estimating load at a given time of day based on historical load a that time on that day of the week, etc (forecasting in general)

**Comment by imbstack** [comment]
@catlee has a `scalingRatio` patch mostly done in https://github.com/taskcluster/taskcluster/compare/master...catlee:slow_provisioning

**Comment by tomprince** [comment]
As :jmaher points out [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1641675#c1) we have two instance types defined for the `gecko-t/t-linux-metal` pool:
- r5.metal with capacity 32, at ~$0.18/capacity
- m5.metal with capacity 15, at ~$0.30/capacity

So, if there was some way to prefer the r5.metal there would be a reasonable savings. My understanding is that wcosta ran into issues with the total available capacity of the metal instances, so we wanted to be able to spread the load over multiple instance types, but being able to use the one if available (or even just with a higher portion of the instances provisioned) would be good.

**Comment by tomprince** [comment]
Another thought that occurs to me is if there is any potential savings in preferring one region over another, for better locality of data. This might have impact on data transfer costs, or speed of downloads/uploads.

On the other hand I'm not sure how big either of those effects are, to offset the engineering effort required.

**Comment by djmitche** [comment]
aws-provisioner had a `utility` factor for each configuration which it used to evaluate differences in price.  For example if m5.metal is twice as efficient for our purposes as r5.metal, then the utility factors would be 2 and 1, respectively, so the utility-adjusted prices would be $0.36 and $0.30.  We would need to figure out whether utility included or excluded capacity.

John also talked about looking at the success rate of provisioning each configuration and biasing toward those that were more successful.  The idea was that if e.g., us-east-1 is on fire, then even if it's cheapest there's no point trying to request instances there.  This is much trickier to implement since it feeds back on itself: if the provider doesn't *try* to provision in an en-fuego region, how will it know when the fire is extinguished?

**Comment by djmitche** [comment]
From @imbstack 
> if you basically write a little node script that can take a list of region x zone x machineType x whatever as input
> and outputs the sku costs for each one
> one implementation for gcp, one for aws, bonus points for azure

**Comment by djmitche** [comment]
I made a script to do this.  Basically it gets the price for each launchConfig, and then averages them since we select randomly.

https://github.com/djmitche/tc-cloud-prices

Downside is, I don't have access to billing information for GCP, so I can't determine GCP prices.

Here's the current output (with N/A for anything we don't have a price for)

[output.txt](https://github.com/taskcluster/taskcluster/files/4737965/output.txt)

**Comment by tomprince** [comment]
#2879 tracks some aspect of this

**Comment by djmitche** [comment]
This was a vague "figure out" issue that's not seen action in a while..
