### ISSUE TITLE
Support encrypted columns in postgres

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#2962]
This is required to support a token for reregistration. @djmitche and @helfi92  can help fill out the other bits of this about what we actually need to do.

Blocks #2893

**Comment by djmitche** [comment]
High-level concerns:
 * We'll need to support migration to/from tc-lib-entities' encryption implementation
 * The keys should remain in the service pod, not be sent to the postgres server - as with Azure, this means that a compromise of the DB server alone cannot reveal these secrets
   * This could make migrations difficult
 * Should we implement signing at the same time, or can the two be separated?
 * Cloudops was unimpressed that we can't rotate encryption and signing keys.  The new implementation should allow rotation.

@helfi92 what comes to mind for you?

**Comment by djmitche** [comment]
[This](https://www.postgresql.org/docs/10/encryption-options.html) is a super-concise summary of our options.  Pg docs are really top-notch.

**Comment by djmitche** [comment]
The encrypted columns we need to plan for are:

```
auth - Client:    accessToken: Entity.types.EncryptedText,
hooks - Hook:    triggerToken: Entity.types.EncryptedText,
hooks - Hook:    nextTaskId: Entity.types.EncryptedText,
secrets - Secret:    secret: Entity.types.EncryptedJSON,
web-server - AccessToken:    accessToken: Entity.types.EncryptedText,
web-server - GithubAccessToken:    accessToken: Entity.types.EncryptedText,
web-server - SessionStorage:    sessionId: Entity.types.EncryptedText,
```

Signed tables:
```
auth - Client
hooks - Hook
hooks - Queues
hooks - LastFire
secrets - Secret
web-server - AccessToken
web-server - AuthorizationCode
web-server - GithubAccessToken
web-server - SessionStorage
```

(AuthorizationCode should probably be encrypted too..)

**Comment by djmitche** [comment]
Some background on the concern around keeping the key material on the service pod (I'm having second thoughts about this requirement!)

In Azure, we do our crypto (encryption and signing) client-side, with key material and cleartext data never communicated to Azure.  Crypto is done with aes-256-cbc on individual columns, and signing with a sha512 hmac over the whole row.

Postgres has some signing and crypto support in the handy "pgcrypto" module  https://blog.andreiavram.ro/encrypt-postgresql-column/but that only encrypts the data at rest on the Pg server, and not in transit.  It's also not secure against a severe[*] compromise of the Pg server, as the keys are sent to that server and present in its memory at least temporarily.  That said, encryption at rest means that the information is secure in backups, in snapshots we might take for dev or analysis purposes, and so on, as the key material is not present in those situations.

My second thoughts are mostly due to concerns about migration scripts, which run entirely on the server side.  If those need to decrypt a value in one format and re-encrypt it in another, or sign changed rows, then we will need to make a way to run migration scripts client-side if we are not sending key material to the server.

**Comment by djmitche** [comment]
Brian and I talked this through, and I think we have a high-level plan, but there may be devils in the details.

We'll continue to do all of the crypto client-side.

We won't consider signing right now.

We'll invent a container format for encrypted columns that has a key identifier, a format identifier, and the ciphertext.  Format 0 will be identical to that used by azure-entities (with `__buf0_<name>` and all that jazz).  The key identifiers will let us rotate keys.

Migration scripts then always handle encrypted columns as an opaque blob, with the exception of migration from azure-entities format.  To do so, the scripts will extract the `__buf0_<name>` jazz and wrap it in a container with key identifier 0 and format identifier 0.

We'll need to bake in some support for scanning tables and upgrading everything to the latest key identifier, perhaps in daily crontasks, to support key rotation.

I'll work a bit on the particulars and then Brian and I will do a bit of pairing on this.

**Comment by djmitche** [comment]
I wrote up a README with some notes in https://github.com/djmitche/taskcluster/pull/new/issue2962.  I don't see any devils yet.

A few minor worries:
 * With this plan, we would be unable to encrypt a previously-un-encrypted column during a migration.  That's probably OK.
 * The configuration format for the key material might be a bit complicated, as we really should specify the algorithm for each key.  But at least it will be the same across the services.
 * Downgrades won't work after the crypto container format upgrade crontask runs.  We might want to consider making such tasks manual runs, instead of crontasks, if k8s supports such a thing.
