### ISSUE TITLE
Calls to get_workers on firefox-ci are really slow

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3032]
Reported by @sciurus on slack:

```
   total_minutes    |  average_time_ms  | calls  |                             query                             
--------------------+-------------------+--------+---------------------------------------------------------------
   7.48474414346667 |  6325.13589588733 |     71 | select * from "get_workers"($1,$2,$3,$4,$5,$6)
   3.00127360881668 |  0.61625264030567 | 292212 | select * from "azure_queue_get"($1,$2,$3)
   1.07801060408333 |  1.15940052063168 |  55788 | select * from "queue_tasks_entities_load"($1,$2)
  0.568329448783334 |  144.490537826271 |    236 | select * from "queue_worker_entities_scan"($1,$2,$3,$4,$5)
      0.17861192615 |  3.40862454484733 |   3144 | select * from "queue_artifacts_entities_scan"($1,$2,$3,$4,$5)
  0.123711863366666 | 0.354255323915429 |  20953 | select * from "queue_artifacts_entities_load"($1,$2)
 0.0543825321166666 |  4.64146789046941 |    703 | select * from "queue_tasks_entities_scan"($1,$2,$3,$4,$5)
 0.0465551093666667 | 0.219358140568557 |  12734 | select * from "queue_worker_entities_load"($1,$2)
 0.0436504890999999 | 0.527073726303077 |   4969 | select * from "queue_worker_entities_modify"($1,$2,$3,$4,$5)
       0.0429933757 |  1.02813971383021 |   2509 | select * from "indexed_tasks_entities_scan"($1,$2,$3,$4,$5)
```

generating temp files:

```
temp_blks_written | average_temp_blks_written | temp_blks_read | average_temp_blks_read | calls |                           query                            
-------------------+---------------------------+----------------+------------------------+-------+------------------------------------------------------------
          20193269 |                    126207 |       18002237 |                 112513 |   160 | select * from "get_workers"($1,$2,$3,$4,$5,$6)
```

the query they replaced (at least i think that's what this is) generated some too, but less on average

```
 temp_blks_written | average_temp_blks_written | temp_blks_read | average_temp_blks_read |  calls   |                           query                            
-------------------+---------------------------+----------------+------------------------+----------+------------------------------------------------------------
       12857630591 |                       813 |    12464574081 |                    789 | 15797803 | select * from "wmworkers_entities_scan"($1,$2,$3,$4,$5)
```

**Comment by djmitche** [comment]
We learned some things!

A basic `select * from workers` takes about 15s.  Explaining it shows about 335k rows with an average width of 886 bytes.  That's about 10x larger than when we measured [last week](https://bugzilla.mozilla.org/show_bug.cgi?id=1643670#c2).  Most of that width is `provider_data`.  We were able to reproduce this performance on a table of similar size in a dev environment.

The majority of those rows are stopped workers.

```
taskcluster=> select count(*), state from workers group by state;
 count  |   state   
--------+-----------
    382 | requested
   3155 | running
 322730 | stopped
      1 | stopping
(4 rows)
```

which led us to dig into expiration.  [We set expiration for workers to 1 week from the last time they were seen](https://github.com/taskcluster/taskcluster/blob/209999337c773777ff1f5e66abfd68823523b0e5/services/worker-manager/src/providers/azure.js#L725-L733) so we'd expect the table to hold about one week's worth of workers.

One reason for the change in number of workers may be [configuring workers to shut down immediately on idle](https://bugzilla.mozilla.org/show_bug.cgi?id=1641624).  A 10x jump in total number of instances is higher than any of us would have guessed, but not impossible.

Some analysis of the `expires` timestamps in the production DB shows that (please correct me if I'm remembering incorrectly) about 35000 are more than 8 days old (and thus should have been deleted in the most recent expiration run, which was less than 24h ago), and about 15000 are more than 9 days old.  Both of those numbers are higher than the number of running workers, so it can't be that they're all still running and thus not expired.  So, something is up there - #3034.

Back to get_workers being so slow!  Remember, the yak we were shaving when this all started?  The function is called three ways:
1. in `src/api.js` to answer `listWorkersForWorkerPool` and `listWorkersForWorkerGroup`
1. in `src/worker-scanner.js` to get workers to scan
1. in `src/provisioner.js` to count current running and requested capacity

At a design level, we talked about "leaking" business logic into the DB.  I propose that it's a good idea to leak that logic when it makes sense for performance.  Our DB functions shouldn't be too generic, but should do the things we need them to do.

The calls from the API do not need provider_data, so let's write a new function that only returns what the API requires.  #3035.

The call from `worker-scanner.js` only needs non-stopped workers, but does need provider_data.  So let's write a function that returns that, and add an index on `state` so that the DB can find those rows quickly.  #3036.

The call from `provisioner.js` is just summing the capacity of running and requested workers.  That, too, can be done quickly by the DB.  Also #3036.
