### ISSUE TITLE
New UI: Success/failure colour in favicon is too small

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#306]
Trying to notice the status of a TC build job from the icon is much harder now with the new UI's icon.

Could this be made bigger and with [more accessible colours](https://en.wikipedia.org/wiki/Color_blindness#Deuteranopia)?

<img width="277" alt="screen shot 2019-02-25 at 3 21 36 pm" src="https://user-images.githubusercontent.com/1370580/53366333-52ecf900-3911-11e9-976e-ef23e34d1b4c.png">

**Comment by projectyang** [comment]
@helfi92 

Since I helped implement the first version of the icon, more than happy to take on redesigning it for a better UI experience.

In terms of accessibility, maybe we can introduce difference shapes (circle, triangle, square) / and or textures to help differentiate? Let me know your thoughts.

**Comment by helfi92** [comment]
Hey @projectyang :)

That's awesome, thanks for offering your help. You can try experimenting with different designs (e.g., vertically stretching the status dot, adding a thick border around the "T" with the status color) and see what works best. Looking forward to seeing what you come up with!

**Comment by projectyang** [comment]
![screen shot 2019-03-04 at 8 49 22 pm](https://user-images.githubusercontent.com/13473834/53775105-36c3fb80-3ebf-11e9-922d-483c46e005d4.png)
![image](https://user-images.githubusercontent.com/13473834/53775513-df268f80-3ec0-11e9-8007-a02b408e0015.png)
![image](https://user-images.githubusercontent.com/13473834/53775606-388ebe80-3ec1-11e9-8e47-200c50ab7749.png)
![image](https://user-images.githubusercontent.com/13473834/53775706-8e636680-3ec1-11e9-8338-b4332feea8a1.png)
![image](https://user-images.githubusercontent.com/13473834/53775710-94594780-3ec1-11e9-8012-8b449dd0cab1.png)
![image](https://user-images.githubusercontent.com/13473834/53775719-9ae7bf00-3ec1-11e9-99e5-6dab0f4853ca.png)

Hey, here's my take on a revised version with an increased size and different shapes. (First to admit, I'm not a very good designer...).

@jonalmeida Does this help improve visibility?

**Comment by jonalmeida** [comment]
Hello @projectyang, sorry for the slow reply!

Unfortunately, it's still a bit hard for me to distinguish the difference between the light themed first and third status icons, and the second and third dark themed icons.

**Comment by projectyang** [comment]
Hi @jonalmeida, sorry for the wait on your feedback. I've been trying to come up with other approaches for a status icon that could potentially work for accessibility but wasn't very successful.

Going back to my previous iteration, I've taken your feedback and slightly emphasized the third status (rectangle) a bit more since it seemed to be the common issue between light/dark themes. 

Let me know if this makes it a bit easier to distinguish.

![screen shot 2019-03-04 at 8 49 22 pm](https://user-images.githubusercontent.com/13473834/53775105-36c3fb80-3ebf-11e9-922d-483c46e005d4.png)
![image](https://user-images.githubusercontent.com/13473834/53775513-df268f80-3ec0-11e9-8007-a02b408e0015.png)
![Screen Shot 2019-04-02 at 2 28 36 PM](https://user-images.githubusercontent.com/13473834/55426833-b9d68100-5553-11e9-9c90-1ecf69c8c6e8.png)

![image](https://user-images.githubusercontent.com/13473834/53775706-8e636680-3ec1-11e9-8338-b4332feea8a1.png)
![image](https://user-images.githubusercontent.com/13473834/53775710-94594780-3ec1-11e9-8012-8b449dd0cab1.png)
![Screen Shot 2019-04-02 at 2 28 51 PM](https://user-images.githubusercontent.com/13473834/55426826-b642fa00-5553-11e9-8b84-6bf2e81d8651.png)

Also, I wouldn't mind if someone else wanted to take a stab at this? 

The logo design should be held to a high standard, and I'm not satisfied with what I've produced so far. I'm sure someone who has good design skills can come up with something better.

**Comment by jonalmeida** [comment]
Hey @projectyang , thanks for taking a look at this issue! Thinking about this more, having the shapes alone should be enough to rely on.

I think I like the first suggestion more for the square shapes rather than a rectangle. 😉 Maybe just a tad bit bigger and it should be perfect?

**Comment by projectyang** [comment]
How's this looking @jonalmeida?

![screen shot 2019-03-04 at 8 49 22 pm](https://user-images.githubusercontent.com/13473834/53775105-36c3fb80-3ebf-11e9-922d-483c46e005d4.png)
![image](https://user-images.githubusercontent.com/13473834/53775513-df268f80-3ec0-11e9-8007-a02b408e0015.png)
![Screen Shot 2019-04-11 at 4 47 51 PM](https://user-images.githubusercontent.com/13473834/55992063-a7f28d80-5c79-11e9-8c51-dac17e7eae66.png)


![image](https://user-images.githubusercontent.com/13473834/53775706-8e636680-3ec1-11e9-8338-b4332feea8a1.png)
![image](https://user-images.githubusercontent.com/13473834/53775710-94594780-3ec1-11e9-8012-8b449dd0cab1.png)
![Screen Shot 2019-04-11 at 4 48 11 PM](https://user-images.githubusercontent.com/13473834/55992078-af199b80-5c79-11e9-96dc-48290bf11342.png)


Also, here's an alternate (rough) iteration using the icons you suggested. Let me know your thoughts.


![Screen Shot 2019-04-11 at 5 16 17 PM](https://user-images.githubusercontent.com/13473834/55993667-b0e55e00-5c7d-11e9-88be-d24c9a60d811.png)
![Screen Shot 2019-04-11 at 5 15 39 PM](https://user-images.githubusercontent.com/13473834/55993668-b2af2180-5c7d-11e9-9939-bb11c4404e01.png)
![Screen Shot 2019-04-11 at 5 16 45 PM](https://user-images.githubusercontent.com/13473834/55993660-af1b9a80-5c7d-11e9-84a9-494911b6a314.png)


![Screen Shot 2019-04-11 at 5 16 12 PM](https://user-images.githubusercontent.com/13473834/55993692-bfcc1080-5c7d-11e9-8e70-8e4b0dc06c44.png)
![Screen Shot 2019-04-11 at 5 15 44 PM](https://user-images.githubusercontent.com/13473834/55993694-c0fd3d80-5c7d-11e9-95de-6dcf93d6d390.png)
![Screen Shot 2019-04-11 at 5 16 42 PM](https://user-images.githubusercontent.com/13473834/55993688-be9ae380-5c7d-11e9-96f4-8085fbb37c60.png)

**Comment by jonalmeida** [comment]
@projectyang really liking the last set. :)

**Comment by projectyang** [comment]
Awesome, I've cleaned it up a bit and opened up a WIP pull request with images. Let me know if you have any more feedback on it.
