### ISSUE TITLE
Figure out how much time the DB upgrade will take on July 11

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3136]
Blocker: https://bugzilla.mozilla.org/show_bug.cgi?id=1648609 

Notes by DB version:
 * 0013 (add worker capacity) - fast
 * 0014 (add worker.secrets) - fast
 * 0015 (add sha512) - fast
 * 0016 (add uuid_to_slugid, slugid_to_uuid) - fast
 * 0017 (denylisted_addresses) - fast
 * 0018 (queue_artifacts)
   * create table - 42m
   * create primary key - 24m
   * set not null - 4m (?!)
 * 0019 (tasks)
   * create table - 4h 20m
   * add primary key - 7m
   * add task_group index - 4m
   * add task_group index for unresolved - 3m
   * set not null - 3m
 * 0020 (task groups) - fast
 * 0021 (task dependencies)
   * create table - 8m
   * not null - fast
   * primary key - 4m
   * task_dependencies_dependent_task_id_idx - fast
 * 0022 (indexes)
   * indexed_tasks
     * create table - 1m
     * add primary key - 2m
   * index_namespaces
     * create table - 8s
     * add primary key - 30s
     * sha512_index_namespaces_idx - 15s
     * sha512_indexed_tasks_idx - 1m

Grand total, then, is about 6h.

As a bonus, we use a lot less space:

![image](https://user-images.githubusercontent.com/28673/86922892-48449580-c0fb-11ea-83b0-f1c0affecfa4.png)

Downgrade times:
 * 0022 -> 0021 - 20m
 * 0021 -> 0020 - 50m
 * 0020 -> 0019 - fast
 * 0019 -> 0018 - 3h 10m
 * 0018 -> 0017
   * insert into - 10h
   * add primary key - 34m

**Comment by helfi92** [comment]
Once we have a better idea around timing we could update the migration plan to have approximate timing included.

**Comment by djmitche** [comment]
I've finished the import, and I took a DB backup afterward so hopefully restoring to that version shouldn't be too awful.

**Comment by helfi92** [comment]
Did you have the chance to run the db upgrade on both PRs that will land on Friday?

**Comment by djmitche** [comment]
I need to gather the PRs into a single branch, and I also want to instrument the migrations a little so that I can see how long each phase takes (for example, `insert .. select` vs. the subsequent `alter table .. primary key`).  That's my plan for today, although I expect it will take longer than my workday.

**Comment by djmitche** [comment]
Shortcut to avoid the stackdriver UI:

```shell
gcloud logging read 'textPayload:"user=dustindev LOG:"
resource.labels.database_id="taskcluster-dev:dustindev"' --freshness 6h --format json | jq -r '.[] | .textPayload' | tac
```

Note that the `tac` is required because the command hangs with `--order asc`.  Go stackdriver!

**Comment by djmitche** [comment]
For the tasks migration:
```
2020-07-07T18:24:14.605146978Z [76999]: [3-1] db=dustindev,user=dustindev LOG:  start tasks create table .. as select
2020-07-07T22:53:13.895621804Z [76999]: [6-1] db=dustindev,user=dustindev LOG:  start tasks add primary key
2020-07-07T23:00:58.493087495Z [76999]: [21-1] db=dustindev,user=dustindev LOG:  start tasks add tasks_task_group_id_idx
2020-07-07T23:04:45.743835069Z [76999]: [30-1] db=dustindev,user=dustindev LOG:  start tasks add tasks_task_group_id_unresolved_idx
2020-07-07T23:08:03.669185738Z [76999]: [39-1] db=dustindev,user=dustindev LOG:  start tasks set not null
2020-07-07T23:11:22.060147192Z [76999]: [42-1] db=dustindev,user=dustindev LOG:  start tasks set perms
```

**Comment by djmitche** [comment]
Index import ran in under 10 minutes, but...

```
AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped

  {
    access_token_table_entities: {
...
    },
    workers: {
+     '........pg.dropped.13........': '-',
      capacity: 'integer not null',
...
      worker_pool_id: 'text not null'
    }
  }
    at Function._checkTableColumns (/home/dustin/p/taskcluster/libraries/postgres/src/Database.js:369:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Function.upgrade (/home/dustin/p/taskcluster/libraries/postgres/src/Database.js:173:9)
    at async exports.upgrade (/home/dustin/p/taskcluster/db/src/upgrade.js:5:3)
    at async dbUpgrade (/home/dustin/p/taskcluster/infrastructure/tooling/src/dev/index.js:79:3) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: [Object],
  expected: [Object],
  operator: 'deepStrictEqual'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
WAT

**Comment by helfi92** [comment]
??

How did a `'........pg.dropped.13........': '-',` get introduced?

**Comment by djmitche** [comment]
```
dustindev=>           select
            attname,
            pg_catalog.format_type(a.atttypid, a.atttypmod) as type,
            a.attnotnull as notnull
          from
            pg_catalog.pg_attribute a
          where
            -- attnum's < 0 are internal
            a.attrelid=56443 and a.attnum > 0
;
            attname            |           type           | notnull 
-------------------------------+--------------------------+---------
 worker_pool_id                | text                     | t
 worker_group                  | text                     | t
 worker_id                     | text                     | t
 provider_id                   | text                     | t
 created                       | timestamp with time zone | t
 expires                       | timestamp with time zone | t
 state                         | text                     | t
 provider_data                 | jsonb                    | t
 capacity                      | integer                  | t
 last_modified                 | timestamp with time zone | t
 last_checked                  | timestamp with time zone | t
 etag                          | uuid                     | t
 ........pg.dropped.13........ | -                        | f
 secret                        | jsonb                    | f
(14 rows)
```
it looks like this is an implementation detail of postgres.  I can't find docs about this, but I did find a [mailing-list thread](https://www.postgresql.org/message-id/flat/92869e661001070822n570ecb14kbf5e602fa97c0963%40mail.gmail.com).  Apparently there's an attisdropped field we can be filtering on.

```
dustindev=>           select
            attname,
            pg_catalog.format_type(a.atttypid, a.atttypmod) as type,
            a.attnotnull as notnull
          from
            pg_catalog.pg_attribute a
          where
            -- attnum's < 0 are internal
            a.attrelid=56443 and a.attnum > 0 and not a.attisdropped;
    attname     |           type           | notnull 
----------------+--------------------------+---------
 worker_pool_id | text                     | t
 worker_group   | text                     | t
 worker_id      | text                     | t
 provider_id    | text                     | t
 created        | timestamp with time zone | t
 expires        | timestamp with time zone | t
 state          | text                     | t
 provider_data  | jsonb                    | t
 capacity       | integer                  | t
 last_modified  | timestamp with time zone | t
 last_checked   | timestamp with time zone | t
 etag           | uuid                     | t
 secret         | jsonb                    | f
(13 rows)
```
Migration 22 doesn't touch the workers table, so I was confused why this only showed up after running migration 22, but I remembered that we only verify that the tables match `db/tables.yml` when the DB is at the latest version.  So this might have occurred quite a while ago, and even been broken in my DB before I started work on this issue, since none of the migrations I've been testing touch this table.

**Comment by djmitche** [comment]
Fix in #3177.

**Comment by djmitche** [comment]
OK, updated times in the issue description.

It seems that the `tasks` and `task_artifacts` migrations are the slow ones, while the index migration is super-fast.  The slow migrations share a few things:
 * big JSON blobs
 * they use sub-selects

I'll experiment and see if I can't get those to run a little faster.

**Comment by helfi92** [comment]
Sounds good. Thanks Dustin! I am amazed at how much space we were able to free up.

**Comment by djmitche** [comment]
It looks like the artifacts migration might be as good as it gets -- the explain for that select is basically "scan the table", so the sub-select is being optimized away correctly:
```
dustindev=> explain analyze    select                                                   
      artifacts_entities.task_id as task_id,
      (value ->> 'runId')::integer as run_id,
      (value ->> 'name')::text as name,
      (value ->> 'storageType')::text as storage_type,
      (value ->> 'contentType')::text as content_type,
      entity_buf_decode(value, 'details')::jsonb as details,
      (value ->> 'present')::boolean as present,
      (value ->> 'expires')::timestamptz as expires,
      etag
    from (
      select
        *,
        uuid_to_slugid(value ->> 'taskId')::text as task_id
      from queue_artifacts_entities
    ) as artifacts_entities;
                                                                    QUERY PLAN                                                                    
--------------------------------------------------------------------------------------------------------------------------------------------------
 Seq Scan on queue_artifacts_entities  (cost=0.00..146292571.96 rows=229712736 width=189) (actual time=0.086..1792015.859 rows=229839323 loops=1)
 Planning Time: 0.069 ms
 Execution Time: 1807566.554 ms
```

I bet `entity_buf_decode` is not fast, but there's nothing we can do about that.

**Comment by djmitche** [comment]
The query plan for the tasks table is
```
                                                                                                              QUERY PLAN                                                                                                              
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Left Join  (cost=975.98..61682384.10 rows=25591284 width=472)
   Hash Cond: ((queue_tasks_entities.partition_key = queue_task_group_active_sets_entities.row_key) AND (uuid_to_slugid((queue_tasks_entities.value ->> 'taskGroupId'::text)) = queue_task_group_active_sets_entities.partition_key))
   ->  Seq Scan on queue_tasks_entities  (cost=0.00..572620.84 rows=25591284 width=57)
   ->  Hash  (cost=758.19..758.19 rows=14519 width=46)
         ->  Seq Scan on queue_task_group_active_sets_entities  (cost=0.00..758.19 rows=14519 width=46)
```
it makes sense that's more complex, as we are actually doing a join.  I think it's correctly using the (partition_key, row_key) index on `queue_task_group_active_sets_entities` while scanning `queue_tasks_entities`, since the where condition values for the latter require function evaluation.

I bet that uuid_to_slugid is super-slow.  I can't tell from the explain whether postgres is executing it only once per row, like I want it to.  I'll try doing two passes here -- one to create the tasks table, and one to update the ever_resolved column based on the join.

Big picture, there's nothing obvious in the queries here that can be optimized, so let's count on 6h for the migration, with an option to be pleasantly surprised.

**Comment by djmitche** [comment]
I tried breaking up the tasks join.  Just the `create table .. as select` portion took 3h 25m, and that was just under `explain analyze` so no time spent on IO to actually write the new table.  I think

```sql
update tasks 
set ever_resolved = true
from queue_task_group_active_sets_entities
where tasks.task_id = queue_task_group_active_sets_entities.row_key;
update tasks
set ever_resolved = false
where ever_resolved is null;
```
would be the approach to set the ever_resolved column after the fact, and an explain on that shows almost the same as in the previous comment, so I don't expect it would be especially speedier.  Sadly I don't have a table to actually join it to, so I can't get the actual timing.

The thing I want to try is to leave the `tasks_entities.task_group_id = active_tasks.task_group_id` condition off of the `on` clause for the join.  It's redundant anyway, since each task_id has a unique task_group.  I had included it because the task_group_active_sets has primary key (task_group_id, task_id), so the task group is needed to use the index -- but as it turns out the execution plan just scans that table (probably because it's small and all of its data is required) so this doesn't help.  Including the condition just means that it calls `uuid_to_slugid` for each row to check an equality condition that will always be true.

**Comment by djmitche** [comment]
> The thing I want to try is to leave the tasks_entities.task_group_id = active_tasks.task_group_id condition off of the on clause for the join. 

This took 4h 10m, within the noise floor, so I won't land that change.

**Comment by djmitche** [comment]
I can't figure out why the 0018 -> 0017 (queue_artifacts) downgrade is taking so long.  It's a pretty standard downgrade, and the task downgrade went very quickly.  I was concerned it had to do with running slugid_to_uuid, but some testing 

```
CREATE OR REPLACE FUNCTION perf_test_q1()
    RETURNS VOID AS
$BODY$
DECLARE
    i bigint;
BEGIN
    FOR i IN 1..1000000 LOOP
        perform * FROM slugid_to_uuid('Yeaz1hdaThyPIlEPCGVCkA');                              
    END LOOP;
END;
$BODY$
LANGUAGE plpgsql VOLATILE;
```

shows that to run in about 1.5µs, so for 230 million rows that accounts for about 5 minutes -- a tiny fraction of the 6 hours it's taken so far (and it's still on the `insert into .. select` query).

A similar test shows that the whole `entity_buf_encode(..) as value` expression takes about 12µs per iteration, so about 45 minutes.  That's with a static `details`, so maybe longer to serialize the JSONB in `details::text`, but that can't add much.

Looking at the perf graphs during this time, I see a sustained 11 reads/sec and a spikier ~75 writes/sec for the duration of this query.  Right in the same graph I see higher values for both of those, so this isn't a limit of the instance.  CPU utilization is hovering at about 16%, over a baseline of 5%.   This is an 8-cpu instance, so one pegged CPU is 12.5%.  So it looks like we're CPU-bound here.

The full `select` portion of the `insert into .. select ..` takes 130µs per iteration over 200k rows, which would be about 8 hours for 230 million rows.  Dropping the `entity_buf_encode(..., 'details', details::text)` portion of that saves about 10µs.  Dropping `slugid_to_uuid` saves about 2µs (roughly matching the observation above).  Dropping `encode_composite_key` seems to save 40µs -- that's about 2.5h for 230 million rows!  That sort of makes sense, since it calls `encode_string_key` twice, and that function does some crazy looping over each character in the string.  I think that my "cheating" in `0019-downgrade.sql`, using `task_id` instead of `encode_string_key(task_id`), might have saved quite a bit of time.  I think we can do something similar in this downgrade script.

**Comment by djmitche** [comment]
Even with that change:

```
9 Jul 02:52:15 - downgrading database to version 18
9 Jul 02:52:16 - ..running downgrade script
9 Jul 13:27:35 - ..redefining methods
9 Jul 13:27:35 -    using queue_artifacts_entities_create from db version 2
9 Jul 13:27:35 -    using queue_artifacts_entities_load from db version 2
9 Jul 13:27:36 -    using queue_artifacts_entities_modify from db version 2
9 Jul 13:27:36 -    using queue_artifacts_entities_remove from db version 2
9 Jul 13:27:36 -    using queue_artifacts_entities_scan from db version 7
9 Jul 13:27:36 - ..updating version
9 Jul 13:27:36 - ..committing transaction
9 Jul 13:27:37 - downgrade to version 17 successful
```

and, looking at the timing from the logs, that was 10 hours for the insert followed by about 34m for the primary key.

**Comment by djmitche** [comment]
I don't think there's more action here..
