### ISSUE TITLE
Support one-off maintenance jobs running in k8s

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3139]
For encryption, we have an outline of a process for automatically re-keying tables, but no implementation of it.  Right now, if a deployer adds a new encryption key for a service, the service will dutifully use it for new and updated columns, but existing columns will remain as they are until they are deleted or updated.

The only encrypted column right now is the worker secret, but soon there will be more.  Let's invent a convenient way to either work this into an existing expiration crontask or create a purpose-specific crontask.

**Comment by djmitche** [comment]
Maybe we should define some one-off jobs to do this sort of online DB maintenance.

We could use it for online DB migrations, too.  That could have three parts:
 * A "regular" DB migration from `yarn db:upgrade` that creates new tables, sets up functions, etc.
 * An online job for the migration that must complete before the next "regular" DB migration can start
 * The next "regular" DB migration checks that the online job is complete and fails with a useful error message if it is not.

So then a deployer would see the equivalent of

```
Running DB migration 0198..
DB migration 0198 complete
Running DB migration 0199
FAILED: Maintenance job 'online-0198' on the 'auth' service must run to completion first
```

The deployer then runs the `taskcluster-auth-maintenance' job with argument `online-0198` (or maybe just `kubectl job run taskcluster-auth-maint-online-0189`) and waits until it completes, at which point the DB migration script can run again and will proceed.

More simply, to re-key the DB, we'd define jobs like `taskcluster-secrets-maint-rekey-secrets` that just scan the table and update the encrypted values to use the latest key.

@sciurus is this similar to anything you've encountered with other tools?  I don't mind re-inventing the wheel, but it's easier to do if I can look at someone else's bicycle while I'm doing it..

**Comment by djmitche** [comment]
For the re-keying jobs at least, it's critical that the job have access to the service's secrets.

**Comment by sciurus** [comment]
I wouldn't think this is worth doing for online migrations alone, but it's a good approach for one-off jobs and could be reused for online migrations too.

From ops' perceptive, the main things we'd have to figure out is where/how these jobs live in the taskcluster repo. They'd need to be separate from the main [helm chart](https://github.com/taskcluster/taskcluster/tree/main/infrastructure/k8s) since we wouldn't want to deploy them each time. It's likely easiest for us to have our existing tooling run them if each job is its own helm chart, but if that's too clunky we could change deploylib to support a different structure.

**Comment by djmitche** [comment]
Hm, I thought k8s had a convenient way to define a job but not run it.  Maybe we could "fake" it by defining cronjobs that don't ever run automatically.

**Comment by djmitche** [comment]
Ah, it looks like "Job" is the thing I want.  A job can be defined with 0 parallelism:

https://kubernetes.io/docs/concepts/workloads/controllers/job/#controlling-parallelism

Thoughts:
* Probably the interface we want is similar to the `yarn db:upgrade` -- that is, via the DB.
* Some jobs will need to run in the context of different services (specifically, with that service's secrets)
* It might not be possible or preferable to automate this as part of the cloudops deployment process, since these jobs will run for a long time (perhaps days).

**Comment by djmitche** [comment]
Thinking more on this:

```
$ yarn db:jobs
name                        | k8s-job                           | state     | notes
----------------------------+-----------------------------------+-----------+------
key-rotation-auth           | taskcluster-db-job-auth           | running   | 39%
key-rotation-hooks          | taskcluster-db-job-hooks          | stopped   |
key-rotation-secrets        | taskcluster-db-job-secrets        | stopped   |                    
key-rotation-web-server     | taskcluster-db-job-web-server     | stopped   |
key-rotation-worker-manager | taskcluster-db-job-worker-manager | stopped   |
online-migration-0131       | db:admin-job                      | completed | completed 2020-11-12T19:32:51.009Z
online-migration-0198       | db:admin-job                      | pending   | waiting to start

$ yarn db:jobs:run key-rotation-hooks
```

`db:jobs:run` could run both `completed` and `stopped` jobs, allowing re-running things as necessary.

The jobs themselves would need to guard against being run at an inappropriate time or in parallel with other jobs.  As we did with the ad-hoc online migration a few months ago, the jobs should run in "chunks", and probably hold a lock on the row in the jobs table while doing so to avoid concurrency problems.  Jobs will be implemented as JS functions, implemented in `db/src/online`.  Online migration jobs will mostly wrap a call to a stored function, while key rotation jobs will just loop over rows, reading, decrypting, encrypting, and writing.

Each k8s job will be defined similar to crontasks for the relevant services, but with the Helm charts generating a Job with parallelism=0.

it would then be up to the admin to start the necessary k8s jobs (setting parallelism=1) for the per-service jobs, as necessary.  For admin jobs (that need the DB admin password), admins will need to run `yarn db:admin-job` from a console with that access (similar to `yarn db:upgrade`).

**Comment by sciurus** [comment]
You could probably talk me into it, but I'm not a big fan of adding these jobs into the main helm chart with `parallelism: 0`. Reasons being

1. I think it's unusual enough it might eventually confuse one of us or a tool we use to unknown effect
1. Over time we might build up a significant number of jobs, making working with jobs a pain
1. The ergonomics of resubmitting a job with increased parallelism aren't really better than just submitting it from scratch

What if you generated them with the desired parallelism, but stuck them all in a new directory outside the helm chart, so we don't automatically deploy them? I think after that you'd have a couple options

One is to do nothing else, and just document that operators have to run `kubectl apply path/to/job.yaml` whenever they need to run of these jobs. For my team's purposes, I think this is good enough.

Another is to build a tool like you've sketched out above that is able to kick off jobs, list their state, etc. If you think this is helpful for your own purposes in dev, we could use it to in production too.

A few random thoughts:

> db:jobs:run could run both completed and stopped jobs, allowing re-running things as necessary.

Once it completes you can't resubmit a job with the same name, so any tools you create would need to either delete the existing job before submitting a new one or incorporate something unique like a timestamp in the job name.

> For admin jobs (that need the DB admin password)

I think we'd need to standardize on a name for the Secret that contains the ADMIN_DB_URL. Right now this Secret is the only one in the cluster that we created instead of you. It's defined [here](https://github.com/mozilla-services/cloudops-infra/blob/master/projects/taskcluster/k8s/charts/migrate/templates/secret.yaml#L4). It currently works out to be named like `migrate-communitytc-taskcluster-migrate-1-migrate` , but we could easily change this to something saner.

> admins will need to run yarn db:admin-job from a console with that access (similar to yarn db:upgrade).

So you're thinking that this would sequentially kick off each pending admin job, similar to how db:upgrade kicks off each migration?

**Comment by djmitche** [comment]
In retrospect I should have avoided this, but I used the terms "job" and "k8s job" distinctly above.  Let's rename the first to "admin job".

Putting the ADMIN_DB_URL in a k8s Secret is an interesting idea.  I didn't realize you did that!  The value definitely shouldn't be shared with any of the services, but storing it in K8s makes a lot of sense, and means that all one-off jobs (including db migrations) could be run as k8s jobs.

I do want to keep a nice separation between k8s and tc-admin-jobs, so that in principle we could run Taskcluster, including its admin jobs, without k8s.

So, I think I want two levels here:
 * a simple way to run a named admin job for a particular service in a docker container; something like `docker run -e ADMIN_JOB=key-rotation-hooks .. hooks/admin-job`.  This is similar to how services and crontasks are run.  We can build a bit of support code to make this pretty formulaic, so that it's easy to add a new named job to a service.  And we'll include `db` as a "service" here for db-wide changes.  That will mean that db migrations can now be run with `docker run -e ADMIN_JOB=db-upgrade .. db/admin-job`.
 * a simple way to run such an admin job as a k8s job.

But I don't know how to do that second part, since Helm typically uses a bunch of values to render the template, for example `.Values.rootUrl`.  In other words:

> One is to do nothing else, and just document that operators have to run `kubectl apply path/to/job.yaml` whenever they need to run of these jobs. For my team's purposes, I think this is good enough.

I don't think that can work, unless Helm can be convinced to dump those files out (or some other automation with access to things like the root URL and the docker image name generates them).  I think that's the crux of the issue.  Which kind of brings be back to the parallelism=0 option, as that allows us to use the existing Helm automation for that purpose.

**Comment by sciurus** [comment]
> a simple way to run a named admin job for a particular service in a docker container; something like docker run -e ADMIN_JOB=key-rotation-hooks .. hooks/admin-job. This is similar to how services and crontasks are run. 

I was wrongly assuming the new "admin jobs" would be launched via yarn similarly to your existing ad-hoc like `generate`, `db:upgrade`, etc. It sounds like you want an additional layer of abstraction to wrap the common elements of invoking admin jobs. If you plan for that to work similarly to how you run services and cronjobs, then that should work fine for us.

> a simple way to run such an admin job as a k8s job. But I don't know how to do that second part, since Helm typically uses a bunch of values to render the template, for example .Values.rootUrl

Okay, I see what you're worried about now. I was not considering that the k8s job will have some dynamic values. Most of them are in the k8s secret and thus are already taken care of, but there are some like the docker image that do need to be remain templated in the k8s job definition.

I think that only requires a minor change to my idea, though. Put all the jobs k8s jobs for the admin jobs in a new helm chart, and run them via `helm template job_chart -s path/to/specific/job.yaml | kubectl apply -f -`

**Comment by sciurus** [comment]
@bqbn do you have opinions on the ideas discussed here so far, or any new ideas?

**Comment by djmitche** [comment]
I'll flag @ricky26 for a similar open-ended request for thoughts, given your experience with k8s and with deploying TC :)

**Comment by bqbn** [comment]
I'm generally nervous about doing db migrations. In old times they are time consuming and prone to errors. Nowadays things improved some but many things can still go wrong depending on which projects you are on. As a result, in general, the last thing I want to run into when doing db migrations is to see an error that is not related to the db migration itself. That really causes headache and sometimes raises heart beat rate and blood pressure. 

In this case and IMHO, I think we should run it as a cron job instead of a middle step of any db migrations, even though we're "sure" this job is not going to fail. Running it as a cron job also eases troubleshooting because when it fails, we don't have to second guess if it's because of some db migration step or not.

**Comment by imbstack** [comment]
> Alternately, instead of a file per k8s job you could have just one and template the secret to load and admin command to run. Then running it would look something like helm template -f path/to/existing/values.yaml --set admin_job=foo,secret=bar job_chart | kubectl apply -f -

I like this plan the most I believe. That couple with admin jobs that know how to not step on each other seems to cover all of the bases.

Cron job also feels ok to me although if it is just happening at some arbitrary time it might be harder to notice it failing immediately which would normally be good to watch for.

**Comment by djmitche** [comment]
> I'm generally nervous about doing db migrations. In old times they are time consuming and prone to errors. 
>
> In this case and IMHO, I think we should run it as a cron job instead of a middle step of any db migrations, 

I agree that DB migrations are anxiety-inducing!  But I'm not sure I understand the link to this issue.   The jobs we're discussing here *are* part of DB migrations (except key rotation, but let's set that aside), so regardless of whether they're run as a cron job or a batch job, they're involved in that process.

I guess you're making a distinction between a cronjob that runs independently of any deployment automation, and a batch job that would be run as part of the deployment automation.  I think that's blurring two distinct things.
 * An online-migration job *must* run to completion between two consecutive DB versions; so for example, after an upgrade to 0091, the online migration for 0091 must complete before the upgrade to 0092 can begin.  (most DB versions won't have an online migration, but some will)
 * Whether or not to run online migrations as part of deployment automation, "by hand", or on a schedule is sort of an implementation detail.  If the deployment automation can be configured to wait (possibly for days) for the online migration to complete, then by-hand/scheduled makes sense.

> Cron job also feels ok to me although if it is just happening at some arbitrary time it might be harder to notice it failing immediately which would normally be good to watch for.

Agreed.  I think the fundamental fact that's going to make this hard to monitor if it happens automatically is that there's no realistic "timeout" after which it's safe to assume something went wrong.  But if we execute them in a full service context, at least we can report errors to sentry.

All of that being said, from a technical perspective the crontask idea is appealing.  They're easy to define in the Helm chart, as we already do.  Those jobs can start up every 6 hours, say, and check for things they need to do.  If that seems wasteful, it's easy to "Pause" those cronjobs (at least in the GKE UI), and if we want to run them quickly, there's also a "Run Now" button.  We'd need to find some way for the key-rotation jobs to avoid a full table scan on every run, but I can imagine a few simple solutions for that.

**Comment by bqbn** [comment]
> The jobs we're discussing here are part of DB migrations (except key rotation, but let's set that aside), 

Oh well, I probably have misunderstood what this issue is about. I thought we **were** talking about key rotation as the initial post seemed to indicate that way, so I was trying to make a point that we should not make key rotation be part of DB migration, but be its own cron job.

Also pardon my unfamiliarity of some taskcluster terms. What is the difference between an "online-migration" and a "db migration"? It sounds like a db migration changes the db version, but an online-migration doesn't. Is that right? And what does an online-migration do usually?

**Comment by djmitche** [comment]
Sorry, yes, the issue has wandered a bit.  You're completely correct -- key rotation would not happen as part of a DB rotation

* *DB Migration*: a single transaction that modifies the DB schema
* *Online Migration*: a gradual, non-blocking operation that modifies DB data

This was born out of our difficulty migrating the task table, where we wrote an ad-hoc online migration in #3235.  In #3641 we'll need a similar thing.  That migration runs `update tasks set task_queue_id = provisioner_id || '/' || worker_type` that will scan and lock the entire table.  The "online" version of that would work like this:

1. In a DB migration, add a nullable `task_queue_id` column to the table and adjust code that creates rows to populate that column as well as `provisioner_id` and `worker_type`.  After this change, `task_queue_id` may be NULL, but once it has a value in a row it will never become NULL again, and in new rows it will have a value.
1. In an online migration, fill in `task_queue_id` a few rows at a time, avoiding holding locks for more than a few ms.
1. In a second DB migration, check that the online migration is complete.  If so, adjust the code that accesses the table to use `task_queue_id` exclusively and drop the `provisioner_id` and `worker_type` columns.

I hope that helps clarify the ideas here.

**Comment by ricky26** [comment]
+1 to the CronJob approach. We use this in some of our backend services for admin-triggered one-off jobs.

In `taskcluster-operator`, I assert a Job for the DB migration every time I reconcile the Taskcluster instance.

It sounds like this issue crosses the point where there's no static set of resources you can assert which will eventually resolve with an up-to-date Taskcluster instance. If `db:migrate` had some machine readable output, you'd have the choice of two options:
- Have a long running service which eternally tries to make sure the DB is fully migrated (which would effectively wait for the online migrations to end in between states).
- Have more complicated Job orchestration, e.g. using an operator. (Theoretically, there's a middle-ground here where you dynamically trigger the CronJob between calls to `db:migrate` but it feels like that's nearly as complicated as the operator approach to the same thing.)

**Comment by djmitche** [comment]
ICYMI, there's an ordering requirement in the existing DB migrations: the DB migration should be complete before the corresponding service code is deployed.  Maybe the operator accounts for that, but I thought I'd mention it.  There's also the single-major-version-at-a-time requirement.  Together, those get us a kind of "alternation" of deployments between DB schema changes and code deployments, which we depend on to avoid incompatibility and deadlocks.

That means that a tool intending to automatically update Taskcluster would need to have some logic to sequence its operations, and maybe some local state.  If all of that's the case, then the assertion is basically "no steps left in the sequence".  That would have to accept that there might be some online migrations still going on, but if you tilt your head just right you can still consider that "an up-to-date Taskcluster instance" in that there's nothing more for the tooling to do.

(I'd be interested in an issue suggesting what machine-readable output from `db:migrate` would look like.  That doesn't sound too hard)

The one open question I still have, then, is whether a DB migration that requires a previous online migration be complete should wait for that migration to complete (with some helpful logging), or fail with an error.  I'm leaning toward "wait" since, for deployments that aren't huge, it usually won't be a long wait.

**Comment by djmitche** [comment]
Also, maybe this is worth an RFC -- thoughts?

**Comment by sciurus** [comment]
This discussion has drifted in directions I didn't expect. I feel like there's two questions

1) Taskcluster has arbitrary jobs that need to be run one time and are unrelated to deploys, such as reencrypting database records with a new key. How should we run those in kubernetes?
2) Taskcluster has some long-running database migrations that can happen online while version N is running but block deploying N+1. Should we continue to have `db:migrate` command run them itself, or should they be invoked separately following the process we define for 1.

For 1:

- Dustin proposes adding them to the existing helm chart as K8s jobs with 0 parallelism, and asking the operator to increase the parallelism of one to run it
- Brian Pitts proposes adding them as a new helm chart where the command and secret to use are templated and requiring the operator to deploy it. Brian Stack likes this approach.
- Wei and Ricky propose adding them to the existing helm chart as K8S cronjobs

I've already commented a bit on things I don't like about parallelism of 0. Although to be clear, I don't _strongly_ dislike it.

For the k8s cronjob approach, I'm unclear why you'd prefer that to a k8s job @bqbn . I agree with @imbstack  that it feels dangerous to have something like reencrypting a database column kick off at an arbitrary time instead of when an operator tells it to. It also feels wrong and a potentially dangerous (depending on how they determine if they have work to do, and how they interact with future changes to taskcluster's schema) to have what are logically one-shot jobs permanently in the cluster, periodically waking up looking for work to do.

For 2:

@djmitche you've been assuming we'll split them out into this new process but it's not clear to me that we should. I already have a helm chart with a k8s job for running db:migrate that I could deploy at an arbitrary time with an arbitrary taskcluster version. I don't see what the advantage is of having that fail and require me to launch another job to perform a online migration and then run it again.

**Comment by djmitche** [comment]
There are, indeed, a bunch of ideas floating around here, and I have been trying to solve two problems with one solution.  That's definitely hard to track, so thank you for summarizing it clearly!

I'm seeing a strong case for *not* solving both with the same solution, particularly now that I know that _all_ deployers of Taskcluster run `db:migrate` in a k8s job!

So here's a new proposal, using the numbering from the previous comment:

For 1: Choose the second option (suggested by @sciurus / liked by @imbstack).  These jobs are unusual so a few "manual" steps are OK.  From a TC developer's perspective, these are pretty simple bits of code that just scan the table, and we can write some library code to support it.

For 2: Incorporate online migration into the `db:migrate` process, such that any `db:migrate` run that introduces a need for an online migration goes on to execute it immediately.  From a deployer's perspective, this means no changes to existing processes.  Looked at from the TC developer's perspective and squinting a bit, this basically means that a migration is no longer limited to a single database transaction.

Those are totally unrelated, too, so we can break them into two issues and solve them at different times.  Nice!

**Comment by djmitche** [comment]
I'll break "2" off into #3733, leaving this issue just covering "1".

**Comment by djmitche** [comment]
Ah, "1" is now in #3734, so I think we can consider this issue finished in the sense it is covered by those two.
