### ISSUE TITLE
Support scalingRatio for workerpools

### ISSUE THREAD

**Issue by jmaher** [taskcluster/taskcluster#3168]
This bug originally read:
> All worker types will inevitably spin up more workers than are needed, I refer to that as overprovisioning.  gecko-t/t-win7-32 is overprovisioned about 4x more than other windows test workers.  I would like to adjust our metrics/heuristics which determine when we create new workers and how many we create.  I am fine with slightly longer queues.

I'm going to take this as a starting point for a bug to support scalingRatio again as a simple tool to help admins dial in their efficiency-to-cost ratios.

Scaling ratio is a number in the range `(0, 1]` where `1.0` would mean "spawn 1 worker per pending task" and `0.5` would mean "spawn 1 worker for ever 2 pending tasks".

I'm not sure this is exactly the formulation we'll use (or if we'll use scaling ratio for sure) by the time we get to the sprint but I'm writing it this way for now.

**Comment by petemoore** [comment]
Some things that will help us here:

1) We now track both workers being launched, and workers reporting themselves as available for work (previously worker manager only knew when it had spawned a worker, but it wasn't clear if that worker was already asking the queue for work)
2) Worker Manager has insight into tasks in the queue (previously it just had a pending count, so if there were `x` pending tasks on its previous check, and `y` pending tasks now, it wouldn't know how many of the `y` tasks were also present in the `x` tasks, and how many of them were "new", so whether it needed to spawn new workers or not).

These are all things of the past, so we should be able to provision in a much more controlled and regulated fashion now, and we won't need to tweak provisioning logic on a per worker pool basis, since they should no longer behave differently depending on their start-up time).

**Comment by imbstack** [comment]
This will require at least the following:

1. Update the schemas for the dynamic providers to support a `scalingRatio` field next to `minCapacity`/`maxCapacity`, etc.
2. Update `Estimator.simple` to take this value and modify `desiredCapacity` by this amount.
