### ISSUE TITLE
web ui: removing dead worker from quarantine throws error

### ISSUE THREAD

**Issue by aerickson** [taskcluster/taskcluster#3242]
**Describe the bug**
I removed a worker from quarantine that had already been destroyed by the worker manager and it threw an error. 

It worked, but I didn't think it did due to the message.

worker: https://firefox-ci-tc.services.mozilla.com/provisioners/gecko-t/worker-types/t-linux-metal/workers/us-west-2/i-03ee7bfd4677f3bc3

```
Worker with workerId i-03ee7bfd4677f3bc3, workerGroup us-west-2,worker-type t-linux-metal and provisionerId gecko-t not found. Are you sure it was created?

```

**To Reproduce**

1. Create a worker.
2. Quarantine it.
3. Have worker manager delete it.
4. Try to remove it from quarantine.

**Expected behavior**
It works without error. I'd be returned to the higher level worker list page with a quasi-modal message saying that the worker has been removed from quarantine.

If the page can't find the requested worker it should show an error or redirect to the higher level page and display a warning.

**Taskcluster version**
33.0.0-1-g4c4ad4262

**Screenshots**
disappeared too quickly

**Platform (please complete the following information):**

 - OS: Mac
 - Browser if applicable FF
 - Version if applicable 78.0.2

**Additional context**
n/a

**Comment by djmitche** [comment]
That UI operation only applies to the queue's notion of what a worker is, and the error is from the queue, so I don't think it has to do with the worker-manager.  Rather, I think it has to do with the worker not having done work for long enough that the record has expired in the queue.

I think what happened is that it literally couldn't find the worker record -- perhaps because quarantine "overrides" a worker's expiration, so that once it was un-quarantined it was immediately expired.

I agree that the UI could be better here, although that may just wait until this UI is reworked to address the larger issue of the queue and worker manager having different notions of workers.

**Comment by djmitche** [comment]
A non-UI fix for this would be to always set the expiration to at least, say, quarantine + 1 day, when setting the quarantine.  Then the worker will not immediately expire after being un-quarantined (and we can remove the extra checks for quarantined date from the expiration logic).

**Comment by djmitche** [comment]
I believe this is addressed in https://github.com/taskcluster/taskcluster/commit/99e646b60ca60221e3989b02b0d25edccc62acfd
