### ISSUE TITLE
Terminated instances appear in the list of workers mixed with running workers

### ISSUE THREAD

**Issue by bccrisan** [taskcluster/taskcluster#328]
**Describe the bug**
Terminated instances appear in the list of workers mixed with running workers

**To Reproduce**
1. Go to 'https://tools.taskcluster.net/provisioners/aws-provisioner-v1/worker-types/gecko-3-b-linux'
2. Copy the Worker ID of an instance that has the task state completed.
3. Go to instances in aws_console and search for that instance.

**Expected behavior**
The instance should appear as running (and probably running another job)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser if applicable: Firefox 65.0.1

**Additional context**
I have looked in that specific pool to check the machines because they had a pretty large queue. That is almost next to impossible because on each page are 1-4 workers that actually exist and the rest of them are terminated instaces (probably).
I'm not 100% sure that these are terminated instances, the name looks like it but it's just a guess.

**Comment by djmitche** [comment]
I don't understand the bug report -- the instances still appear in the AWS console?  If the instance is still running, that makes sense.  If the instance is no longer running, the console displays it as state "terminated" for a while.  At any rate, we don't control the AWS console, so we can't change what it displays.

**Comment by bccrisan** [comment]
The problem is that we have terminated workers in the taskcluster UI, and there are so many that we cannot look at the good workers that pick up tasks.

**Comment by djmitche** [comment]
Ah, I see.  The problem is that we don't know when an instance terminates, and can only infer that it has terminated based on how long it has been since we have heard from the instance.  The [worker manager](https://github.com/taskcluster/taskcluster-rfcs/blob/master/rfcs/0124-worker-manager.md) will provide a totally different approach to this problem, and address this particular bug in the process.  If you'd like to file a bug to track that, it can be blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1478941.
