### ISSUE TITLE
unhandled duplicate unique key in index service

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3463]
https://sentry.prod.mozaws.net/operations/taskcluster-firefox-ci/issues/7969161/events/6e782bccca7643649523b5bd460a3229/
```
error: duplicate key value violates unique constraint "indexed_tasks_pkey"
DETAIL: Key (namespace, name)=(gecko.cache.level-3.toolchains.v3.linux64-android-gradle-dependencies.hash, bea0d7fd57208ad3cb3cd0c28bf48db8ed04dee2317a2cd172988cbbb0e6ac85) already e...
  ?, in null.<anonymous>
  File "/app/node_modules/pg/lib/connection.js", line 606, col 11, in Connection.parseE
    msg = new Error(fields.M)
  File "/app/node_modules/pg/lib/connection.js", line 403, col 19, in Connection.parseMessage
    return this.parseE(buffer, length)
  File "/app/node_modules/pg/lib/connection.js", line 123, col 22, in TLSSocket.<anonymous>
    var msg = self.parseMessage(packet)
  File "events.js", line 315, col 20, in TLSSocket.emit
  File "domain.js", line 482, col 12, in TLSSocket.EventEmitter.emit
  File "_stream_readable.js", line 295, col 12, in addChunk
  File "_stream_readable.js", line 271, col 9, in readableAddChunk
  File "_stream_readable.js", line 212, col 10, in TLSSocket.Readable.push
  File "internal/stream_base_commons.js", line 186, col 23, in TLSWrap.onStreamRead
```

**Comment by djmitche** [comment]
@jwhitlock this might be a good off-sprint bug for you.

**Comment by djmitche** [comment]
Quick summary: in most places in the API implementation where we do inserts, there's a try/catch to handle the constraint violation and implement idempotency -- either returning a 200 if the existing row and the insert request match or a 409 if they do not.  We should do the same thing here.

**Comment by jwhitlock** [comment]
A different [event 335e0f...](https://sentry.prod.mozaws.net/operations/taskcluster-firefox-ci/issues/9746308/events/53611517/) has a shorter namespace / name pair, that identify the PL/pgSQL function as ``create_indexed_task``, raised by the ``index`` service:

```
duplicate key value violates unique constraint "indexed_tasks_pkey"
DETAIL: Key (namespace, name)=(gecko.v2.try.shippable.2020.10.13.latest.mobile, android-api-16-opt) already exists.
WHERE: PL/pgSQL function create_indexed_task(text,text,integer,tex...
```

It looks like the calling code is ``insertTask``, triggered when the task doesn't exist when calling ``get_indexed_task``, but exists a few lines later when ``create_indexed_task`` is called:

https://github.com/taskcluster/taskcluster/blob/f79e42cd338091b677292855bb0ada9fe5e1ac87/services/index/src/helpers.js#L86-L100

I'm guessing the fix is to catch the ``UNIQUE_VIOLATION``, call ``get_indexed_task`` to load it, and proceed to check the database entry against the service parameters as if ``get_indexed_task`` worked the first time.

Also, it looks like similar PostgreSQL errors with different causes are collected by Sentry under the same issue. There's [event d3f78e9a...](https://sentry.prod.mozaws.net/operations/taskcluster-firefox-ci/issues/9746308/events/53973138/) from the ``auth`` service with message:

```
error: client already exists with different values
WHERE: PL/pgSQL function create_client(text,text,jsonb,timestamp with time zone,boolean,jsonb,boolean) line 40 at RAISE
CODE: 23505
```

We might need a different issue for the auth ``create_client`` issue.

**Comment by djmitche** [comment]
I think that's all correct!  And, please do file another issue for `create_client`.

Yes, Sentry's event-merging is not great.  I suppose it's damning with faint praise, but it's far better than Stackdriver's merging!
