### ISSUE TITLE
Plan how to cope with docker hub pull limits

### ISSUE THREAD

**Issue by ccooper** [taskcluster/taskcluster#3475]
Docker is going to start throttling anonymous pulls. We should figure out what we need to do, whether that's all alternative container registry, changes to automation to not pull anonymously, or something else.

See also https://bugzil.la/1660840

**Comment by imbstack** [comment]
Things we've realized/learned:

1. The vast majority of our image pulls are of tc artifacts so that doesn't count against our limit
2. The vast majority of our workers only live for a couple tasks and afaict their limits are ip addr based so we're ok there

Going to monitor the situation and reopen this bug if we are wrong.
