### ISSUE TITLE
Add authenticateAnonymous endpoint to the auth service

### ISSUE THREAD

**Issue by ccooper** [taskcluster/taskcluster#3585]
A new API call will be added to the auth service (authenticateAnonymous) which will return the expanded scopes of ["assume:anonymous"].

See https://github.com/taskcluster/taskcluster-rfcs/pull/165

**Comment by petemoore** [comment]
The proposed new API endpoint is equivalent by definition to the existing [`auth.role('anonymous')`](https://community-tc.services.mozilla.com/docs/reference/platform/auth/api#role) endpoint. I can't think of a good reason to add a second method to return the same information that this call would return, other than if the name of the role 'anonymous' is likely to change. However, even in that case, the name of the API endpoint (`authenticateAnonymous`) would probably also be inappropriate, so we'd have a breaking change anyway.

The endpoint is intended only for internal calls, and then only from a single call site within the auth middleware, so perhaps adding a new API endpoint that users would see, but shouldn't really use, may overall add additional unnecessary noise.

Having worked through the details I've also realised it isn't doesn't really perform any authenticate like the `auth.authenticateHawk` endpoint does (it would service GET requests with no request body), but instead it simply returns a list of scopes (which matches the `auth.role` response body, rather than the `auth.authenticateHawk` response which contains additional auth data) so the name `authenticateAnonymous` is also perhaps a little misleading.

So all in all my preference is not to add the extra endpoint, and call `auth.role('anonymous')` inside the auth middleware instead.

I realise it would have been better to spot this during the RFC approval process, but unfortunately it wasn't until getting into the details that I realised.

**Comment by ricky26** [comment]
This sounds fine from my point of view since the primary concern the separate endpoint addressed was the ability to return additional information about caching. If/when caching comes back up, swapping over to a dedicated `authenticateAnonymous` endpoint is going to cost no more than doing it now.

**Comment by petemoore** [comment]
Thanks Ricky! In that case, I'll close this issue now, and we can always reopen it if we need to.

Even if we cache the response later, perhaps the caller (the auth middleware) could decide how long to cache the results for, in the absence of a dedicated endpoint. However, a dedicated endpoint would allow for an explicit cache expiry, like you say, which is probably cleaner from a data organisation perspective, although requires a little more code and API surface area.

**Comment by djmitche** [comment]
> Even if we cache the response later, perhaps the caller (the auth middleware) could decide how long to cache the results for, in the absence of a dedicated endpoint. However, a dedicated endpoint would allow for an explicit cache expiry, like you say, which is probably cleaner from a data organisation perspective, although requires a little more code and API surface area.

This cache duration would be a deployment configuration item, and those are pretty easy to distribute to all services, so there's not necessarily a need to carry it in the HTTP bodies.
