### ISSUE TITLE
Remove irc support from the notify service

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#3604]
**Describe the bug**
The Kubernetes deployment for notify-irc stays in CrashLoopBackoff forever when IRC is not configured on the Taskcluster instance.

**To Reproduce**

1. Remove the IRC configuration from the Taskcluster values.yml
2. Deploy to Kubernetes
3. Look at the Kubernetes deployment for notify-irc
4. Notice that it is in the CrashLoopBackOff state.

**Expected behavior**
notify-irc should either not be deployed if IRC is not configured or should gracefully do nothing.

**Taskcluster version**
v37.2.0

**Comment by djmitche** [comment]
The workaround we've used is to dial the deployment count down to 0, but that's pretty bogus.

My understanding is that irc is the only one of the notification methods that requires a constant connection, which is what necessitated the separate k8s deployment.  If that's likely to remain the case (and let's be honest, everything in the last 20 years uses HTTP as a transport, so it is) then maybe the fix here is to remove irc support.

That, coupled with https://bugzilla.mozilla.org/show_bug.cgi?id=1522154, might suggest a bit of a refactor so that notification methods can be easily configured or left disabled with a single deployment configuration parameter, similar to the `worker_manager.providers` configuration.  Then when we add, say, a Facebook Chat plugin (?!) it's just adding `facebook.js` and adding `facebook` to a few other files, and deployments not using facebook can be confident it won't cause any issues for them.  It's a pattern we'd like to follow with the object service, too.  My memory of the notify code is that it's pretty close to this already, meaning this would be a relatively tame refactor.

**Comment by imbstack** [comment]
Yeah, irc is the odd one out for sure. Maybe we keep it around for now but default to the deployment count being 0 for it?

Otoh the irc support is very basic as-is so we could always add it back if somebody wanted it later. You don't want irc support, right @ricky26? I think I've convinced myself that we should remove it since the notify service becomes much cleaner without irc.

**Comment by ricky26** [comment]
@imbstack yeah, as sad as it is, I don't want IRC support. (Pure curiosity, is the persistent connection requirement to minimise channel join/leave noise?)

**Comment by djmitche** [comment]
Yes, that's the reason behind the persistent connection requirement.

Let's remove it.
