### ISSUE TITLE
db v48 -> v49 hung on a lock

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3632]
**Describe the bug**
Migration from v48 to v49 hung on a lock and was locking some other tables.

From Slack:

```
taskcluster=>   select relation::regclass, * from pg_locks where not granted and mode='AccessExclusiveLock';
-[ RECORD 1 ]------+--------------------
relation           | queue_artifacts
locktype           | relation
database           | 16415
relation           | 91613110
page               | 
tuple              | 
virtualxid         | 
transactionid      | 
classid            | 
objid              | 
objsubid           | 
virtualtransaction | 12/23931639
pid                | 1060149
mode               | AccessExclusiveLock
granted            | f
fastpath           | f
```

so it can't get lock on `queue_artifacts`.

**Comment by helfi92** [comment]
I wonder if the fix would be to simply get a lock on the tables affected before running this migration. Thoughts?

**Comment by djmitche** [comment]
I think the outage comes from locking table A, then waiting for a lock on table B: while waiting, table A is unusable.

I believe that the actual alter operation is very quick regardless of number of rows (I think it just marks the column as hidden in the table metadata), so it might be best to do this table-by-table: lock table A, alter table A, unlock table A, lock table B, ..

I'm not sure if there's a way to release a lock within a transaction, so that might require multiple transactions -- not something we currently support in a single DB version script.

**Comment by djmitche** [comment]
https://www.postgresql.org/docs/8.1/sql-lock.html
> (There is no UNLOCK TABLE command; locks are always released at transaction end.)

That is the kind of simple, declarative statement I love to read in documentation.  Unfortunately, it doesn't say what I would like to say.

It seems we are "out of the woods" on this in that the upgrade has finished successfully.  So perhaps the lesson to learn is that many `alter` operations which will require a full table lock should not be bundled into a single db version, but spread out over multiple versions, especially isolating frequently-accessed tables in their own db versions.
