### ISSUE TITLE
tc-github intermittently spews out 100+ comments on some commits.

### ISSUE THREAD

**Issue by JohanLorenzo** [taskcluster/taskcluster#3637]
**Describe the bug**
Sometimes, when someone pushes to a tc-enabled repo, taskcluster-github repeatedly comments with the error:

```
Failed to get your artifact.
```

**To Reproduce**

This issue was first reported to me by @badboy, 7 days ago. It happened on https://github.com/mozilla-mobile/android-components/commit/d7e7482c115d477595b1430d492bb711f5c66db2, which was a regular commit on a non-fork repo.

Another instance of this bug happened yesterday, with @alopezz: https://github.com/mozilla-mobile/android-components/commit/da6225aa1558768c3b39042351b29a45d02ccba1. This commit was on a PR.

I don't have more information on how to reproduce it. I guess tc-gh logs will help 

**Expected behavior**
Either a single error or getting tc-gh schedule the decision task.

**Taskcluster version**
 v37.3.0 for yesterday's instance.

**Screenshots**
N/A

**Platform (please complete the following information):**
N/A

**Additional context**
None.

**Comment by badboy** [comment]
One note: android-components has ~100 tasks or so on TaskCluster, so I suspect TC is complaining for each and every single one of these tasks.

**Comment by djmitche** [comment]
I believe this comes from looking for custom check-run text and annotations.

https://github.com/taskcluster/taskcluster/blob/7e08c8041c2a23959599d807c1498a94c677b865/services/github/src/handlers.js#L428-L450

That fetch occurs on every task completion for a checks-enabled repo, and will add this comment for any response but 200 and 404.  I suspect that the instance that occurred yesterday was during the upgrade that caused the queue to "hang" for a while (probably generating timeouts, rather than an HTTP response status code).  I don't know why it would have happened seven days ago.

The `throttleRequest` call should retry around intermittent issues, so this would have to be some longer-term failure (which was the case yesterday).

If we had more robust commenting support, we might be able to avoid the *multiple* comments.  Also, we could probably include a more descriptive message in the error.

**Comment by alopezz** [comment]
> Another instance of this bug happened yesterday, with @alopezz: [mozilla-mobile/android-components@da6225a](https://github.com/mozilla-mobile/android-components/commit/da6225aa1558768c3b39042351b29a45d02ccba1). This commit was on a PR.

Happened again on the next commit of the same PR: https://github.com/mozilla-mobile/android-components/pull/8654/commits/5c6dd00b2a3b05cc030d81d4e2e82fa8cd8fe2d7

**Comment by djmitche** [comment]
Let's aim for a minimal investigation and fix here:
 * is the throttling working?
 * is there something specific about this repo causing issues?
 * is this likely to continue to happen frequently?
 * is there a class of errors that we could just not comment on at all, without losing valuable diagnostic feedback for users?
