### ISSUE TITLE
Remove superseding support

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3773]
Rationale:
* Firefox-CI's usage of superseding was dropped in https://bugzilla.mozilla.org/show_bug.cgi?id=1620610.  I don't know of any other uses.
* The two worker implementations implement superseding in vastly different ways
* There are security issues around having workers (not the task) call out to an arbitrary URL in the task definition
* The design is unlike anything else in Taskcluster

**Comment by djmitche** [comment]
@petemoore what do you think?

**Comment by petemoore** [comment]
The current state of affairs is certainly suboptimal:

  * the feature is not widely understood
  * we appear to have zero users of the feature (as far as I am aware)
  * there are differences between the docker-worker and generic-worker implementations
  * it is rather a complex feature that requires providing a service to integrate with taskcluster, which itself entails security complications

However, I'm also not convinced that we have a good story for handling spikes of load without superseding, and a concern I have if we drop the existing support, is that if we suddenly have constrained pools, we don't have a good strategy for executing the most important tasks.

One thing that is different now than when we implemented superseding, is that previously we had opaque queues that were not inspectable, and were also immutable. Now we have a postgres backend, this all changes, and there is the possibility to be a bit more dynamic in the `queue.claimWork` handler. Essentially superseding is a matter of scheduling, so this is probably the better home though, for handling any decision making about which tasks should be executed, rather than forcing this on the worker, and requiring workers to set task resolution to 'exception/superseded' (when the queue could probably do this itself).

I do feel there is still one open matter that taskcluster does not currently address well, which superseding tried to assist with (but didn't do a good job at). That is, typicallly taskcluster is often used as a CI tool to execute tasks when a source code change occurs, but by default, when a series of changes occur in short succession, there are two problems:

1) the tasks associated with the "older" changes (commits) are executed first
2) there is no easy way to indicate to taskcluster that the result of the older tasks is only relevant if a newer task fails (which is typcially what you care about in a CI - if all the new tasks are green, the intermediate commits aren't so important, especially if you will squash commits at the end of a PR cycle etc)

I think now we have the postgres backend, this is the perfect time for us to review our approach to how best handle these types of scenarios, and like you, I tend to agree that superseding is probably not the best we can do.

@ricky26 Have you been using the superseding functionality, or do you have opinions on it?

**Comment by djmitche** [comment]
Agreed -- I think those are all reasons to look to a completely new way to approach load shedding.  But, that's not something we need to do now.  Assuming it's not in use at WPG, are you OK with removing it?

**Comment by ricky26** [comment]
We've not set anything up with superseding. We are interested in this area though for similar reasons.

Due to licensing reasons, we can only run a certain number of our client workers. If a branch is being worked on heavily we suffer in a similar way. (As an aside, am I right in thinking that there's no great way for workers to notice that tasks are cancelled quickly at the moment?)

An interesting example that's not quite the same issue is this: we are using Taskcluster to run our environment deployments. If two infrastructure commits go into our main branch in quick succession, you get a bit of a deployment race. If they're close enough together (and timing favours the newer one) the old task still running can roll back changes.

I'm personally interested to see where this goes as I don't really have a good general solution in mind.

**Comment by djmitche** [comment]
OK, so it sounds like nobody's opposed to removing the superseding support.  My brain's a little full right now to think about other load-shedding designs, but that shouldn't stop anyone else thinking about it!

**Comment by petemoore** [comment]
I am not opposed to removing the support when have a better solution in place, but I wouldn't be in support of removing it while we have no other tools to handle load spikes. I don't think removing it gains us a lot, since it is an optional integration that has no cost if not used, and the code in the workers has no real maintenance cost (I don't think it has been touched since it was first implemented, and isn't a common source of bugs etc).

**Comment by djmitche** [comment]
We _currently_ have no tools to handle load spikes -- superseding has proven itself not up to the task.  The risk of not removing it is that someone might use it.  As a tiny team working on a large project, we need to limit the number of things we support, and supporting un-used, broken things is not a good use of our resources.  But, I agree that removing the code to support it from the workers is probably more effort (and likelihood of bugs) than leaving it in place.

So perhaps the best strategy is to label the support as deprecated and remove the documentation.  Then if the worker code does become problematic, we can confidently remove it at that time.

**Comment by petemoore** [comment]
So with superseding, the deployer is responsible for providing a service which decides which tasks to supersede, and which ones not to - and I suspect in the case of firefox ci, where the superseding support was dropped, that perhaps the issue lay in the coalescing service, rather than in the taskcluster platform. At least I am aware of no bugs in the taskcluster implementation, and the bugs only mention that more superseding occurred than was desired in November 2019, but no root cause is documented. I agree that if nobody is using it, it is an opportunity to remove it. I was only hesitant, because it was a pretty big piece of work to implement, and I wasn't aware it was causing any problems. But I'm also happy for it to go, if nobody needs it, and we want to redesign it. I think we _do_ have a means to handle spikes, but it is heavily involved for a project that needs it, since they need to build and deploy their own service to support it, so it is probably not something that will get a lot of usage before we invent an alternative system.

**Comment by djmitche** [comment]
I mentioned some reasons in the first comment:

* The two worker implementations implement superseding in vastly different ways
* There are security issues around having workers (not the task) call out to an arbitrary URL in the task definition
* The design is unlike anything else in Taskcluster

I couldn't suggest WPG use superseding, for example -- at least not without a caveats that someone will need to do a hefty bit of work to make it function as advertised, and a good bit more work to make it function as desired.  For example, to support cancellatoin.

**Comment by djmitche** [comment]
@petemoore this is in the current "stabilization" sprint.  Do you think it's OK to proceed?
