### ISSUE TITLE
Quarantined workers still contribute to capacity estimation

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#3794]
**Describe the bug**
If a worker on a cloud provisioner with a high capacity is quarantined it can take a long time for new tasks to get scheduled because the quarantined worker still contributes to available capacity.

**To Reproduce**

1. Create a new worker pool using a gcp provider, with `idleTimeoutSecs` at least 600.
2. Create a task so that it spins up a new worker.
3. Quarantine the worker.
4. Create a new task.
3. Notice that the task remains pending (and no worker is created) for at least 10 minutes.

**Expected behavior**
Quarantined workers should not contribute to existing capacity and new workers should be spun up to handle the currently pending tasks.

**Taskcluster version**
v37.3.0

It looks like this could just be adjusted in worker-manager's provider, similarly to how requested workers don't contribute to total requested capacity.

I'm happy to attempt a PR for this if there are no terrifying gotchas I'm not aware of!

**Comment by djmitche** [comment]
@ricky26 in reading over this again, I'm wondering why you would quarantine a cloud worker, rather than just terminate it (with `workerManager.removeWorker` or directly in the cloud API)?

**Comment by ricky26** [comment]
@djmitche this was a little while ago but if I remember correctly there were a couple of things that brought me here:
- Wanting to investigate a broken worker (without stopping tasks from executing).
- Deleting a worker _whilst it's running a job_ was taking a while to realise that the worker had disappeared (you can use quarantine to let it finish, which is fine, but during that it still contributes to capacity estimation, _which is exacerbated with workers which can handle multiple tasks in parallel_).
  - I did this with the GCloud API.

**Comment by djmitche** [comment]
OK, that makes sense.  A few higher-level observations based on that information and some observations of how sheriffs at Mozilla have used the feature:
 * quarantine is a useful way to take a worker out of circulation while letting its running tasks continue
 * deletion/termination of workers results in a `claim-expired` exception quite a bit later (currently 0-15 minutes), leaving the executing task in limbo until then
 * high-capacity workers exacerbate this particular problem

Fixing this issue directly is a little tricky, since it's the queue which tracks quarantines, and the worker-manager which counts capacity.  We could probably add some visibility for worker-manager into the `queue_workers` table, and do a left join against that table.

I think longer-term (#4582) we should move all of this status information currently maintained by the queue into the worker manager.

I'll take a crack at it, but if it turns out to be a lot tricky, I may give up and defer to the longer-term plan.
