### ISSUE TITLE
Parts of Github integration currently won't work in deployments without an `anonymous` role

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#3867]
**Describe the bug**
taskcluster-github queries taskcluster-queue a lot for various bits of information needed to update statuses in github checks/statuses. This is done with a client with no scopes available. This was fine prior to rfc165 but now we need to give this client certain scopes in its `static/taskcluster/github` client for locked down deployments with no `anonymous` role.

This is fairly easy to do but it does raise some questions about what this would be allowing. The most obvious issue is with custom check annotations. taskcluster-github loads artifacts for this and as it stands can only access public artifacts. If it instead is using its entire set of scopes, it could read almost any artifact in the deployment!

There should be some compromise we can reach here.

**Comment by djmitche** [comment]
So, the scope in question is [`queue:get-artifact:<name>`](https://docs.taskcluster.net/docs/reference/platform/queue/api#getArtifact).

We could access this artifact a few different ways:
 1. with no credentials, so that the scope must be available in the anonymous role
 1. with tc-github's static credentials
 1. with tc-github's static credentials, having added `queue:get-artifact:*` to those creds
 1. with authorizedScopes containing something like `['assume:repo:github.com/<owner>/<repo>:<something>']`

Of those, (2) seems like a particularly bad idea, as those credentials would only get `queue:get-artifact:<name>` scopes from whatever `repo:github.com/..` roles happen to be defined.  So if one repo added `queue:get-artifact:super-secret-check-status.txt`, another unrelated repo could use that scope.  That seems messy!

(3) seems pretty bad, too -- it means tc-github could take *any* artifact and put its contents on github, publicly.

(4) might be a good idea for fine-grained control, but I'm not sure what the `<something>` would be.

I prefer (1), on the reasoning that tc-github is basically taking these artifacts and copying their content to a public place; doing so with an artifact that is not already public is implicitly increasing the visibility of that artifact.  Requiring that the artifact be public avoids that issue.

@ricky26 this is most likely to affect your deployment, so I'd love to hear your preference!

**Comment by ricky26** [comment]
Personally, I like the sound of (4). We use private GitHub repositories, so it's not necessarily safe to assume that GitHub itself is a public place (which makes (1) a bit awkward). Assigning the access to the artefact under a `repo:` role sounds like the right place to me.

I very much agree that (2)/(3) are not ideal.

**Comment by djmitche** [comment]
Wow, I totally forgot GitHub supports private repos.  Hah!

Any idea what `<something>` should be?

**Comment by ricky26** [comment]
If I understand correctly, that represents the context of the action being performed. So perhaps something like `check(s)`? I would've said something like `commit-status` but I think that terminology is slowly being replaced with checks in GitHub.

I can't think of any useful parameters to add to `<something>` either.

**Comment by djmitche** [comment]
`checks` sounds good.
