### ISSUE TITLE
Document config format for websocktunnel secret

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3892]
See https://github.com/wellplayedgames/taskcluster-operator/pull/8#discussion_r521233295

**Comment by djmitche** [comment]
@ricky26 I'm actually pretty confused here.  From what I can tell, this is just a string, and it's a copy of the string at

![image](https://user-images.githubusercontent.com/28673/101931658-bb20d380-3ba7-11eb-9e66-9b268b01f0e8.png)

I don't think there's any special formatting required of the Helm value.  At least, in my dev env it's not got any special formatting.  What have I missed?

**Comment by ricky26** [comment]
I think it derives from it being an `env:list` type. The regex is `/'[^']*'|"[^"]*"|[^ \t]+/g`; something like `"abc" 'abc''abc' asd123` gives you `["abc", "abc", "abc", "asd123"]`. Whilst confusing, as per that issue `"hello"'world'"` gives you `["hello","world"]`. I think it has to be `env:list` so that you can rotate secrets without downtime.

I think the fact that Helm takes it as a string too increased my confusion. :sweat_smile:

**Comment by djmitche** [comment]
Got it, thank you!

**Comment by djmitche** [comment]
(That regexp is super-confusing, but really it's just space-separated strings.  I simplified a bit in the docs, since there's no reason to use quotes in this case (and this is the only use of `!env:list` in TC)
