### ISSUE TITLE
docker-worker fails to load image from gzip’ed artifact

### ISSUE THREAD

**Issue by SimonSapin** [taskcluster/taskcluster#3899]
https://community-tc.services.mozilla.com/tasks/KEHqmyN_SZCqh4rkKILD1g/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FKEHqmyN_SZCqh4rkKILD1g%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive.log#L33

```
[taskcluster 2020-11-11 19:10:01.594Z] Downloading artifact "public/image.tar.lz4" from task ID: f5coRt3YTxuwrhaCY_LzEQ.
[…]
[taskcluster:error] Pulling docker image has failed.
[taskcluster:error] Error: Error loading docker image. Could not decompress image file.Exit Code: 44 Errors: Error 44 : Unrecognized header : file cannot be decoded
```

This image is built by another task, and rebuild on demand when the `Dockerfile` changes or when the previous artifact expires. Here it was recently rebuilt: https://community-tc.services.mozilla.com/tasks/f5coRt3YTxuwrhaCY_LzEQ#artifacts

Because of https://github.com/taskcluster/taskcluster/pull/2809 this artifact is served gzipped:

```
$ curl -sLI https://community-tc.services.mozilla.com/api/queue/v1/task/f5coRt3YTxuwrhaCY_LzEQ/runs/0/artifacts/public%2Fimage.tar.lz4 \
  | grep encoding        
content-encoding: gzip
```

**Comment by SimonSapin** [comment]
Code near here should probably check for the `content-encoding` header and decompress as appropriate:

https://github.com/taskcluster/taskcluster/blob/32720727a859e1d03f913d2f96cb9a9c01066572/workers/docker-worker/src/lib/util/artifact_download.js#L42

**Comment by djmitche** [comment]
You can patch this from the worker-pool definition with something like
```json
      "workerConfig": {
        "shutdown": { .. },
        "artifacts": {
          "skipCompressionExtensions": [
            ".7z", ".bz2", ".dmg", ".flv", ".gif", ".gz", ".jpeg", ".jpg", ".png",
            ".swf", ".tbz", ".tgz", ".webp", ".whl", ".woff", ".woff2",
            ".xz", ".zip", ".zst", "lz4"
          ]
        }
      },
```

**Comment by SimonSapin** [comment]
That’s in the pool of the worker that creates the image, right?

**Comment by djmitche** [comment]
Yes.

**Comment by djmitche** [comment]
It "shouldn't" be an issue that the artifacts are compressed, as they are properly annotated with a Content-Encoding header.  However, some clients (curl and, as we see here, docker-worker itself) do not accept that content-encoding.  These clients are reasonably well-behaved in that they do not send `Accept-Encoding`, so a well-behaved HTTP server would not send an encoded response ([details](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation)).  Note, too, that [406 is not allowed in the case where no Accept-Encoding header is present](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) -- the expectation is that the server is always willing to send an un-encoded response.  Which S3 is not willing to do.

It's worth noting that this was an implementation of behavior that already exists in generic-worker.  So in part it's the surprise of this change that is the issue, rather than the implementation.

I still don't know how we'll solve this (or if a solution exists) in the object service; perhaps we just won't support compressed objects on S3.  Perhaps other clouds do a better job.

So as I see it, we have a few options here:
 * add this extension to the do-not-compress list (this is the absolute minimal fix for this issue, #3900)
 * fix docker-worker to send Accept-Encoding: gzip and continue to expect `curl` users to pass `--compress`
 * revert compression support entirely in docker-worker
 * add a property to the `artifacts` in a task definition to enable compression (defaulting to off)

**Comment by djmitche** [comment]
> * fix docker-worker to send Accept-Encoding: gzip and continue to expect curl users to pass --compress

What I meant here was, fix docker-worker to accept gzip-encoded responses and decompress them; and expect curl users to pass `--compress` to do the same thing.

**Comment by SimonSapin** [comment]
Not gzip-compressing `.lz4` files makes sense and fixes the immediate issue here, but the same issue would still exist with uncompressed (except for gzip added by the worker implementation) Docker images.

If automatic compression of artifacts exists then a better fix is for docker-worker to support it.

**Comment by djmitche** [comment]
38.0.5, just released contains the .lz4 fix in #3900.

**Comment by jschwartzentruber** [comment]
Is there a workaround for uncompressed images? I think I hit this in https://community-tc.services.mozilla.com/tasks/PT5FVOmcTrmprP6elOefgA:

```
[taskcluster 2020-11-13 18:19:50.911Z] Downloading artifact "public/grizzly-reduce-tc-monitor.tar" from task ID: CxTGdb-oRV6xGUPMwVz3UA.
[taskcluster 2020-11-13 18:19:52.331Z] Downloaded artifact successfully.
[taskcluster 2020-11-13 18:19:52.331Z] Downloaded 14.970 mb
[taskcluster 2020-11-13 18:19:52.332Z] Loading docker image from downloaded archive.
[taskcluster:error] Pulling docker image has failed.
[taskcluster:error] Error: Error loading docker image. Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
```

`curl` confirms the artifact is gzip'ed.

**Comment by djmitche** [comment]
I think that will be the second item ("fix docker-worker to send Accept-Encoding: gzip").  Which I'll work on shortly.  Adding `.tar` to the list of extensions to skip (similar to [above](https://github.com/taskcluster/taskcluster/issues/3899#issuecomment-726101670)) is, I think, the current best workaround.

**Comment by jschwartzentruber** [comment]
That did work, thanks!

**Comment by SimonSapin** [comment]
Confirmed that forcing the Docker image to be re-created and re-uploaded as an artifact with 38.0.5 worked around the issue.
