### ISSUE TITLE
python index client appears broken for client.findArtifactFromTask(index, artifact)

### ISSUE THREAD

**Issue by grenade** [taskcluster/taskcluster#4022]
**Describe the bug**

when calling `findArtifactFromTask` from the python taskcluster index client, running within a task that uses the taskcluster proxy, an exception is thrown which reads:
```
Cannot use two authentication schemes at once this request has both bewit in querystring and and 'authorization' header
---
* method:     getLatestArtifact
* errorCode:  AuthenticationFailed
* statusCode: 401
* time:       2020-12-03T12:10:48.066Z
Traceback (most recent call last):
  File "//./debug.py", line 9, in <module>
    artifact = taskclusterIndexClient.findArtifactFromTask('project.relops.cloud-image-builder.azure.win10-64.latest', 'public/image-bucket-resource.json')
  File "/usr/local/lib/python3.9/site-packages/taskcluster/generated/index.py", line 128, in findArtifactFromTask
    return self._makeApiCall(self.funcinfo["findArtifactFromTask"], *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/taskcluster/client.py", line 270, in _makeApiCall
    response = self._makeHttpRequest(entry['method'], _route, payload)
  File "/usr/local/lib/python3.9/site-packages/taskcluster/client.py", line 531, in _makeHttpRequest
    raise exceptions.TaskclusterAuthFailure(
taskcluster.exceptions.TaskclusterAuthFailure: Cannot use two authentication schemes at once this request has both bewit in querystring and and 'authorization' header
---
* method:     getLatestArtifact
* errorCode:  AuthenticationFailed
* statusCode: 401
* time:       2020-12-03T12:10:48.066Z
```

**To Reproduce**
execute `taskcluster.Index({ 'rootUrl': os.environ['TASKCLUSTER_PROXY_URL'] }).findArtifactFromTask()` from within a task that has the taskclusterProxy feature enabled

* a full reproduction example is demonstrated at: https://gist.github.com/grenade/d681a022c0fc525f6147d1bad99e9f53
* an example of a task using the gist example is shown at: https://stage.taskcluster.nonprod.cloudops.mozgcp.net/tasks/Epd6mXheRc6EKWtlqapSnw

this reproduction was tested on the taskcluster staging deployment at: https://stage.taskcluster.nonprod.cloudops.mozgcp.net/tasks/create where the contents of `.taskcluster.yml` from the gist were used to define the task.

**Expected behavior**

the requested artifact should be returned by findArtifactFromTask

**Taskcluster version**

**Screenshots**

**Platform (please complete the following information):**

 - OS: [e.g. windows]
 - Browser if applicable [e.g. firefox, safari]
 - Version if applicable [e.g. 57]

**Additional context**

**Comment by djmitche** [comment]
Ah, I think I see the issue!  Instead of returning an API response, that method returns a redirect to the queue service, which again redirects to the artifact.  It's typically used with `buildUrl` rather than directly.  But since in this case the artifact is a JSON blob, nothing stops the Python client from following the redirects and parsing and returning the final object.  That's not something we planned to support, but it makes sense.

And I should say "nothing stops" except that the redirect to the queue now (with the advent of the anonymous role) contains a bewit, to which tc-proxy dutifully attaches an Authorization header.

I think we can fix that relatively easily, by not adding the header when a bewit is present.  But that'll wait for the next release, and it's unlikely that `gecko-1/b-linux` will be upgraded from its in the forseeable future, so you might need to create a new worker-type to see that fix.

The much more practical fix will be to generate the URL for that artifact using `bulidUrl` and then fetch it with a regular HTTP client (not via the proxy).  Another alternative would be to simply disable the proxy for this particular request and just use the TASKCLUSTER_ROOT_URL directly.

**Comment by djmitche** [comment]
(I'm sorry I didn't realize this yesterday!)

**Comment by grenade** [comment]
thanks! that's an easy workaround. much appreciated!

**Comment by djmitche** [comment]
I broke this out into some sub-issues.
