### ISSUE TITLE
Support for browser-based auth for viewing artifacts

### ISSUE THREAD

**Issue by ajvb** [taskcluster/taskcluster#4031]
_from discussion within https://github.com/taskcluster/taskcluster/issues/3946_

In the cases where Taskcluster is hosting an artifact that should be kept private, should there be support for private / authentication-required artifact URLs?

As I understand it, for private artifacts, a signed S3 URL is generated and that is what is used to retrieve the artifact. This definitely prevents against the case of guessable URLs and since signed S3 URL's have a max TTL of 1 week that helps greatly in the case of URLs being leaked.

But if we have artifacts that are sensitive enough, or if Taskcluster is to be used by those with artifacts that are sensitive enough, should there be support for certain artifacts to only be accessible via a URL with authentication / authorization enforcement as to completely remove the ability to accidentally leak these URLs? Whether that be through Taskcluster directly (rather than a signed S3 url) or something else.

**Comment by djmitche** [comment]
I suspect that the right answer here is, don't store such stuff in artifacts.  Artifacts are more of an "API" (like S3) than a UI element (like Google docs), so requiring UI-style authentication to view them would be difficult and an awkward fit.

In particular, it would require some kind of intermediary to serve the content only after validating the authentication, with that authentication a property of the browser (cookie, localstorage, etc.) rather than of the URL.  I think that intermediary would be best implemented as something outside of Taskcluster.  Maybe it's a dedicated service, or maybe it's something off-the-shelf.  Maybe it uses artifacts as a backing storage, or maybe it stores the data elsewhere and has a way to receive data from workers.

Please feel free to disagree :)

**Comment by djmitche** [comment]
Thinking more on this, I think this is something that should be implemented outside of TC, in any case where it's needed.  Here's how:

 * set up a backend that matches the artifacts needing additional protection, that writes to a private bucket
 * use the CDN middleware to redirect requests to those artifacts to whatever middlebox implements the additional auth requirements -- be that a URL behind a VPN, or an nginx proxy that does NTLM authentication, or whatever.  That middlebox would have the credentials to access the data in the private bucket.
