### ISSUE TITLE
Upgrade to ECMAScript Modules

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4260]
I believe this is an all-or-nothing change to the entire JS codebase.

Once this is done, we can use
* `quick-lru` (#4257).  Our use of that specific module is not nearly deep enough to drive this change -- at worst, we could find another (still CJS) LRU package.
* `markdown-table` (#4566)
* `p-queue` (#4678)
* `got` (#5388 )
* ~~`escape-string-regex` (#4783)~~
* `@sentry/browser` (#5547)

**Comment by djmitche** [comment]
This may also be a good time to drop use of @sindresorhus's packages in general.  This seems to be a determined mission on their part to make unnecessary work for other people.

**Comment by sindresorhus** [comment]
You might want to read [this](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77) if you haven't already. The motivation is not to annoy people, but rather to rip off the bandaid quickly (the bandaid being fully moving to ESM). This will benefit the community in the long-term even if it's a small inconvenience right now. A lot of OSS maintainers have committed to moving to ESM at the end of the month, so this problem is not just going to be with my packages.

**Comment by djmitche** [comment]
I did -- the problem is that it's a large band-aid for a large application that consumes many libraries.  We need to figure out how to schedule that work.

**Comment by djmitche** [comment]
Also sorry to ping you here -- in my head @'ing someone on github only notifies them if they're following the repo, but this is not the first time I've been proven wrong on that point!

**Comment by djmitche** [comment]
I took a crack at updating just `services/built-in-workers` (which only has four .js files) to ESM.  It's definitely well clear of a few regexes and into "rewrite" territory, especially `test/helper.js`, which does a lot of runtime manipulation of its exports.

I'd say this would be 1-2 weeks' work, and would need to be in a "quiet" time when other nontrivial things weren't landing, since merge conflicts will be pretty awful.
