### ISSUE TITLE
Link artifact logs do not use the log viewer

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#4411]
**Describe the bug**
When using link artifacts for live logs, the redirect works but the log is shown as plain text in a new tab.

**To Reproduce**

1. Create a new task which takes its own task ID.
2. In the task, create a log artifact (content-type 'text/plain' & .log extension).
3. Create a link artifact to the log artifact.
3. In the task view, notice that clicking on the log artifact displays the log viewer.
4. Notice that clicking the link artifact does *not* show the log viewer.

**Expected behavior**
Link artifacts which link to log artifacts should use the log viewer.

**Taskcluster version**
v41.0.0

**Additional context**
It looks like this is because `listArtifacts` returns an empty `contentType` for link artifacts. There are two fixes I can think of:
a) Make it so the DB function does a JOIN for link artifacts to retrieve the content type.
b) Include the artifact name in the DB function and have the taskcluster UI piece together the information.

**Comment by djmitche** [comment]
Perfect diagnosis, as always:
```
    const isLogFile =                                                                                                                                                                                                                                                                                                                                                                          
      contentType.startsWith('text/plain') && name.endsWith('.log');
```

Links can point to other links, and the `getArtifact` applies some cycle-detection to avoid infinite loops.  That's not something that'd be easy to do well in SQL, though.  Alternate ideas:

* Change the UI to just use `name.endswith('.log')` alone to recognize logfiles
* Require specifying a contentType on creation for link artifacts as well

I got things a bit wrong when I first looked at the contentType property -- I thought it was completely unused, and a relic of some of the artifact types we've removed.  That's why I was so cavalier in just omitting it for Link artifacts.  I've since learned that it is an "advisory" for what type of data to expect in the file, with the understanding that actually downloading the data might result in something completely different.

In that light, I think the latter option ("Require specifying a contentType..") might be the right blend of "correct" and "practical".

**Comment by djmitche** [comment]
Minor correction: it seems the default contentType is `application/json`, per the source and some experimentation:

```
{
  "artifacts": [
    {
      "storageType": "link",
      "name": "public/test.log",
      "expires": "2021-02-16T20:34:14.000Z",
      "contentType": "application/json"
    }
  ]
}
```

**Comment by djmitche** [comment]
#4228 hasn't landed yet, so I'll update that to provide a content-type (which will mean it can't land until the fix for this issue is resolved.. ugh)
