### ISSUE TITLE
[UI] improve loading performance of docs.html

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#449]
We can remove some chunks and functionality from the /docs view to allow it to load faster.

**Comment by djmitche** [comment]
@helfi92  I think you fixed this up by putting all docs in one chunk?

**Comment by helfi92** [comment]
Yes, docs are a lot faster now. We can still improve performance however by removing the apollo stuff since we don't do any graphql queries and don't render things differently whether the user is logged in or not. I think it should be okay closing this given that we're okay with current docs performance.
