### ISSUE TITLE
[UI] support searching docs

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#450]
The docs are spread over quite a few pages, and it's not always obvious where to find some key piece of information.

A search feature would help!

**Comment by helfi92** [comment]
We could perhaps use [Docsearch](https://community.algolia.com/docsearch/) to provide the search feature. The normal way requires sending the documentation URL to the algolia team. In order to not have to reach out to the Algolia team for every spawned cluster, we could [run our own crawler](https://community.algolia.com/docsearch/run-your-own.html) instead. We could potentially use the [documentation-scrapper docker image](https://hub.docker.com/r/algolia/documentation-scrapper) to do the crawling and indexing.

**Comment by djmitche** [comment]
We could potentially run that during `yarn build`, which runs lots of other stuff in docker images.  But from a glance at the "run your own crawler" link, it seems like it scans static pages via GET requests -- would it have any success trying to scan a react app?

It seems like something that indexes the `.md`/`.mdx` files (and maybe the references?) directly would be a better fit for our needs.

**Comment by helfi92** [comment]
Setting [`start_urls`](https://community.algolia.com/docsearch/config-file.html#start_urls) to https://taskcluster-web.netlify.com/docs and [`js_render`](https://community.algolia.com/docsearch/config-file.html#js_render-optional) to `true` in the config file will perform the crawling in a Selenium browser. I believe we should be okay.

**Comment by djmitche** [comment]
True, but that's not a great URL to crawl, as it's not necessarily running the version of the docs that we're building.  To use selenium to do the crawling, we'd need to run a full copy of tc-ui in another docker container at the same time and link the two.  That seems like a super-complicated way to index markdown files :)

**Comment by helfi92** [comment]
> That seems like a super-complicated way to index markdown files :)

Many of the files are not markdown. They contain Javascript.

**Comment by djmitche** [comment]
Give it a shot, then :)

**Comment by helfi92** [comment]
Sure. Just wanted to see if there was consensus before doing this :)
