### ISSUE TITLE
Update rerunTask docs regarding completed, unscheduled tasks

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4587]
https://bugzilla.mozilla.org/show_bug.cgi?id=1458896

**Comment by escapewindow** [comment]
MoCo releng does occasionally rely on this behavior: in this graph,

    X -> Y -> Z

we may have a perma-broken task `Y`, but we want to run task `Z` anyway. The current behavior allows for this: cancel task `Z` to move it from `unscheduled` to `exception: canceled`, then rerun task `Z` to move it from `exception: canceled` to `pending`. However, this is a special case and maybe shouldn't be the default. Maybe some sort of admin or force action? Having this capability avoids having to reschedule an entire 10k task taskgroup if a task in the middle is perma-failing, but humans decide we want and are able to proceed anyway.

In other cases, maybe task `Y` and `Z` are in a failed or exception state, but that was a temporary external issue, now resolved. Then we may want to rerun task `Y` and task `Z`, but we may want task `Z` to wait for the 2nd run of task `Y`. In these cases, we'd prefer if task `Z` moved from `failed` or `exception` to an `unscheduled` state rather than `pending`.

(We can solve for this latter case currently if we rerun task `Y`, wait for it to complete, and then rerun task `Z`. This is harder to do when we're talking about hundreds or thousands of tasks where we have to act as manual dependency resolvers, however.)

**Comment by escapewindow** [comment]
Maybe a `reschedule` that moves the task to `unscheduled` if it has non-complete dependencies, and `pending` if all dependencies are complete? or `rerun --ignore-dependencies`? The former may let us lock rerun down to admins only. Not sure about details, just that we want both behaviors at different times, and potentially limited to different groups of people.

**Comment by djmitche** [comment]
Would https://docs.taskcluster.net/docs/reference/platform/queue/api#scheduleTask work in that case?

The other option here is to document the current behavior.  The linked bug notes that the docs do not correspond to the implementation, and there are two ways to fix a problem like that!

**Comment by djmitche** [comment]
Maybe let's just update the docs, rather than risk disrupting existing workflows :)
