### ISSUE TITLE
All clients should retry HTTP 400's when uploading via object service convenience methods

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#4623]
Originating from: https://github.com/taskcluster/taskcluster/pull/4493#discussion_r599007535

**Comment by djmitche** [comment]
I did some experimenting by pausing during uploads, and I can't replicate this behavior.  I get broken pipes from hangups, but no 400's.

I suspect AWS fixed this bug, and we don't need to work around it anymore.  The risk to keeping the workaround is that real 400's will be retried for a long time instead of failing quickly.

So I'll remove this from the go client.  If we do see this again, or figure out a way to reproduce it, we can restore that bit and put similar functionality in the other clients.

**Comment by djmitche** [comment]
..that said, https://aws.amazon.com/premiumsupport/knowledge-center/s3-socket-connection-timeout-error/ was updated recently.  I'll keep trying to reproduce this.  If I can, then I can find a specific attribute of the response that indicates it's an "S3 error" and only retry on that.
