### ISSUE TITLE
New UI: Task status updates aren't seen as accurately as the old

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#469]
**Describe the bug**

When comparing a new PR in https://github.com/mozilla-mobile/android-components which leads to may individual tasks in a group being created, I see the old using is updated far quicker than the new UI (which seems to poll for updates).

**To Reproduce**
1. Create a PR in android-components.
2. Observe the old and new UI side-by-side.
3. Observe when task statuses are updated in both UIs.

**Expected behavior**
The new UI should subscribe for task status updates instead of polling for them.

**Platform (please complete the following information):**
 - OS: Mac OS
 - Browser if applicable: Firefox
 - Version if applicable: 67.0a1 (2019-03-15) (64-bit)

**Comment by helfi92** [comment]
Thanks for the issue. I do agree that it would make more sense to subscribe to a task instead of polling in this situation. Polling becomes a problem when you have to support task groups that takes a while to load (10k+ tasks) for something like a release job. I will experiment with switching to a subscription model and see if that improves the experience.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/fd837dfde1cce4e813c054c41091f9c1d57bc519. Thank you for bringing this up.
