### ISSUE TITLE
Current ingress YAML does not work with nginx ingress

### ISSUE THREAD

**Issue by MasterWayZ** [taskcluster/taskcluster#4913]
Currently, `infrastructure/k8s/templates/ingress.yaml` uses `/*` in all its paths. However, nginx ingress, or at least the nginx ingress addon for minikube does not support this. The fix is to remove all the `*` and then it will work instead of 404.

**Comment by imbstack** [comment]
Let's make this a configuration option for `dev:apply` maybe? Could also be a "compile-time" option maybe. I'll need to think on this more.

**Comment by lotas** [comment]
I've made some changes to make it work in #5613

Initially I thought I could simply use helm templating to introduce conditional rendering `{{ if eq .Values.ingressType "nginx" }} ..` but that turned out to be problematic, since `ingress.yml` is autogenerated. And that means it goes through several YAML parsers before it comes to its final state. And all those templating constructs are not valid YAML, which makes it rather impossible without direct string manipulations.

Proposed solution will work if you set `ingressType: nginx` in your `dev-config.yml`. It will then make sure all URLs do  not include trailing `*`.

I also added some extra annotations to allow using both cert manager and ingress nginx
