### ISSUE TITLE
Add ability to re-run PR checks for intermittant network issues

### ISSUE THREAD

**Issue by jwhitlock** [taskcluster/taskcluster#4950]
On a test run for PR #4948, the db-library test failed:

https://community-tc.services.mozilla.com/tasks/EfEaT4CZSAGk_wLAeneZUw

```
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/googleapis/-/googleapis-73.0.0.tgz: unexpected end of file".
info If you think this is a bug, please open a bug report with the information provided in "/taskcluster/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

This appears to be an intermittent network failure. Downloading the file worked locally, and this test passed on other recent PRs.

Taskcluster has several features that would appear to address retrying tasks, but they do not work.

There is a "Re-run" link next to the failed task in GitHub. Clicking this displays the message "You have successfully requested db-library be re-run". It does not appear to run a test in Taskcluster.

<img width="1231" alt="github rerun" src="https://user-images.githubusercontent.com/286017/128559444-72f3c8cd-e7f3-4750-aa66-19ae3cbb74bd.png">

When viewing the failed task in Taskcluster, the action menu has a "Rerun" action and a "Retrigger (disabled)" action:
<img width="318" alt="tc task actions" src="https://user-images.githubusercontent.com/286017/128559588-464633d1-e5c4-4ce6-9fd1-f8d185532ff2.png">

This displays a re-run page with a message: 

> Rerun a task.
> This only works on failed or exception tasks in the original taskgraph, and is CoT friendly.
> This action triggers hook project-taskcluster/in-tree-action-1-generic/f62bbc6185.

with a Action ``{}`` and a Schema:

```
properties: {}
type: object
```

Clicking "RERUN" with these defaults results in an error:

> Action is misconfigured: decision task's scopes do not satisfy in-tree:hook-action:project-taskcluster/in-tree-action-1-generic/f62bbc6185

<img width="1251" alt="tc task rerun failure" src="https://user-images.githubusercontent.com/286017/128560323-e8b97bd8-914f-4d07-a2ab-525c43d016db.png">

Ideally:

* Tasks that are known to fail due to intermittent network issues would retry, perhaps as part of the original task definition
* The "Re-run" button in GitHub would work
* The "Rerun" action in Taskcluster would work

**Comment by lotas** [comment]
The first part of the problem was already resolved, `re-run` event is now being processed

**Comment by lotas** [comment]
so the issue here is that taskcluster is using taskgraph which for some reasons (CoT) auto-generates `actions.json` always. 
This generated file relies on the [hooks](https://docs.mozilla-releng.net/en/latest/taskcluster/known_problems.html?highlight=actions#actions-are-broken-after-modifying-taskcluster-yml) that should be created externally by 3rd party tools whenever `.taskcluster.yml` changes. 
I don't think `taskcluster/taskcluster` needs those hooks are needs any custom `actions.json`.

By removing this file from artifacts folder, all tasks within taskgroup can use rerun/re-trigger/cancel actions directly from the UI which will not use definitions from `actions.json` and will run from the UI
