### ISSUE TITLE
Task which ran successfully should not have been rerun

### ISSUE THREAD

**Issue by Archaeopteryx** [taskcluster/taskcluster#5038]
**Describe the bug**
https://firefox-ci-tc.services.mozilla.com/tasks/diAT8-P3SOKUoVYsnMionA/runs/0 ran successfully (`exit code: 0`) but got rerun https://firefox-ci-tc.services.mozilla.com/tasks/diAT8-P3SOKUoVYsnMionA/runs/1 which caused issues because the task action had been already executed. If I remember correct, there is already an issue/bug for this undesired behavior but I cannot find it.

**Taskcluster version**
43.2.0

**Comment by escapewindow** [comment]
The worker died or hung after running the script, which resulted in a `claim-expired` exception for run 0.
In run 1, we detected that the apk had already been submitted and exited.
I don't think there's anything actionable here.

**Comment by petemoore** [comment]
Agreed. It looks like taskcluster behaved appropriately under the circumstances, it is just rather unfortunate that the worker died / disappeared after completing that step, but before resolving the task run.

There may be a bug for the worker losing contact with the Queue, but I don't think we have enough context here to be able to look into that more deeply, and it could be due to a miriad of problems, including issues in AWS itself. The rerun mechanics are designed to improve the robustness of the system by rerunning when there are unexpected disconnects, like this one, and I think this is the best we can do in the circumstances.
