### ISSUE TITLE
Implement RFC 168 - Process Github issue_comment events to support adhoc task creation

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#5073]
Details in the RFC [here](https://github.com/taskcluster/taskcluster-rfcs/blob/main/rfcs/0168-Trigger-Tests-Based-on-PR-Comments.md).

**Comment by lotas** [comment]
TODO: check how much this overlaps with actions.json

**Comment by lotas** [comment]
I started working on this issue and here are some implementation details:

- as per discussion in [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1715848) we will not support `merge` command (@bhearsum @ahal please correct me if I'm wrong)
- comments can be created, edited and deleted. We would only react on `created` event and ignore `edited`. To avoid running multiple task graphs for the same comment. 
- [`comment.action.author_association`](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=created#issue_comment) is one of: `COLLABORATOR, CONTRIBUTOR, FIRST_TIMER, FIRST_TIME_CONTRIBUTOR, MANNEQUIN, MEMBER, NONE, OWNER`. We would only act if it is `COLLABORATOR`
- `issue.state` can be `open, closed` - we only act if the issue is open 
- `issue.pull_request` - we only act if this is the actual pull request and not an issue

**Comment by lotas** [comment]
Also, I don't think it was discussed, but would be good to give some feedback to those comments in form of taskcluster-bot replying to a given comment (or adding new comment) with execution summary:
- "in response to comment above, I created this task <link>" (or similar)
- "error creating tasks for command above - reason: unsupported command, available: run-tests, run-tests-svc,..."

**Comment by bhearsum** [comment]
> I started working on this issue and here are some implementation details:
> 
>     * as per discussion in [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1715848) we will not support `merge` command (@bhearsum @ahal please correct me if I'm wrong)

That's right. As I understand it, the only thing we're supporting directly is firing the new event. Any implementation of a `merge` command would be left to a consuming repository.

>     * comments can be created, edited and deleted. We would only react on `created` event and ignore `edited`. To avoid running multiple task graphs for the same comment.

This sounds sensible to me.

> 
>     * [`comment.action.author_association`](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=created#issue_comment) is one of: `COLLABORATOR, CONTRIBUTOR, FIRST_TIMER, FIRST_TIME_CONTRIBUTOR, MANNEQUIN, MEMBER, NONE, OWNER`. We would only act if it is `COLLABORATOR`

Is there definitions of these somewhere? `OWNER`, `MEMBER`, and `CONTRIBUTOR` might also be needed, depending on what they mean. The most flexible option might be to pass this along and let the repository deal with it though...

>     * `issue.state` can be `open, closed` - we only act if the issue is open

:+1: 

>     * `issue.pull_request` - we only act if this is the actual pull request and not an issue

:+1:

**Comment by bhearsum** [comment]
> Also, I don't think it was discussed, but would be good to give some feedback to those comments in form of taskcluster-bot replying to a given comment (or adding new comment) with execution summary:
> 
>     * "in response to comment above, I created this task " (or similar)

This sounds good to me.

> 
>     * "error creating tasks for command above - reason: unsupported command, available: run-tests, run-tests-svc,..."

I _think_ this is outside of the scope of tc-gh. It will hand off the arguments given to the command to `.taskcluster.yml` as json-e context, which will be used to decide what tasks to create or not, and maybe even forwarded to a decision task in the case of taskgraph. So I think tc-gh won't know enough to make such a comment?

**Comment by ahal** [comment]
Nice, this is exciting!

> comments can be created, edited and deleted. We would only react on created event and ignore edited. To avoid running multiple task graphs for the same comment.

I agree with you and Ben that ignoring edited seems fine, especially for an initial pass.. But I don't think having multiple graphs attached to the same comment is necessarily a problem. If someone made a typo, it might be nice to correct it rather than paste the comment a second time. But definitely not a big deal and if we implement it it could be a follow-up.

> We would only act if it is COLLABORATOR

Seems like OWNER should also have this ability

> "in response to comment above, I created this task " (or similar)

Do you know if the task will show up in the `checks` UI in the pull request? (I think we should try to ensure it does). If we can do that, maybe Taskcluster can instead react with a thumbs up emoji like dependabot does.

I agree it should comment on failure though (just like for normal pull request events).

> I think this is outside of the scope of tc-gh. It will hand off the arguments given to the command to .taskcluster.yml as json-e context, which will be used to decide what tasks to create or not, and maybe even forwarded to a decision task in the case of taskgraph. So I think tc-gh won't know enough to make such a comment?

I think it can comment if there's an error rendering the `.tc.yml`. So it should at least comment for that (like it already does for other events). But yeah, task failures (incl Decision task) means you'd need to check the log.

**Comment by lotas** [comment]
I was wondering if empty command should be a valid one or there should be some constraints?

`/taskcluster` probably shouldn't do anything
but
`/taskcluster anything-till-the-end-of-line` will trigger task generation with those params: 

```yaml
tasks_for: github-issue-comment

# separate name to avoid collision with original github event
event.taskcluster_comment: anything-till-the-end-of-line

# original event data
event.action: created
event.issue: { .. } 
event.comment: { .. } 
event.repository: { .. } 
event.organization: { .. } 
event.sender: { .. } 
```

**Comment by bhearsum** [comment]
I agree that an empty command (`/taskcluster`) probably shouldn't do anything. I guess theoretically there could be some default case in the `.taskcluster.yml` that gets hit, but I can't fathom any desirable use case for that seeing as this feature is all about allowing for explicit requests to be made through comments.

**Comment by lotas** [comment]
@ahal @bhearsum 
I'm testing it on dev currently - https://github.com/taskcluster/tc-dev-integration-test/pull/17 

And I've come across one interesting "feature". I am an admin on that repo through org team. So when handler asks calls github api to check this: `/repos/taskcluster/tc-dev-integration-test/collaborators/lotas -` it returns 404 for some reason 

Only when I add myself as a user, it starts returning 404. So it ignore team hierarchy for some reason.
Did you see similar issues in other features and github integrations maybe?

**Comment by lotas** [comment]
Ok, this is likely due to the missing permission for an application - it needs to have some org read permission (need to figure out which one)
