### ISSUE TITLE
[UI] remove search pattern for clients viewer

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#513]
On the old tools site, by default we searched for clients whose names have the current user's clientId as a prefix.  This was done because we have a convention of naming users' clients after their own clientId (and tc-login gives them permission to do so).  That convention is now embodied in the client creator, and most users generate clients that way.

The old UI showed the search pattern right above the list.  The new UI shows it far away in the upper-right corner, in a rather dim typeface.  This has now tripped me up a few times, where I don't see the client I'm looking for and go wondering how it got deleted.

Let's just default to showing all clients, like we do for roles.

**Comment by djmitche** [comment]
![Screenshot_2019-03-29 Clients - Taskcluster](https://user-images.githubusercontent.com/28673/55263649-19791780-5248-11e9-9db7-f7b460cf12c1.png)
*omg where's my client*

**Comment by projectyang** [comment]
Hey,

I can remove this - I implemented the previous behaviour, so would be familiar with reverting it.

**Comment by helfi92** [comment]
Awesome, go for it :)

**Comment by helfi92** [comment]
Check your email. I sent you an invitation to become a collaborator :)

**Comment by projectyang** [comment]
If a user has submitted a search in the view, and then signs in/out, is the expected behaviour:

1. The search query and results remain as before
2. The search query and results reset back to default

**Comment by helfi92** [comment]
The search query and results remain as before.

**Comment by helfi92** [comment]
How is it going @projectyang? Let me know if you had questions :)

**Comment by projectyang** [comment]
Hey @helfi92,

I'm a bit stuck. 

I'm using componentDidUpdate as a way to refetch the previous query and results after a sign in/out event:

`async componentDidUpdate(prevProps, prevState) {...
if (this.props.user !== prevProps.user) { refetch...}`

However, this approach will briefly cause the 

> resetStore: Store reset while query was in flight error

whenever a user signs in and out.

I assume the problem is because the refetch is occuring during the same time as reset/clearStore. I've tried using setTimeOut on the refetch as a hacky way to avoid it, which works for signing in. But signing out (clearStore) will still trigger the error. 

I'm not too familiar with Apollo, so I was wondering if there's a better way to accomplish this?

**Comment by helfi92** [comment]
> I'm using componentDidUpdate as a way to refetch the previous query and results after a sign in/out event:

No need to do a refetch after a sign in/out event :)

**Comment by projectyang** [comment]
> > I'm using componentDidUpdate as a way to refetch the previous query and results after a sign in/out event:
> 
> No need to do a refetch after a sign in/out event :)

Sorry if I'm misunderstanding, but if I don't include a refetch, wouldn't a sign in/out event reset the previous query and results on the clients view.

**Comment by helfi92** [comment]
> Sorry if I'm misunderstanding, but if I don't include a refetch, wouldn't a sign in/out event reset the previous query and results on the clients view.

Sorry, I forgot about that. In that case, let's just stop resetting the store since it's causing too much trouble. We can use `.clearStore` instead which won't clear the previous queries.

**Comment by projectyang** [comment]
I'm probably missing something very obvious...

If I use clearStore on both sign in and sign out components or even disable it entirely, the clients data still resets to the full list. Does onAuthorize/onUnAuthorize automatically force a reset?

**Comment by helfi92** [comment]
> the clients data still resets to the full list. Does onAuthorize/onUnAuthorize automatically force a reset?

Ah, I see. Yes it forces a reset because the when a user logs in/logs out, the state is changed in `src/App/index.jsx` which ends up re-rendering all of its children. When the clients view gets re-rendered, it will trigger the graphql query.

One solution would be to embed the search string in the url `http://localhost:5080/auth/clients?search=github` for example. Want to do that?

**Comment by projectyang** [comment]
Ah, I see. And the search string method sounds good, I'm on it.
