### ISSUE TITLE
The roles page takes a long time to render when there are a few hundred roles

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5179]
UI side, the graphql API responds way faster than the page takes to render. Example here: https://divvun-tc.thetc.se/auth/roles

**Comment by lotas** [comment]
I've discovered that material UI table is causing those slow renders. Also a problem for filtering that I've introduced in #5218

**Comment by lotas** [comment]
I've spent some time debugging the issue. Problem there that Roles page (and most of the others) are using `1000` as default page size to render all elements. 
Rendering of each single row takes time, because of dozens of components wrapped around it.

I see two approaches how we can solve this:

1. Reduce markup to the bare minimum (For example list of `280` roles renders around `4700` dom elements. This can be simplified to have twice as fewer components). This is still slowish, but feels faster than it was.
2. Change the way how `ConnectionDataTable` component renders such tables. Currently it renders all rows at once. We can apply `react-virtualized`/`react-window` List wrappers, to render only what's inside the viewport. Rendering of such pages will be instant

Second approach will require slightly more refactoring, as it will touch most of the pages where lists/tables are used. 
Another downside would be that you cannot use native browser Find in Page functionality (as not all rows are rendered). Considering we have filtering on the tables themselves, I think we can sacrifice this functionality in order to make pages load faster and be more responsive.

**Comment by lotas** [comment]
@Eijebong can you please remind how big was your Roles table? Community has around 280 roles so it is somewhat bearable. Iirc you had around 600? 
I think the easiest fix is to set page size to ~100, or just implement custom rendering

**Comment by Eijebong** [comment]
Well I'm hitting pagination limits so more than 1000

**Comment by lotas** [comment]
Fix was merge. It will now should render only rows visible on the page. Layout was simplified a bit also (removed link icon, as the whole row is clickable anyway)

**Comment by Eijebong** [comment]
Will test as soon as a release contains the patch and let you know ;)

Please remind me in two weeks that I haven't tested it because there's a 99.9% change I will forget though.

**Comment by lotas** [comment]
Woo-hoo! Great, now we need to go through the rest of the tables with grids and possibly do the same.. 
Do you have any other pages with hundreds of rows?
