### ISSUE TITLE
Put the log files at the top of the list in task artifacts

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5362]
Currently artifacts are sorted alphabetically, however the chances of you wanting anything but logs there is pretty slim (as far as my workflow goes, maybe my workflow is too specific).

I feel like it would help if the log artifacts would always show up first in the artifacts list instead of me having to look for it.in the list. And yeah, there's a filter, but that's extra work :)

**Comment by lotas** [comment]
@Eijebong I just realized that it was already fixed in the past :)

![image](https://user-images.githubusercontent.com/83861/165490356-63995706-e2ed-402e-b5b9-4d513428988d.png)

Link to the logs is a huge button on top. Do you see the same on your instance? 

I will still place them on top in the list

**Comment by Eijebong** [comment]
![39dd72b7-e654-4326-8038-37d88d65791a](https://user-images.githubusercontent.com/3650385/165491147-a2098fc7-3c23-427e-97d9-f4c39f385f07.png)

It's not there if you don't have livelog enabled

**Comment by lotas** [comment]
Fix merged
