### ISSUE TITLE
Cache missing or corrupted problems repeat

### ISSUE THREAD

**Issue by davehouse** [taskcluster/taskcluster#5363]
**Describe the bug**
https://bugzilla.mozilla.org/show_bug.cgi?id=1595217 If a file is missing on the filesystem but still in the file-cache.json or directory-cache.json, then generic-worker attempts to copy it and panics when the filesystem move fails.

https://bugzilla.mozilla.org/show_bug.cgi?id=1539681 If a cached file/dir is corrupted, generic-worker does not run a checksum to catch this. Instead when generic-worker runs a task using the corrupted cache file(s), it moves the bad file(s) into place and allows the task to fail. Because of this, we see repeated failures on the affected worker for tasks using the corrupt cache file(s). This appears as an intermittent failure to sheriffs.

**To Reproduce**

Missing cached file
1. Remove a cached file from the filesystem.
2. Run a task that uses the cached file.
3. Notice that generic-worker fails when trying to move the missing cache into place.
4. Loop to step 2

Corrupt cached file
1. Modify a cached file or directory on the filesystem.
2. Run a task that uses the cached file.
3. Notice that generic-worker fails when running the task.
4. Loop to step 2

**Expected behavior**
Could generic-worker check if cached files exist before trying to use them and remove them from the cache record if they're missing?
Could generic-worker as part of this check run a checksum for the on-filesystem cached file(s) to verify it is not corrupted?

generic-worker does remove cached file(s) if there is a failure moving it back into the caches directory (back out from within the task_XX dir), but only if it fails to move it. This could also be a place to verify the checksum of the cache to make sure the finished task did not alter the cache contents?

**Taskcluster version**
v38
The failures have increased over the last 3-4 years. Perhaps this has increased with the increased use of the cache

**Screenshots**

**Platform (please complete the following information):**

 - OS: Linux, MacOS (I assume WIndows g-w also could have this happen if not already happening)
 - Browser if applicable [e.g. firefox, safari]
 - Version if applicable [e.g. 57]

**Additional context**

**Comment by petemoore** [comment]
Thanks for the detailed report @davehouse.

Indeed generic-worker can/should do a sanity check that cached files exist and have correct checksums, where checksums are known.

I _think_ in multiuser engine, it shouldn't be possible for a task to corrupt a cache file, since the task should not have write access to generic-worker's copy of the cached files. Do you know whether this is broken, or whether it is something outside the task that is deleting/modifying generic-worker's caches?

The generic-worker could theoretically purge the cache if it found it to be invalid, but I think at the least it should alert that something has interfered with the environment, as there shouldn't be anything interfering with the caches, and tasks should not be able to do this either. With simple engine, it is a different story, since it is insecure, and tasks can cause all sorts of trouble. But with multiuser engine it should simply not be possible, and if it is, it means there is a more serious bug we need to look into, since the caches are essentially internal state of generic-worker, and should not be subject to external interference.

**Comment by petemoore** [comment]
> If g-w could validate the cache after and before each use, that could give data points that may reveal when it is happening. That may expose if tasks are corrupting it, or if there are g-w actions/failures?

That is a great idea!
