### ISSUE TITLE
[UI] Provide way to act on several tasks from group view

### ISSUE THREAD

**Issue by lissyx** [taskcluster/taskcluster#564]
Use case is being able to `rerun` or `retrigger` several failed tasks with little effort from the group view.

**Comment by helfi92** [comment]
One way to achieve that is to create two new speed dial buttons "Rerun Failed Tasks" and "Retrigger Failed Tasks" in the Task group view that would have the necessary logic to rerun the tasks.

**Comment by djmitche** [comment]
Ideally those operations would be implemented as [actions](https://docs.taskcluster.net/docs/manual/design/conventions/actions), which the UI will automatically make available.  There's a surprising amount of subtlety in what "retrigger" and "failed" mean, so we prefer to leave it to the CI system to define those things instead of assuming we know.

**Comment by helfi92** [comment]
Even better! Is there a Bugzilla bug on file for this or should I create one?

**Comment by helfi92** [comment]
Continued in https://bugzilla.mozilla.org/show_bug.cgi?id=1588857.

**Comment by reuben** [comment]
Isn't this making things more complicated than they have to be? TaskCluster doesn't have to know about any subtleties, just let the user choose. My idea is: let the user select several tasks in the group view, then trigger actions that exist on all the selected tasks. The rerun/retrigger/cancel buttons already exist without me having to define any custom actions, I just want some UI to trigger the same action on several tasks.
