### ISSUE TITLE
https://firefox-ci-tc.services.mozilla.com/hooks/project-relman/code-review-production errors out with 504

### ISSUE THREAD

**Issue by marco-c** [taskcluster/taskcluster#5804]
Loading https://firefox-ci-tc.services.mozilla.com/hooks/project-relman/code-review-production or https://firefox-ci-tc.services.mozilla.com/hooks/project-relman/code-review-testing doesn't work. After a while, the following error is displayed:
> Network Error (504): ServerParseError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by lotas** [comment]
So there's a network time out. 
And I believe that's because it tries to fetch _all_ last fires without pagination.
For the `project-relman/code-review-production` it already has `203461` records, which will probably take long to serialize to respond.

We should introduce proper pagination and maybe split calls to load page without that initially.

**Comment by lotas** [comment]
related to #4870

**Comment by lotas** [comment]
Discovered that it's not only the UI that tries to fetch everything, hooks api is also loading all of the fires to determine the most recent one
