### ISSUE TITLE
Run yarn commands against clean checkout when building service containers

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#5922]
The repository root `Dockerfile` defines the docker image to be used by service containers.

In the process of creating the docker image, yarn is installed and run inside a docker container. However, the yarn commands are not run against a pristine checkout of the repository code, but rather a manipulated version of the checkout, which the yarn targets are not guaranteed to work with.

It would be cleaner to run the `yarn install` against an unmodified checkout of the source code, and then move parts into place, rather than the other way around. This would have avoided the problems we saw in #5921.

**Comment by lotas** [comment]
I think the problem there was my fix from #5920  .. which I forgot to check against the Dockerfile

This is the recommended way to build dockerfiles for node projects - copy package.json/lockfiles first, do yarn install, and only then copy over the source code. This is to let heavier operations (yarn install) run first and be cached, so that the files that are modified more frequently (code) would be added on the next step.

I think this is all fine, just the preinstall script was broken.. but it was hotfixed in #5923

**Comment by lotas** [comment]
There was already `git checkout` inside the dockerfile which caused some different kind of issues. And it was only created to avoid unwanted files to get into the build. 
This was then changed and `.dockeringore` file was added so that docker wouldn't copy unwanted files inside the container. So I think the files inside are quite clean (unless source code was modified, but this is a different topic probably)

**Comment by petemoore** [comment]
OK, let's leave it as it is then. :-)
