### ISSUE TITLE
Implement sealTaskGroup method

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#6059]
During implementation of #3652  we had an idea that it would make sense to have functionality to "seal" task group, that would make it impossible to add new tasks for this group.

This should might be used together with `cancelTaskGroup` to save resources and be sure that new tasks wouldn't be added from some decision tasks that are still running.

Discussion points:
* should this be reversible? `sealTaskGroup` + `unsealTaskGroup`?
* does it need any new scope like `queue:seal-task-group:<taskGroupId>` ?

**Comment by petemoore** [comment]
I think I prefer sealing a task group to be irreversible, since it keeps things simple and makes it easier to reason about things knowing it can't later change (and associated race conditions/concurrency issues around task groups becoming unsealed while other activities are taking place).
And I also agree `queue:seal-task-group:<taskGroupId>` is good. Perhaps `queue:seal-task-group-for-project:<projectId>` might also be reasonable (i.e. `AnyOf` these scopes being sufficient).
