### ISSUE TITLE
workerManager spawns unbounded new instances when image is busted

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskcluster#6332]
Over the past two days there was an issue where a pool was configured with a broken image. This happened in the evening / overnight so we didn't notice for 12 hours. In that time worker manager kept spawning new instances over and over until we had thousands of them. This used up all SSD quota, and ground fxci to a halt.

I'm assuming that workerManager is querying the current number of workers from the queue service. But since these busted workers have never claimed a task, the queue service doesn't know about them.

Instead, I think worker manager needs to make sure that it looks at its own tables for the true number of running workers. I believe it should never exceed `maxCapacity` , even if workers are unknown to the queue service.

One downside of this is that the busted workers will never claim a task, so it could mean that if `maxCapacity` is filled with busted capacity, we'd have to wait a long time for the problem to resolve itself (without manual intervention). To get around this, maybe `workerManager` could be much more aggressive at automatically killing workers when they aren't claiming any tasks. Or perhaps if it detects a large queue of tasks despite `maxCapacity` being reached, it could start killing off the oldest workers to make room for newer ones (which may be fixed).

**Comment by petemoore** [comment]
I think this is a duplicated of #6142

**Comment by lotas** [comment]
Yes, problem here that w-m knows pretty well how many instances it created/are running, but it doesn't have a clue how good they are, if they started claiming tasks or not.  So this part is missing. 
I don't think it ever exceeds now `maxCapacity`, but if you have 90% of workers in the pool that are running but not doing anything, it's gonna have a huge impact. 

So we can start tracking imagesets that were used to start that particular workers, and keep track of stats for each. Worker manager can then periodically ask queue service it there were requests from those workers, and if not, it should stop requesting those, throw some errors, or panic otherwise. 
Perhaps we can also start rolling out new images way slower, introduce some scaling factor. Like if image is new, only do `Min(1, 10% of requested)` or so and wait a bit to see if it's working.
This would probably affect "good" images, as polls would be scaling slower, but would also help not to start "bad" images in big proportions

**Comment by ahal** [comment]
Ah my apologies, I jumped to conclusions here.. If we never exceed max capacity, I'm ok closing this out.

It sounds like for that particular pool we should lower max capacity :)

**Comment by ahal** [comment]
After chatting in Slack, let's close this out and use #6142 for improvements in this area.
