### ISSUE TITLE
Failed to fetch live.log and backing_live.log

### ISSUE THREAD

**Issue by Jadon-Harris** [taskcluster/taskcluster#6395]
I followed the document to run taskcluster locally, but can not open live.log and live_backing.log.
![image](https://github.com/taskcluster/taskcluster/assets/65598607/37e3ee7b-6f7c-44f7-a800-4a29a978a33e)

**Steps to reproduce:**
1. git clone https://github.com/taskcluster/taskcluster
2. cd taskcluster
3. yarn start
4. add “127.0.0.1 taskcluster” to /etc/hosts 
5. sign in (**Client Id:** static/taskcluster/root, **Access Token:** j2Z6zW2QSLehailBXlosdw9e2Ti8R_Qh2M4buAEQfsMA)
6. create a task and save
![image](https://github.com/taskcluster/taskcluster/assets/65598607/04529a45-6cab-47a1-81a2-9c90a20c4a57)
7. click live.log or live_backing.log

**Expected behavior:**
click live.log or live_backing.log and show the log in ui.

**Actual behavior:**
![image](https://github.com/taskcluster/taskcluster/assets/65598607/c0c7c883-9b0c-41f0-beea-183f14315257)

**Environment information:**
- Operating System: Windows 10
- Browser: Chrome

**Comment by lotas** [comment]
Thank you @Jadon-Harris for reporting this issue and for trying to run Taskcluster locally. 
I think I'm able to reproduce this locally as well now.

**Comment by Jadon-Harris** [comment]
Thanks for your comment @lotas. I've been stuck with this problem for a while. 
If you can reproduce this locally as well and find out some solutions, could you tell me how to fix it?
Thank you in advance.

**Comment by lotas** [comment]
I really appreciate that you submitted this issue. I'm testing it locally right now, there's something wrong with local s3/minio most likely.

**Comment by lotas** [comment]
@Jadon-Harris I think I know what's broken. 
Since we didn't pin `minio/minio` and `minio/mc` to specific version, the newer ones slightly changed CLI API, which prevented `public-bucket` policy to be set to `public`. 
This way artifacts remained private, and when requested by UI were hit with `403`. 

I will push fixes, but it will only be available after release.

To fix this issue manually you have two options:
1. patch `s3_init_buckets` command and change last command to be `'/usr/bin/mc anonymous set public local/public-bucket;'` (instead of `mc policy set`)
2. open Minio console in browser http://localhost:3091/buckets/public-bucket/admin/summary  (credentials to login are seen in docker-compose.yml: `minioadmin` `minopassword`) and manually set **Access Poilcy** to **public**

Thanks again for reporting this!

**Comment by Jadon-Harris** [comment]
It works now! :D
I really appreciate your work. Thank you so much and looking forward to your new release.

**Comment by lotas** [comment]
Awesome! Thanks for the contribution :)

**Comment by petemoore** [comment]
@Jadon-Harris Also feel free to join our [#taskcluster](https://matrix.to/#/!whDRjjSmICCgrhFHsQ:mozilla.org) matrix channel to ask questions etc. We also have [community meetings](https://github.com/taskcluster/taskcluster/discussions/5036#discussion-3783425) on Fridays if you are interested. :+1:

**Comment by Jadon-Harris** [comment]
Okay, I got it! Thank you so much for the invitation!

**Comment by lotas** [comment]
I will reopen this issue because there' still a problem with `live.log` when task is running.

Issue here being that generic-worker that runs in a container launches `livelog` executable that listens on two ports, one for writing and one for reading. 
Later generic-worker exposes `livelog` through a different dynamic port bound to `publicIP` interface or uses `websocktunnel` if it is configured
The trick here would be either to properly set up `websocktunnel` or make exposed port configurable, so it can be deterministic on localhost and can be listed in `docker-compose.yml`, so the artifact would be reachable during task execution

**Comment by Jadon-Harris** [comment]
Thank you Yarik. I think this feature is quite important for my work. Please let me know if  you make it, and I will try to figure it out  at the same time as well.

**Comment by lotas** [comment]
@Jadon-Harris may I ask how you are using/going to use Taskcluster? Maybe you need more specific help/setup?
Running bigger deployment might require additional tools, which are being   developed outside of this repo.

**Comment by lotas** [comment]
I mean, you could also just do `docker compose logs -f generic-worker-standalone` to see same output in real time, but it's less friendly :) would work only as a temp workaround

**Comment by Jadon-Harris** [comment]
I‘m in technical researching now, so I was trynna run it locally. I will summarize the problem I have met and maybe we can talk more details later in the matrix channel.
Thank you for the help anyway.

**Comment by lotas** [comment]
Sure! You can also join the community meting that Pete mentioned above, or just use matrix
