### ISSUE TITLE
d2g does not set all TASKCLUSTER_* env vars that Docker Worker sets

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6471]
I [created](https://github.com/mozilla/community-tc-config/pull/665) a Docker Worker worker pool and a Generic Worker 54.4.1 worker pool, to compare results of identical tasks, to be sure that the Docker Worker compatibility layer is functioning correctly in Generic Worker.

Early results show some differences in environment. Specifically:

Docker worker was setting environment variables:

* `TASKCLUSTER_WORKER_POOL`
* `TASKCLUSTER_WORKER_GROUP`
* `TASKCLUSTER_PUBLIC_IP`
* `TASKCLUSTER_WORKER_TYPE`
* `TASKCLUSTER_INSTANCE_TYPE`

Generic Worker does not set any of the above environment variables. I have some reservations about setting such environment variables, in general, since they encourage task authors to use the information in tasks, which would very much tie them to the taskcluster environment (e.g. making it harder to run tasks locally). However, maybe we need to provide this information to be backwardly compatible. It might be that nothing uses these env vars, but it is hard to know.

Furthermore, Docker Worker was setting this env var correctly, and Generic Worker is not, it seems:

* `TASKCLUSTER_WORKER_LOCATION`

Generic Worker seems to just set it to the empty string.

**Comment by petemoore** [comment]
Here is a task to show the ENV vars under Docker:
* https://community-tc.services.mozilla.com/tasks/CdKq512_S_yKtk7nWhNfng/runs/0/logs/public/logs/live.log

Here is a task to show the ENV vars under Generic Worker:
* https://community-tc.services.mozilla.com/tasks/TAGw1qxASWeht-tFUE3viQ/runs/0/logs/live/public/logs/live.log

**Comment by djmitche** [comment]
Hm, at least for `TASKCLUSTER_WORKER_LOCATION` I remember setting that in both worker implementations. It comes from worker-runner, so perhaps your test task was not deployed in worker-runner.

At any rate, many of the variables are all [documented](https://docs.taskcluster.net/docs/manual/design/env-vars#standard-environment-variables) so should probably be maintained absent a good reason to remove them. The idea was to replace many of the variables that _aren't_ documented, such as TASKCLUSTER_WORKER_TYPE, with `TASKCLUSTER_WORKER_LOCATION`, since that's generally what a task needs, for example, to select a nearby sccache location.

**Comment by matt-boris** [comment]
> Hm, at least for `TASKCLUSTER_WORKER_LOCATION` I remember setting that in both worker implementations. It comes from worker-runner, so perhaps your test task was not deployed in worker-runner.

It looks like it was only set for the simple engine. I'll create a PR here soon that adds it in to the multiuser engine as well.

**Comment by matt-boris** [comment]
Looks like this bit of code was missing from worker runner https://github.com/taskcluster/taskcluster/pull/6589/files#diff-a2bbd922934163a3c852df8727f36c442360b72f3922dfdfd7e9f2148103e9f4
