### ISSUE TITLE
d2g kvm feature will need osGroup: kvm

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6472]
I believe kvm feature of docker worker ensures that the host user is in the `kvm` OS group, in order for the docker container to also have access to kvm. I believe in d2g, tasks that use the kvm feature will also need to add `osGroups: kvm` to the task payload. It isn't entirely clear if `osGroups` feature is working on Linux, so this is something we should explicitly test, e.g. by testing a working payload that uses kvm feature under worker pool:

* `proj-taskcluster/old-docker-worker`

and then testing the same payload under worker pool:

* `proj-taskcluster/gw-ubuntu-22-04`

**Comment by mozfreddyb** [comment]
Hi folks,
just making sure it's properly known (maybe it already is). It looks like our team is requiring this to unblock nested virtualization an important goal of ours. Any estimation when this might be started?

**Comment by jschwartzentruber** [comment]
> It isn't entirely clear if osGroups feature is working on Linux

[Here is a one-off task](https://community-tc.services.mozilla.com/tasks/JI8vt89uSZ-L94sP-Pcigw) to show that `osGroups` feature on Linux is not working (gw version 55.0.1).

Payload contains:

```json
{
  ...
  "osGroups": [
    "kvm"
  ]
}
```

Task has scope `generic-worker:os-group:proj-fuzzing/linux-truber-gw-test/kvm`

Public log contains: [(L260-262)](https://community-tc.services.mozilla.com/tasks/JI8vt89uSZ-L94sP-Pcigw/runs/0/logs/public/logs/live.log#L260-262)
```
[taskcluster 2023-09-06T20:42:00.222Z] Executing command 4: id
uid=1004(task_169403284952733) gid=1005(task_169403284952733) groups=1005(task_169403284952733)
[taskcluster 2023-09-06T20:42:00.223Z]    Exit Code: 0
```

The `kvm` group does exist, shown earlier in the same log: [(L79)](https://community-tc.services.mozilla.com/tasks/JI8vt89uSZ-L94sP-Pcigw/runs/0/logs/public/logs/live.log#L79)
```
crw-rw----+ 1 root                 kvm      10,   232 Sep  6 20:41 kvm
```

Are there any errors in the worker logs for that machine?

**Comment by petemoore** [comment]
> Hi folks, just making sure it's properly known (maybe it already is). It looks like our team is requiring this to unblock nested virtualization - an important goal of ours. Any estimation when this might be started?

Unblocking this with https://github.com/mozilla/community-tc-config/pull/676 until the issue here has been resolved.

**Comment by Eijebong** [comment]
Investigated a bit. There are two issues here.

First issue is due to how the worker runs the command for the task.
When we generate the command to run, we set its `SysProcAttrs` (https://github.com/taskcluster/taskcluster/blob/036143aa29a5f25ec6a7fbfb2fc8740d4b4e6499/workers/generic-worker/process/multiuser_posix.go#L126)

This value comes from here:
https://github.com/taskcluster/taskcluster/blob/036143aa29a5f25ec6a7fbfb2fc8740d4b4e6499/workers/generic-worker/process/multiuser_posix.go#L58-L65

As you can see, this is where we set the command's credential (i.e, which user/groups will that command be run with). There a `Groups` field in there that is not set which should contain extra groups that should be shared. Local testing shows that if omitted, no extra groups except the `Gid` one will be given to the command.

```go
package main

import (
	"fmt"
	"os/exec"
	"syscall"
)

func main() {
    cmd := exec.Command("groups")
    attrs := &syscall.SysProcAttr {
        Credential: &syscall.Credential {
            Uid: 1000,
            Gid: 1000,
        },
    };
    cmd.SysProcAttr = attrs

    out, err := cmd.Output()
    if err != nil {
        fmt.Printf("Error: %s", err)
        return
    }
    fmt.Printf("%s", out)
}
```
```
[eijebong@plutonium] ~  >>> groups
seat plugdev libvirt docker eijebong
[eijebong@plutonium] ~  >>> sudo ./main
eijebong
```

Adding the `Groups` field set to some arbitrary value, we can see that I can even run the command as my user but with groups that I'm not in.

```diff
+ Groups: []uint32{11},
```
```
[eijebong@plutonium] ~  >>> sudo ./main
eijebong ftp
```

A solution becomes quite visible, let's set that `Groups` in the `SysProcAttr` struct to the list of groups for the user. Did that, nothing changes.
There comes the second issue. Order. 

Because `OsGroup` is a "feature", it is only "started" after we got a task to run. The issue here is that the `SysProcAttr` struct is generated very early on, while the worker checks if it needs to refresh the current user.

It is created by that call https://github.com/taskcluster/taskcluster/blob/036143aa29a5f25ec6a7fbfb2fc8740d4b4e6499/workers/generic-worker/multiuser.go#L91
which you can trace back up to https://github.com/taskcluster/taskcluster/blob/036143aa29a5f25ec6a7fbfb2fc8740d4b4e6499/workers/generic-worker/main.go#L400 (not gonna paste the chain...)
Features are started when the task runs, which is a few lines after https://github.com/taskcluster/taskcluster/blob/036143aa29a5f25ec6a7fbfb2fc8740d4b4e6499/workers/generic-worker/main.go#L430

Which means the user is added to the group after we decided which groups the task command should see.

A solution here would be to either refresh the `SysProcAttrs` somehow when the `OsGroup` feature is started or to generate it later on.

**Comment by petemoore** [comment]
@jschwartzentruber The latest release of Generic Worker (55.3.3) looks to be working as required. See:
  * https://community-tc.services.mozilla.com/tasks/FzrNvFSoShmpCgS245retA/runs/0/logs/public/logs/live.log#L34

Can you check if you are happy with the new behaviour from #6591 ?

Note, this issue is still open because there is work to do with d2g to convert docker-worker payloads appropriately, but the underlying Generic Worker feature we believe to be working correctly now, so this should hopefully unblock you using Generic Worker.

**Comment by matt-boris** [comment]
We'll likely need to patch our bootstrap scripts to install some additional packages for this feature, as well as look into the required groups a user needs to be in https://help.ubuntu.com/community/KVM/Installation.

**Comment by matt-boris** [comment]
In order to use kvm, it looks like `enableNestedVirtualization` needs to be set to `true` in the worker pool config.

https://cloud.google.com/compute/docs/instances/nested-virtualization/enabling
