### ISSUE TITLE
Long-running tasks cause "NetworkError when attempting to fetch resource." in generic-worker livelog feature

### ISSUE THREAD

**Issue by gabrielBusta** [taskcluster/taskcluster#6563]
**Bug description**

We are using the livelog feature on `generic-worker` to monitor long running tasks. The live logging works for some time (maybe around 24 hours.) After a while we start seeing "NetworkError when attempting to fetch resource." in the log view.

**To reproduce**
1. Go to a long running task that has been executing for a while
2. Click on "View Live Log"
4. See "NetworkError when attempting to fetch resource." error

**Expected behavior**

The livelog should stream logs for the duration of the task.

**Taskcluster version**

55.3.0

**`generic-worker` version**

55.1.1

**Screenshot**

![image](https://github.com/taskcluster/taskcluster/assets/10228658/ddbe9d8c-4616-459a-99a9-998e603905f1)

**Platform**
 
Linux (amd64)

**Additional context**

https://github.com/mozilla/firefox-translations-training/issues/200

**Comment by lotas** [comment]
Thanks Gabriel for submitting this issue. 

When I go now to open that initial link [public/logs/live.log](https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/F3k0tOoOQMaf9q_vJYqFAg/runs/0/artifacts/public%2Flogs%2Flive.log) it now properly redirects, since it points to the existing artifact already. 

I'm not too familiar with websocket proxy internals, but it seems like session tunnel was closed for some reason (which is possible over long period of time), or the session token expired.

Auth service issues websocktunnel tokens which live [up to 96hr](https://github.com/taskcluster/taskcluster/blob/main/services/auth/src/websocktunnel.js#L33)
And it seems like this worker was running [this task](https://firefox-ci-tc.services.mozilla.com/tasks/F3k0tOoOQMaf9q_vJYqFAg/runs/0) for somewhere around 4-5 days.

So there are two possible directions to address this issue:
1. we would patch websocktunnel to take care of expiration aspect of those tokens, and let it refresh the token. This would require releasing new workers/imagesets.
2. we allow larger expiration dates for the tokens in auth service. This would be the quickest fix, but we need to check what would be the implications of letting those tokens live longer 

I don't immediately see why having longer lived tokens would be bad security wise, they don't seem to have much permissions, only allow workers to connect to the tunnel ? @petemoore what do you think?

**Comment by petemoore** [comment]
I don't know too much about websocktunnel, but this comment seems to suggest that token refreshing should already be built in. I'm just not sure how, since this is the only place I see where a token is fetched:

https://github.com/taskcluster/taskcluster/blob/15284ceb5519a79fac025fa2500d4c4cf6389b6b/workers/generic-worker/expose/wst.go#L78-L79

**Comment by djmitche** [comment]
It would be good to know what the underlying network error is that is being describe as a "network error" in the UI, and also to look at the WST logs at that time. Also, does this issue occur any time you try to load the logs after ~24 hours, or is this a single tab actively tailing the live-logs for 24 hours and failing after that time?

The token that the generic-worker exposer gets from `auth.websocktunnelToken` is for the connection from the worker to the websocktunnel server. A new token is fetched before each such connection, and that connection then stays open for however long the network between those two endpoints allows. When that connection fails, generic-worker should reconnect and pick up where it left off. The token is only consulted at the beginning of that connection, which should be only a few seconds after the token was issued.

There's a lot of network and tunnels to consider here, so narrowing down what is going wrong is a good place to start.

**Comment by aerickson** [comment]
Where are the WST logs written?

**Comment by djmitche** [comment]
I think they're just the stdout from the websocktunnel process -- wherever that goes. I don't remember if debug logging is enabled by default.

That wasn't necessarily the data I was suggesting gathering!

**Comment by marco-c** [comment]
Is there a workaround we can employ in the meantime to get access to the live logs?

**Comment by marco-c** [comment]
Looking at https://github.com/mozilla/firefox-translations-training/issues/200#issuecomment-1730366769, it looks like the error we see is 504.

**Comment by petemoore** [comment]
> Looking at [mozilla/firefox-translations-training#200 (comment)](https://github.com/mozilla/firefox-translations-training/issues/200#issuecomment-1730366769), it looks like the error we see is 504.

@lotas @djmitche Any ideas here? It looks like the following line setting the header has been in place for 8 years, so I'm not sure what is going on:

https://github.com/taskcluster/taskcluster/blame/main/tools/livelog/main.go#L53

**Comment by djmitche** [comment]
Nope, same questions remain.

**Comment by marco-c** [comment]
See also #6685.

**Comment by lotas** [comment]
we also realized today that some of those issues might be related to the fact that websocktunnel container is being restarted sometimes! which might result in dropped connections, and if clients do not auto-reconnect, those live logs would be gone

Here are restarts for the past 30d:
<img width="921" alt="image" src="https://github.com/taskcluster/taskcluster/assets/83861/dded6e6d-6d7d-4055-96b7-af933ef0cfb3">

**Comment by bhearsum** [comment]
I noticed this happen with a task that was running earlier today. @lotas had a look at the websocktunnel GCP logs and it does look like the service was restarted around the time the log stopped working, which seems to lend some evidence to the theory above.

@lotas also noticed that the restarts were caused because the pods requested too much memory.

AIUI, this means there's probably two things we might want to do:
- Ensure that workers reconnect if their websocktunnel connection is closed
- Tweak deployment parameters to reduce or eliminate restarts of the service during normal operation
- Investigate and fix and memory leaks in websocktunnel.

**Comment by lotas** [comment]
I think it could have been a deployment configuration thingy.. Before the holidays I increased memory limits, so the pod wouldn't be killed, and it looks like it worked just fine, pod was not killed so frequently! In fact, only once 

<img width="1274" alt="image" src="https://github.com/taskcluster/taskcluster/assets/83861/12edf8c2-849a-4ddb-85dc-9736f559e67c">

It seems like CPU usage was going up, so we likely would have to restart it periodically still (or fix cpu/mem leaks) 
<img width="1016" alt="image" src="https://github.com/taskcluster/taskcluster/assets/83861/440dea00-264f-4cbc-afb8-34e7c0baae37">

**Comment by marco-c** [comment]
@lotas could it be because of lower usage during the holidays?

**Comment by lotas** [comment]
@marco-c very likely yes, but at least we figured out what attributes to those problems. We can try to increase memory limits for now to see how far it can go without rewriting that tunnel.
Maybe it would be even possible to scale them with some sticky sessions

**Comment by djmitche** [comment]
IIRC, a few people looked at this leak and weren't able to find anything obvious. But there's no inherent reason that this leak should exist -- it's definitely a bug.  This is probably an interesting chase for someone familiar with the Go runtime! I think it's worth putting at least _some_ time into that before trying to fix this with deployment trickery.

https://github.com/taskcluster/taskcluster/issues/2659 may be a hint - that this increases so slowly suggests that it's not leaking a lot of memory on every request, but only leaking in specific circumstances -- and maybe one of those circumstances is precisely the one that isn't tested :)

**Comment by marco-c** [comment]
@djmitche I agree we should find the real culprit, but as this is hampering us right now, what if we temporarily increase the memory limits until somebody has free cycles to look at the underlying problem?

**Comment by lotas** [comment]
@marco-c that's exactly what I did so far, doubled memory limits manually to see how far we can go.
Container is being restarted less-frequently as a result, but there are still some conditions that lead to restarts. Possibly k8s scaling nodes and moving pods between them might result in restarts also.
I'm observing logs to see what else happens there.

**Comment by bhearsum** [comment]
I got websocktunnel & generic-worker up and running locally today to do some investigation into how we can get the worker to recommend when the tunnel goes away. I was able to simulate the websocktunnel restarts by running a task, attaching to a live log, and then killing and restarting the websocktunnel process. This is the sequence of events I found after adding some debug logging to the worker:
- As soon as the websocktunnel goes down, we end up trying to reconnect and sitting at the [connectWithRetry call](https://github.com/taskcluster/taskcluster/blob/309ebaaff3d3fb072ae85d079cb1ded0721779cb/tools/websocktunnel/client/client.go#L232).
- When it comes back up we proceed from there
- We end up [calling Session.Close](https://github.com/taskcluster/taskcluster/blob/309ebaaff3d3fb072ae85d079cb1ded0721779cb/tools/websocktunnel/client/client.go#L241) as part `reconnect`
- In Session.Close we end up [exiting early because it of the first check for s.closed](https://github.com/taskcluster/taskcluster/blob/309ebaaff3d3fb072ae85d079cb1ded0721779cb/tools/websocktunnel/wsmux/session.go#L213)
- Back in `reconnect` we run [the remainder of the function and return normally from it](https://github.com/taskcluster/taskcluster/blob/309ebaaff3d3fb072ae85d079cb1ded0721779cb/tools/websocktunnel/client/client.go#L245-L254)

However, even after this I'm unable to reconnect to the live log (just like in production). Eventually I get a 500 error from the websocktunnel process. This is the log output from that process from both the first and second launch of websocktunnel - note that in both cases we see an "added new tunnel" message from when the worker connects, and then reconnects:
```
INFO[0000] starting server                               server-addr=":1080"
INFO[0004] Host=localhost:1080 Path=/                    remote-addr="172.17.0.1:42654" tunnel-id=
INFO[0004] requesting client registration                remote-addr="172.17.0.1:42654" tunnel-id=test-worker-group.bhearsum.60099
INFO[0004] sending url= http://localhost:1080/test-worker-group.bhearsum.60099  remote-addr="172.17.0.1:42654" tunnel-id=test-worker-group.bhearsum.60099
INFO[0004] added new tunnel                              remote-addr="172.17.0.1:42654" tunnel-id=test-worker-group.bhearsum.60099
INFO[0006] Host=localhost:1080 Path=/test-worker-group.bhearsum.60099/log/C_C6RYfKQcCdFzWs0pchrQ  remote-addr="172.17.0.1:42658" tunnel-id=
INFO[0006] request: host=localhost:1080 path=/log/C_C6RYfKQcCdFzWs0pchrQ  remote-addr="172.17.0.1:42658" tunnel-id=test-worker-group.bhearsum.60099
INFO[0006] request: URL: /test-worker-group.bhearsum.60099/log/C_C6RYfKQcCdFzWs0pchrQ  remote-addr="172.17.0.1:42658" tunnel-id=test-worker-group.bhearsum.60099
INFO[0006] attempting to open new stream                 remote-addr="172.17.0.1:42658" tunnel-id=test-worker-group.bhearsum.60099
INFO[0006] stream 0: read waiting                       
INFO[0006] unblock broadcasted : stream 0               
INFO[0006] stream 0: read waiting                       
INFO[0006] push broadcasted : stream 0                  
INFO[0006] push broadcasted : stream 0                  
INFO[0006] streaming http                                remote-addr="172.17.0.1:42658" tunnel-id=test-worker-group.bhearsum.60099
INFO[0006] stream 0: read waiting                       
INFO[0006] push broadcasted : stream 0                  
INFO[0006] stream 0: read waiting                       
INFO[0007] push broadcasted : stream 0                  
INFO[0007] stream 0: read waiting                       
INFO[0008] push broadcasted : stream 0                  
INFO[0008] stream 0: read waiting                       
INFO[0009] push broadcasted : stream 0                  
INFO[0009] stream 0: read waiting                       
INFO[0010] push broadcasted : stream 0                  
INFO[0010] stream 0: read waiting                       
INFO[0011] push broadcasted : stream 0                  
INFO[0011] stream 0: read waiting                       
INFO[0012] push broadcasted : stream 0                  
INFO[0012] stream 0: read waiting                       

<killed and then restarted>


INFO[0000] starting server                               server-addr=":1080"
INFO[0000] Host=localhost:1080 Path=/                    remote-addr="172.17.0.1:47826" tunnel-id=
INFO[0000] requesting client registration                remote-addr="172.17.0.1:47826" tunnel-id=test-worker-group.bhearsum.60099
INFO[0000] sending url= http://localhost:1080/test-worker-group.bhearsum.60099  remote-addr="172.17.0.1:47826" tunnel-id=test-worker-group.bhearsum.60099
INFO[0000] added new tunnel                              remote-addr="172.17.0.1:47826" tunnel-id=test-worker-group.bhearsum.60099
INFO[0004] Host=localhost:1080 Path=/test-worker-group.bhearsum.60099/log/C_C6RYfKQcCdFzWs0pchrQ  remote-addr="172.17.0.1:47834" tunnel-id=
INFO[0004] request: host=localhost:1080 path=/log/C_C6RYfKQcCdFzWs0pchrQ  remote-addr="172.17.0.1:47834" tunnel-id=test-worker-group.bhearsum.60099
INFO[0004] request: URL: /test-worker-group.bhearsum.60099/log/C_C6RYfKQcCdFzWs0pchrQ  remote-addr="172.17.0.1:47834" tunnel-id=test-worker-group.bhearsum.60099
INFO[0004] attempting to open new stream                 remote-addr="172.17.0.1:47834" tunnel-id=test-worker-group.bhearsum.60099
ERRO[0034] could not open stream: path=/log/C_C6RYfKQcCdFzWs0pchrQ  remote-addr="172.17.0.1:47834" tunnel-id=test-worker-group.bhearsum.60099
```

I haven't had time to analyze this any further yet -- but all of this seems to confirm that the worker _is_ actually reconnecting to the tunnel - so that's good at least. My guess at the moment is that there's some additional state in the tunnel that's not being updated when the reconnection happens (note that all of the port numbers around the tunnel change after the restart...). I'll dig into this more again next week.
