### ISSUE TITLE
[UI] Page is blank, exception thrown in console

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#685]
**Describe the bug**
My screen just shows the background dark blue colour, the UI elements aren't showing up.
![Screenshot from 2019-05-02 15-05-24](https://user-images.githubusercontent.com/7784737/57078308-4e1c3b00-6cee-11e9-8941-64998373fd7e.png)

**To Reproduce**
Unsure - perhaps related to a new version of the UI being released?

**Additional context**
```
SyntaxError: expected expression, got '<'
Error: Loading chunk 212 failed.
(missing: https://taskcluster-web.netlify.com/assets/Tasks.ViewTask.66031ca6.js)
The script from “https://taskcluster-web.netlify.com/assets/Tasks.ViewTask.66031ca6.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
```

**Comment by helfi92** [comment]
I will test this out by having a page open then seeing if I can replicate after a new version of the UI is released.

**Comment by djmitche** [comment]
I'm guessing, based on the error logging, that the existing page loaded in the browser is going looking for the named asset, and that asset is gone so it gets an HTML 404 page that does not parse as JS (and has the wrong content-type).

**Comment by helfi92** [comment]
I wasn't able to replicate but it was probably because one of the deployed files changed its filename hash characters.

**Comment by mitchhentges** [comment]
@helfi92 Are you sure you want to close this? This happened to me again today, and it might be a pretty costly end-user experience.
It's not clear to the user if the page is still loading, or if something internal failed.

**Comment by helfi92** [comment]
Hmm, you're right. Let's keep it open.

**Comment by mitchhentges** [comment]
(heads up @helfi92 that I can't re-open this, I think you have to)

**Comment by helfi92** [comment]
Sorry, I thought I did re-open 😅

**Comment by djmitche** [comment]
Following on my earlier comment, it's getting an HTML document instead of a 404 because of the way we configure every URL to serve `index.html`.

Is there a way to hook into the webpack chunk loader?  If that could detect the HTML content-type on a load, that would identify this situation -- and then maybe a popup that informs the user of an update and asks for a reload?

**Comment by helfi92** [comment]
The problem happens when a user is being navigated to a view (chunk) that no longer exists since most views are lazily loaded. Asking to reload the page can become annoying when the user is asked multiple times per day. Instead, what we can possibly do is reload the site with the new url (the page the user is being navigated to) once a chunk fails to load.

**Comment by helfi92** [comment]
This should hopefully be resolved in https://github.com/taskcluster/taskcluster/commit/b710181deed394cc55e7f06ff4848257b98babfb. If ever you experience the same issue, let us know :) Thanks for bringing this up!
