### ISSUE TITLE
[generic worker / osx] - User task_<ID> is shared between all tasks on that Worker.

### ISSUE THREAD

**Issue by strseb** [taskcluster/taskcluster#6970]
**Describe the bug**
It seems that all machines in the mozilla-vpn osx-1 worker queue are always re-using the same user & same task_id. 

ie [macmini-r8-182](https://firefox-ci-tc.services.mozilla.com/provisioners/releng-hardware/worker-types/mozillavpn-b-1-osx/workers/mdc1/macmini-r8-182?sortBy=started&sortDirection=desc) picking some random tasks: 

-> [task-source-test](https://firefox-ci-tc.services.mozilla.com/tasks/K46ltpBxTH2MoMoeu2NIAw/runs/0/logs/public/logs/live.log) runs in  '/opt/worker/tasks/task_171210505492523
-> [task-build-ios](https://firefox-ci-tc.services.mozilla.com/tasks/ahU0_YCaSJmKr6zFjaPuSQ/runs/0/logs/public/logs/live.log) also runs in '/opt/worker/tasks/task_171210505492523

This causes other tasks to carry-over state to the next task. 

**To Reproduce**

1. Go to https://github.com/mozilla-mobile/mozilla-vpn-client
2. Run a task against on any [releng-hardware-osx-1](https://firefox-ci-tc.services.mozilla.com/provisioners/releng-hardware/worker-types/mozillavpn-b-1-osx) worker. i.e Open a Pull request.
3. Run a 2nd task on the same machine.

**Expected behavior**
- Each Task should get an isolated folder `/opt/worker/tasks/task_<someID>` that cannot have been influenced by a previous task.

**Taskcluster version**
v64.2.3

**Comment by petemoore** [comment]
@strseb I'm sorry you've experienced this, it is a problem that has happened several times in the past and is due to misconfiguration of the workers. Can you raise a JIRA ticket for Release SRE team about this? This is a problem with the configuration of the FirefoxCI instance of taskcluster, rather than a problem with the taskcluster product per se. This github repo is only concerned with the taskcluster software product, rather than the configuration of workers in the FirefoxCI deployment of taskcluster. Thanks!

CC @aerickson @rcurranmoz

**Comment by petemoore** [comment]
Some historical references:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1841640#c3
* https://github.com/mozilla-platform-ops/ronin_puppet/pull/390#issue-1264532872
* https://bugzilla.mozilla.org/show_bug.cgi?id=1595217#c398
