### ISSUE TITLE
Some github checks not updated when tasks resolved

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#7136]
In https://github.com/taskcluster/taskcluster/pull/7133 I set the PR to merge on approval. The PR was approved, but the PR didn't get merged, because there were github checks outstanding. However, they were for taskcluster tasks that resolved successfully. Therefore, for whatever reason, the checks didn't get updated.

I can imagine there could be intermittent load/network issues at times either on taskcluster side or github side, so that messages get lost. But ideally recovery would be automatic, so when services resume normal operation, outstanding github checks could be rechecked, even if it is only once per hour while they are outstanding, etc. In that case, even if for a few hours there were problems, ideally in taskcluster we'd have a record of which tasks relate to github checks, and if we have a means to see that those checks are outstanding on the github side, we could routinely attempt update status on github side. Although I can't claim to understand how the communication between github and taskcluster works. 🤣 

PR: https://github.com/taskcluster/taskcluster/pull/7133
Task Group: https://community-tc.services.mozilla.com/tasks/groups/AtpQBDZwTHK6JAy82Dt1dg

**Comment by petemoore** [comment]
Sorry, this is completely invalid. The issue is that the check is looking for an Ubuntu 22.04 task, and we migrated them all to Ubuntu 24.04. 😆

**Comment by lotas** [comment]
Sorry, I think this is just Github expecting some old checks that were there before 

<img width="1209" alt="image" src="https://github.com/taskcluster/taskcluster/assets/83861/6ef764d7-93a6-4d66-a9fc-76a5f1438d68">

since we renamed task names from 22.04 to 24.04 those are, obviously, not running anymore. 

I think we can avoid that in future by not coding worker/os version in the task name and just keep names more generic
