### ISSUE TITLE
Unexpected graceful termination requests and claim-expired tasks

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#7167]
Take a look at e.g. https://community-tc.services.mozilla.com/tasks/f8pxA7E6R4iHc63Mukj7tQ/runs/3/logs/public/logs/live.log#L223

On the fourth attempt of this task, we see a graceful termination request. On the first 3 runs of this task, we had exception/claim-expired resolutions.

We are hitting [this](https://github.com/taskcluster/taskcluster/blob/1f69e1c2dc0cc6470a50944b8ee97fecdd158e8e/workers/generic-worker/main.go#L1153).

There are only two reasons Generic Worker decides to abort a task iirc, one is if you hit the max run time (that didn't happen in this case) and the other is if it believes the machine is about to be shutdown.

This pool runs in ec2, so the aws spot termination handler is be in use.

We don't see this line in the logs of task run 3: https://github.com/taskcluster/taskcluster/blob/1f69e1c2dc0cc6470a50944b8ee97fecdd158e8e/tools/worker-runner/provider/aws/awsprovider.go#L107

I wonder if somehow the task manages to send Generic Worker a `SIGINT` or something similar, even though it shouldn't be possible.

I think the task finally resolved on the 6th run. According to @choller, this has been happening a lot. @jschwartzentruber might have some ideas. This is Generic Worker, running tasks using KVM in EC2 on `c5.metal` instances.

**Comment by jschwartzentruber** [comment]
> I wonder if somehow the task manages to send Generic Worker a `SIGINT` or something similar, even though it shouldn't be possible.

I don't think it's possible since we're running in docker, and we've never seen weird behaviour like that when running this project locally.

My guess is we're hitting spot termination far more frequently than expected. 

From the [EC2 documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-instance-termination-notices.html):
> We recommend that you check for these interruption notices every 5 seconds. 

... and I see the [timer is 30 seconds in worker-runner](https://github.com/taskcluster/taskcluster/blob/1f69e1c2dc0cc6470a50944b8ee97fecdd158e8e/tools/worker-runner/provider/aws/awsprovider.go#L124).

> Interruption notices are emitted on a best effort basis.

... so it's possible we never get the notice, which I think would manifest as `claim-expired`. Is that correct?

Maybe we should just work around this by disabling instance types whenever we see this in a given region. (manually, in the pool definition)
