### ISSUE TITLE
Queue service fails to emit `task-exception` pulse message when run is automatically re-tried

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskcluster#7174]
**Describe the bug**

When a run fails with state `exception` such that it is automatically re-tried, the queue service does not emit a pulse event to the `task-exception` exchange. This happens because the call to `this.publisher.taskException` happens in this else clause:
https://github.com/taskcluster/taskcluster/blob/9afed31dcbad17729523fa84de6beaa5b81bb132/services/queue/src/api.js#L1809

I suspect this was implemented this way intentionally, but I would argue that this is actually a bug. Consider my use case. I'm building an ETL that is aiming to track costs. These runs that get automatically retried, incur just as much cost as any other run, so it's important to track them.

Besides, we emit one event per run in all other cases.. so I don't see why whether there is an automatic retry or not should make any difference.

**Comment by djmitche** [comment]
> Whenever Taskcluster fails to run a message is posted to this exchange

Well, that doesn't clarify the situaion! It would probably be good to update the docs as well.

What are the other events that are emitted per-run? I think all events were intended to be per-task, and for all of the other run resolutions, the task also resolves (failed, success). As written, `task-exception` is only sent when the _task_ resolves with exception, not just the run.

Maybe a new `runException` event would be better?

**Comment by ahal** [comment]
Hmm.. good point.

However, for all other events the task resolves multiple times e.g if it is re-run. So for all intents and purposes, `task-completed` and `task-failed` do get emitted per-run. Though one can certainly argue that this is just by co-incidence.

> Maybe a new runException event would be better?

This may match the semantics better.. but then do we also need `runCompleted` and `runFailed` events? It would be a bit weird to subscribe to `taskEvent` in some cases, but `runEvent` in others.

Then my further question is.. Is it worth implementing new exchanges for mostly semantic reasons? (I say mostly semantic because I can't personally think of a use case for subscribing to the `exception` exchange only when a task resolves.. though I'm sure use cases exist). This feels like something the TC team should answer. I'm not opposed to the new exchanges, aside from a desire to see a fix here landing asap so my ETL gets accurate data quicker :p

**Comment by ahal** [comment]
Also, maybe we should take a different angle here.. Why *doesn't* an exception that gets retried resolve the task? Why is an automatic retry different than a manual retry in this regard?

I might argue that instead of adding new exchanges, we should revisit this decision? Though I don't know what the implications would be.

**Comment by petemoore** [comment]
> Why is an automatic retry different than a manual retry in this regard?

I think the issue is that taskcluster considers certain `<state>/<reason resolved>` combinations to be final, and thus the task is considered to be resolved.

* `completed/completed`
* `failed/failed`
* `exception/canceled`
* `exception/deadline-exceeded`
* `exception/malformed-payload`
* `exception/superseded`

but others are considered non-final, and result in a new task run being scheduled.

* `exception/claim-expired`
* `exception/worker-shutdown`
* `exception/resource-unavailable`
* `exception/internal-error`
* `exception/intermittent-task`

Therefore, without interference from a user, under the current design, a task should be published as resolved to a pulse exchange once. If a user/system reruns a task outside of the usual workflow, it can be resolved more than once. Another way of saying this, is that a message is eventually published once for every time a task is either created, or rerun.

I think it would be good for us to talk this through at mozweek, indeed Dustin makes a valid point, that the proposed approach is a fundamental shift to the current publishing mechanics.

**Comment by ahal** [comment]
> I think the issue is that taskcluster considers certain <state>/<reason resolved> combinations to be final

Why does Taskcluster need to track "finality"? What if we just did away with "finality" as a concept entirely? It seems like it's going to be a grey area no matter what due to a user's ability to rerun any already failed or completed task.

**Comment by djmitche** [comment]
That's true - the point at which a task is fully immutable is when its deadline is in the past, and all other statuses are just for the latest run.

It's worth thinking about what might be depending on this "gray area", but also reasonable to make it more distinct.

**Comment by lotas** [comment]
I'm +1 in the change makes sense camp. 
Major breaking change would be necessary, but I wonder how many integrations that were build around it that are still running and rely on this logic?
