### ISSUE TITLE
WMIC Deprecation impacting Generic Worker on Windows 11 24H2

### ISSUE THREAD

**Issue by jwmoss** [taskcluster/taskcluster#7235]
**Describe the bug**
Release SRE are building images to prepare for the next feature release of Windows 11, which is 24H2, slated to be released in October, 2024. Microsoft will deprecate `wmic` (article [here](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/ba-p/4039242)) in 24H2. When running generic worker, it seems that it relies on `wmic` for creating a new windows user.

**To Reproduce**
Install generic worker on Windows 11 24H2 and run a task. The failure will be similar to `exec: "wmic": executable file not found in %PATH%`.

**Expected behavior**
There should be no errors about `wmic`.

**Taskcluster version**
68.0.2

**Screenshots**
![image](https://github.com/user-attachments/assets/f78b9c09-bb18-4585-a56f-08a60c3890c1)

**Additional context**

**Comment by petemoore** [comment]
`wmic` is currently used at two places in:

https://github.com/taskcluster/taskcluster/blob/773e652d3a6578d78390e19fe653d8425c44e3f7/workers/generic-worker/runtime/runtime_windows.go

**Comment by ErichDonGubler** [comment]
Seems like the solution is to migrate to using the PowerShell commandlets for WMI/CIM? https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/07-working-with-wmi?view=powershell-7.4

**Comment by petemoore** [comment]
Thanks Erich! Another option might be wrapping the [win32 api](https://learn.microsoft.com/en-us/windows/win32/api/lmaccess/nf-lmaccess-netuseradd) like we do with other win32 apis [here](https://github.com/taskcluster/taskcluster/blob/773e652d3a6578d78390e19fe653d8425c44e3f7/workers/generic-worker/win32/win32_windows.go).

**Comment by petemoore** [comment]
Looking closer, I see we have

```
"net", "user", user.Name, user.Password, "/add", "/expires:never", "/passwordchg:no", "/y"
```

and then later

```
"wmic", "useraccount", "where", "name='" + user.Name + "'", "set", "passwordexpires=false"
```

It isn't clear to me right now why we need to set `passwordexpires=false` in the wmic command when we already specified `/expires:never` in the net user command. But perhaps that relates to user account expiry, rather than password expiry. In any case, it might be able to rewrite the wmic command using just net user?

The other placed it is used is to list local accounts on the machine. That might be entirely possible with a different native command too... So before we start wrapping win32 apis or calling powershell, it may just be worth checking if there are other standard cli tools that ship with windows that provide the same features.

**Comment by matt-boris** [comment]
>It isn't clear to me right now why we need to set passwordexpires=false in the wmic command when we already specified /expires:never in the net user command. But perhaps that relates to user account expiry, rather than password expiry? In any case, it might be possible to rewrite the wmic command using just net user?

The `/expires:never` in the `net user` command is in reference to the _account_ never expiring, _not_ the password.

It looks like both of these commands can be combined into one powershell call to [`New-LocalUser`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/new-localuser?view=powershell-5.1).
