### ISSUE TITLE
`next-task-user.json` file not found error running headless CI task

### ISSUE THREAD

**Issue by matt-boris** [taskcluster/taskcluster#7289]
https://github.com/taskcluster/taskcluster/blob/00a76e41309d37f45bdcea1581c929cc93e1f98a/taskcluster/kinds/generic-worker/kind.yml#L171 needs to be tweaked if we enable `headlessTasks` on our CI. Currently https://community-tc.services.mozilla.com/provisioners/proj-taskcluster/worker-types/gw-ci-macos-13/workers/proj-taskcluster/ip-207-254-55-60?sortBy=started&sortDirection=desc has it enabled. I'll quarantine the worker for now.

https://community-tc.services.mozilla.com/tasks/PfKloCFjQdWm2T79C6wn6w/runs/0

```bash
if [ "${ENGINE}" == "multiuser" ]; then
  cp "${TASK_USER_CREDENTIALS}" next-task-user.json
  GORACE=history_size=7 CGO_ENABLED=1 go test -tags "${ENGINE}" -failfast -timeout 20m -ldflags "-X github.com/taskcluster/taskcluster/v71/workers/generic-worker.revision=${GITHUB_SHA}" ${RACE} ${VET} ./...
else
  GORACE=history_size=7 CGO_ENABLED=${CGO_ENABLED_TESTS} go test -tags "${ENGINE}" -failfast -timeout 20m -ldflags "-X github.com/taskcluster/taskcluster/v71/workers/generic-worker.revision=${GITHUB_SHA}" ${RACE} ${VET} ./...
fi
+ '[' multiuser == multiuser ']'
+ cp /var/root/current-task-user.json next-task-user.json
cp: /var/root/current-task-user.json: No such file or directory
```

**Comment by matt-boris** [comment]
Now running into this issue https://community-tc.services.mozilla.com/tasks/bIxhN_dbRo-4OztO13hD_w/runs/0/logs/public/logs/live.log

```bash
+ go test -tags multiuser -failfast -timeout 20m -ldflags '-X github.com/taskcluster/taskcluster/v71/workers/generic-worker.revision=2e81d6807f10fb5f622ebf8aa61a82488e606b5e' ./...
?   	github.com/taskcluster/taskcluster/v71/workers/generic-worker/artifacts	[no test files]
--- FAIL: TestChainOfTrustUpload (0.00s)
    artifacts_multiuser_test.go:23: Could not fetch task user credentials: open /Users/task_172745463113750/taskcluster/workers/generic-worker/next-task-user.json: no such file or directory
```

**Comment by petemoore** [comment]
Thansk for raising this Boris!

Indeed, there are currently some tricks in place in the CI to fool the Generic Worker under test that it has already created a task user, so that it claims a task without first creating a task user and potentially rebooting. This trickery is what enables the CI to run many CI tasks without reboots in between them all. However, it works by making assumptions that the tests are running inside the CI by another Generic Worker that has already created a task user on the host, that the Generic Worker under test can use.

We can fix this by changing the manner in which the task user information gets primed in the Generic Worker under test, however, we will encounter another issue, which is some Generic Worker tests actually test gui features, such as this test: https://github.com/taskcluster/taskcluster/blob/00a76e41309d37f45bdcea1581c929cc93e1f98a/workers/generic-worker/multiuser_windows_test.go#L105-L144

Since e.g. that test requires a GUI, probably the CI host will also need a GUI enabled, in other words, the worker pools used to test Generic Worker (with `gw-ci` in the name) may need to have `headlessTasks: false`. At that point, this CI failure will go away too, so we might be able to leave the existing "tricks" in place that assume that the host Generic Worker is running multiuser engine and not running in Headless mode.

**Comment by petemoore** [comment]
I've updated https://github.com/taskcluster/community-tc-config/pull/833

Maybe we can set `headlessTasks` explicitly to `false` on the macOS workers and unquarantine [ip-207-254-55-60](https://community-tc.services.mozilla.com/provisioners/proj-taskcluster/worker-types/gw-ci-macos-13/workers/proj-taskcluster/ip-207-254-55-60?sortBy=started&sortDirection=desc)?

**Comment by petemoore** [comment]
This should be fixed now that we have headless mode disabled on the gw-ci workers...
