### ISSUE TITLE
switch python client to use pytest

### ISSUE THREAD

**Issue by escapewindow** [taskcluster/taskcluster#749]
pytest is a better test framework; let's use it.

**Comment by melvin2016** [comment]
where should i start?

**Comment by djmitche** [comment]
Hi!  Probably a good place to start is to get the repository checked out and get the *current* test suite running.  You'll want to work in the `clients/client-py` subdirectory of this repository -- you can safely ignore everything else in the repository.

Once that's working for you, let's come up with a plan to use pytest, instead of the existing `unittest` approach.  Rewriting one or two of the tests to use Pytest will be a nice proof-of-concept, but we'll want all of them rewritten in order to merge the changes.

**Comment by helfi92** [comment]
@melvin2016 Are you still working on this?

**Comment by melvin2016** [comment]
Sorry for this.. can you take this up

**Comment by Shubhamchinda** [comment]
Hey, can I work on this ?

**Comment by djmitche** [comment]
You sure can!  My comments from June 1 should get you started.

**Comment by Shubhamchinda** [comment]
> You sure can! My comments from June 1 should get you started.

Thanks, I'll look into it and ask you if I get stuck.

**Comment by Patil2099** [comment]
There is no requirements.txt file Adding one would save some time in installing dependencies @djmitche

**Comment by djmitche** [comment]
@Patil2099 that sounds like a good PR!

**Comment by Patil2099** [comment]
Where should I add the text file ?

**Comment by djmitche** [comment]
where you'd expect to find it :)

**Comment by carpecodeum** [comment]
hey can i work on this issue? this would be a good first issue for me.

**Comment by djmitche** [comment]
I believe @Shubhamchinda is already working on it -- sorry!

**Comment by vishakhanihore** [comment]
@djmitche Its good to be closed now I think.
