### ISSUE TITLE
Allow users to login via Auth0

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#750]
This would involve granting web-server root scopes.

**Comment by helfi92** [comment]
@djmitche auth0 logins in https://taskcluster-staging.net/ is done. Did you want to test it?

**Comment by djmitche** [comment]
will do!

**Comment by djmitche** [comment]
This is looking good -- it all works, at least after #764.  I'm glad we're testing this in staging, as any issues here are low-stakes.  Auth0 logins, in particular, seem fine, and are similar enough to the existing login flow that I think we can safely deploy them soon.  Github looks like it is not so straightforward, unfortunately.  We should probably do an RRA for that functionality.

Anyway, here are some of the concerns I uncovered:

## Staying Signed In..

Looking at `ui/src/auth/AuthController.js`, it seems to delete the _user_ (including access_token) if the _credentials_ (the TC clientId, etc., valid only for 15m) are expired when loadUser is called, which occurs at page load when the App component is mounted.  I would expect this to result in a user being signed out when visiting the site after more than 15 minutes with no tabs open.  

That said, I can't reproduce this -- so I suspect this is something you've gotten right and I'm just not connecting the dots.  Otherwise, this is good for followup, but probably high-priority as people will complain about being logged out when there are no TC tabs open.

## Automatic Refreshes

The automatic credential refreshing seems to be timer-based, meaning that someone with an open tab will poll for new credentials every 15 minutes.  That is probably a simpler model than what we do in tools (re-request credentials just before making an API call, if necessary) -- good call.  However, I think multiple tabs will all try to renew at the same time.  We [applied some randomization](https://github.com/taskcluster/taskcluster-tools/blob/17302c900904b892bc66f359c683e855beccb9a3/src/auth/AuthController.js#L50-L55) in tc-tools to try to avoid that: in most cases one tab will try to renew first, and the others will learn about it via the resulting LocalStorage event.  This is a good followup fix, too.

## Scanning

The client scanner is defined, but not currently set up to run in kubernetes or in Heroku.  We probably shouldn't run it in Heroku (since tc-login is still handing out credentials there) but it should be set up to scan in other deployments, and we should test that it works correctly (I was also going to say it should have tests like it does in tc-login, but I see now there are no tests for tc-login's scanner!).

## GitHub access_tokens and User Consent

There's a problem with the Github support, though.  Any GitHub accessToken can be traded for credentials.  So some "toy" app that asks the user to sign in with Github could easily call any Taskcluster API methods as that user, without that user's permission.  STR:

 * Set up an OAuth app named "rate cute pandas" with callback URI http://localhost:3000
 * Simulate a login to the app with a trip to `https://github.com/login/oauth/authorize?client_id=<your-client-id>&redirect_uri=http://localhost:3000`
 * Click "Authorize"
 * Collect the code from the resulting URL
 * Simulate the app's backend trading that code for an access token with `curl -XPOST 'https://github.com/login/oauth/access_token?client_id=<your-client-id>&redirect_uri=http://localhost:3000&client_secret=<your-client-secret>&code=<the-code>`
 * Collect the resulting accessToken
 * Run the following GraphQL:
   ```
    query getCreds {
        getCredentials(provider: GITHUB, accessToken: "<collected-access-token>") {
            credentials { clientId accessToken certificate }
            expires
        }
    }
    ```
  * Result: Taskcluster credentials for a user that never authorized access to TC on their behalf.

NOTE: CORS will not help with this -- it would merely require that Mal attach an "Origin: https://taskcluster-staging.net" Header to the GraphQL request.

I don't have any fixes for this in mind.. what do you think?  Note that the last place in the process where we have something that requires the app's client_secret is the `curl` command.

## GitHub user_id's in identities

.. just a placeholder that #704 still needs to be finished up and landed..

**Comment by helfi92** [comment]
Thanks for looking into this @djmitche.

> Staying Signed In..

I've created https://github.com/taskcluster/taskcluster/issues/767 to make sure I look into this ASAP as a follow-up.

> Automatic Refreshes

I've created https://github.com/taskcluster/taskcluster/issues/768 to look into this in a follow-up

> Scanning

I've filed https://github.com/taskcluster/taskcluster/issues/769. Agreed. we should try to have it run in our deployments.

> GitHub access_tokens and User Consent

I don't plan to allow users to login via GitHub initially until we have the roles figured out. I don't think it should be a blocker to shipping auth0 logins to our users. Let me know if you disagree.

> GitHub user_id's in identities

👍

**Comment by helfi92** [comment]
https://taskcluster-ui.herokuapp.com/ is configured to only allow auth0 logins. @djmitche Do you have any objections if I go ahead and provide the following scopes to [`project/taskcluster/tc-web-server/production`](https://taskcluster-ui.herokuapp.com/auth/clients/project%2Ftaskcluster%2Ftc-web-server%2Fproduction) https://github.com/taskcluster/taskcluster/blob/b3771d6b17e037dcb867d0e19e2e6277951465b9/infrastructure/terraform/auth-service.tf#L67-L77

**Comment by helfi92** [comment]
Note to self:

Once scopes have been granted,
* Merge https://github.com/taskcluster/taskcluster-tools/pull/604
* Remove https://taskcluster-web.netlify.com/ and only keep preview URLs on netlify

**Comment by djmitche** [comment]
> I don't plan to allow users to login via GitHub initially until we have the roles figured out. I don't think it should be a blocker to shipping auth0 logins to our users. Let me know if you disagree.

I agree.

> Do you have any objections ..

I don't -- let's go!

**Comment by helfi92** [comment]
Users are now able to login via Auth0. Closing as resolved.
