### ISSUE TITLE
[UI] Go to line feature stops working when follow log is first clicked

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#908]
STR:

1. Navigate to http://localhost:5080/tasks/fRav6OG-Sbij116H7gfqag/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FfRav6OG-Sbij116H7gfqag%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log
2. Click the follow log button

![Screen Shot 2019-06-25 at 8 52 38 AM](https://user-images.githubusercontent.com/3766511/60099910-7a13d580-970d-11e9-8e26-bf0305b3f8a1.png)

3. Click the "1 2 3" icon button and enter a line number (e.g., 4) then click on "Go To Line".

**Expected:** Log jumps to the selected line number
**Actual:** Log does not jump to the selected line number.

**Comment by arku** [comment]
@helfi92 Do you mind helping me understand how the 'Go to Line' feature works?

**Comment by helfi92** [comment]
Sure. The LazyLog component (aka log viewer) accepts a `scrollToLine` prop which will theoretically jump to that line when that value changes. I think the logic for that can be found [here](https://github.com/mozilla-frontend-infra/react-lazylog/blob/e8951828d6ac4e94d0592b501921de73ced4d990/src/components/LazyLog/index.jsx#L293-L299).

For some reason, when we click the follow log icon, the jump to line feature stops functioning properly. The problem could either be in this repo or in https://github.com/mozilla-frontend-infra/react-lazylog.

Does that help? Let me know if you had more questions.

**Comment by arku** [comment]
@helfi92 Thanks for clearing it up. Gonna take a look at it.

Will get back to you after making some progress.

**Comment by helfi92** [comment]
Awesome! Also thanks for helping other contributors on the other issues :)

**Comment by arku** [comment]
@helfi92 Looks like the issue is on [this line](https://github.com/mozilla-frontend-infra/react-lazylog/blob/e8951828d6ac4e94d0592b501921de73ced4d990/src/utils.js#L20). When the 'Follow Log' icon is clicked, the `follow` property in `Log` component's state is set to `true` and is never reset when `lineNumber` is updated. And it looks like the 'Go to line' functionality isn't working when actually the `scrollToIndex` function always returns `count - 1 - offset` as `follow` is true.

Let me fix it.

**Comment by arku** [comment]
@helfi92 I have submitted a [PR](https://github.com/taskcluster/taskcluster/pull/984) fixing the issue. Take a look when you get a chance.

**Comment by helfi92** [comment]
Nice! Well done tracking the issue down. I'll take a look soon.

**Comment by arku** [comment]
@helfi92 Perfect, thanks!

Btw, I noticed another bug when you try to go the first line. I created an [issue](https://github.com/taskcluster/taskcluster/issues/985) for it.

I guess it happens because the [`getScrollToIndex`](https://github.com/mozilla-frontend-infra/react-lazylog/blob/e8951828d6ac4e94d0592b501921de73ced4d990/src/utils.js#L12) function [returns 0 when `lineNumber` is 1](https://github.com/mozilla-frontend-infra/react-lazylog/blob/e8951828d6ac4e94d0592b501921de73ced4d990/src/utils.js#L24). I could be wrong though.

What do you think?

**Comment by helfi92** [comment]
That's very possible and I think you may be right here :)
